Automattic/newspack-newsletters

includes/class-newspack-newsletters-renderer.php

Just a tiny tweak so that PHP does not log a notice.

Ensure attribute exists in renderer

---

includes/class-newspack-newsletters-settings.php

Avoid confusion with the wording when user enters its MJML api keys
2. Navigate to Settings > Newspack Newsletters

Update settings description to match MJML api email

---

src/editor/sidebar/index.js

Reorder the sidebar settings and change priority on the send email button
1. Open the sidebar
3. Refresh
4. Check the sidebar now

Reorder the sidebar settings

---

composer.lock
includes/class-newspack-newsletters.php
src/editor/sidebar/index.js

Adds support for Mailchimp Groups, previously known as "Interests." After list selection, if the list has Groups defined a second `SelectControl` appears below with all Groups. The first option is `-- Select a group --`. The select will have an item for each "group grouping" then an indented item for each group. Selecting the groupings will have no effect. Selecting the groups will set the segment for the current campaign. Selecting `-- Select a group --` will unset the segment. 
Closes https://github.com/Automattic/newspack-newsletters/issues/20
1. Following instructions in https://mailchimp.com/help/getting-started-with-groups/, set up a few groups in one or more Mailchimp lists.
2. Create a new Newsletter, choose any template. In the sidebar, select a list with groups. 
3. Observe the …

Mailchimp Groups

---

src/editor/editor/style.scss

Closes #55
1. Add a Button block
2. Observe that the buttons are aligned to center

Fix button block alignment

---

includes/class-newspack-newsletters.php
src/editor/sidebar/index.js

small stuff
Closes https://github.com/Automattic/newspack-newsletters/issues/82

Fix missing import; remove EOL spaces

---

src/editor/blocks/posts-inserter/index.js
src/editor/blocks/posts-inserter/style.scss
src/editor/editor/style.scss
src/editor/sidebar/index.js

This PR updates the style of the placeholder.
__Before:__
__After:__
1. Add a Post Inserter block
3. Refresh

Update post inserter placeholder style

---

includes/class-newspack-newsletters-renderer.php
includes/class-newspack-newsletters.php

Closes #100
1. Create or edit a newsletter
2. Insert a spacer block
3. Preview or send an email - observe that the spacer block is rendered as expected

Add spacer block support

---

src/editor/sidebar/index.js

This notice is not used anymore.

Remove unused notice

---

includes/class-newspack-newsletters.php

Adds try/catches to the API endpoint callbacks for setting Mailchimp list, and setting Mailchimp groups. This type of PR is difficult to test (which I guess is good!). I recommend manually editing `includes/class-newspack-newsletters.php` and introducing bad values in `api_set_mailchimp_list` and `api_set_mailchimp_interest` payloads to verify the notifications. 
Partially addresses https://github.com/Automattic/newspack-newsletters/issues/24
_Note about future approach: after v1 I'm planning to add `$preferred_error` text for all Mailchimp operations, so that end users do not see the original Mailchimp error messages. I'll also add a debug flag which disables these messages, allowing us to optionally see the Mailchimp errors for more accurate debugging. For now, most failures will show …

feat: error catching and notification for lists and groups

---

newspack-newsletters.php

docs: tweak

---

src/editor/index.js

Move the Testing Panel above Layout, for easier access to the more commonly used feature.
Closes https://github.com/Automattic/newspack-newsletters/issues/157#issuecomment-620079866
Verify the Testing Panel's placement above Layout.

feat: move testing panel above layout

---

.github/workflows/main.yml
includes/class-newspack-newsletters-renderer.php
includes/email-template.mjml.php
package-lock.json
package.json
src/components/template-modal/screens/template-picker/index.js
src/components/template-modal/style.scss
src/editor/blocks/posts-inserter/consts.js
src/editor/blocks/posts-inserter/deduplication.js
src/editor/blocks/posts-inserter/index.js
src/editor/blocks/posts-inserter/query-controls.js
src/editor/blocks/posts-inserter/style.scss
src/editor/blocks/posts-inserter/utils.js
src/editor/editor/style.scss
src/editor/layout/index.js
src/editor/layout/style.scss
src/editor/sidebar/style.scss

Release 4/30/20

---

src/components/template-modal/style.scss
src/editor/blocks/posts-inserter/style.scss
src/editor/editor/style.scss

Better preview with the correct margins of the Post Inserter for the Layout Modal, the Editor, and the Sent Newsletter.
2. Add new, when viewing the Layout Modal, check the different posts
3. Insert posts, compare with Post Inserter
4. Send test, compare with Editor

Update posts inserter preview margins

---

src/newsletter-editor/layout/index.js

Fixes a regression that led to sluggish typing in `TextControl`s in the sidebar. 
Closes https://github.com/Automattic/newspack-newsletters/issues/186
1. Verify typing in the Subject, From Name, and Email fields feels natural and speedy.
2. Verify the post flickering corrected in https://github.com/Automattic/newspack-newsletters/pull/183 is still not happening.

fix: sticky text controls

---

includes/class-newspack-newsletters-layouts.php
includes/class-newspack-newsletters.php
src/components/init-modal/screens/layout-picker/SingleLayoutPreview.js
src/components/init-modal/screens/layout-picker/index.js
src/components/newsletter-preview/index.js
src/components/newsletter-preview/style.scss
src/newsletter-editor/layout/index.js

Adds handling of custom styling (fonts, background color) to layouts.
Closes #225.
1. Create a newsletter, set custom styling, save as layout
2. Observe that the layout preview updated in the sidebar Layout tab accordingly
3. Create a new newsletter, observe the custom styles applied in layout previews (in layout chooser and big preview)
4. Choose a custom-styled layout, update styles, update layout – observe the layout is updated in the sidebar preview 
5. Observe the layout is updated in the layout picker when creating new newsletter

Add layout styling settings handling

---

composer.lock
includes/class-newspack-newsletters.php
src/components/with-api-handler/index.js
src/newsletter-editor/editor/index.js

Adds more visible "sent" status labeling in Newsletter posts list and block editor.
In posts list:
In block editor:
Closes #26.
1. Pull this branch and rebuild JS.
2. Create a new newsletter and send it. Observe an undismissible "Campaign sent" notice appearing at the top of the block editor after the post status changes to `publish`. In this view, the date is shown in the user's local format using [`toLocaleString()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString).
3. Go back to the list of all newsletters. Observe a "Sent" label with the publish date next to the post title. In this view, the date is shown in whatever format the site is using in General Settings.

Add "sent" labels to dashboard and editor

---

includes/class-newspack-newsletters-ads.php
includes/class-newspack-newsletters-editor.php
includes/class-newspack-newsletters-renderer.php
includes/class-newspack-newsletters.php
package-lock.json
package.json
src/ads-admin/AdsManager/index.js
src/ads-admin/AdsManager/style.scss
src/ads-admin/consts.js
src/ads-admin/editor/index.js
src/ads-admin/index.js
src/ads-admin/utils.js
src/components/send-button/index.js
src/editor/style.scss
src/newsletter-editor/editor/index.js
src/newsletter-editor/editor/style.scss
src/utils/consts.js
webpack.config.js

Adds self-serve ads. Note that the ads will be placed at the bottom of the email – setting placement will be handled in another PR (issue: #237 ), as this one is pretty big already.
Closes #166 
1. Observe a new item under "Newsletters" menu in admin - "Ads". Visit that page:
2. Click "Create new ad". Create the content and try to publish – observe that it's not possible until an expiry date is set in the sidebar. If an expiry date is set in the past, a warning notice should be shown in the pre-publish panel.
3. Go back to the "Ads" view – observe the new ad being listed there. 
4. Create a new newsletter and send a test email. Observe the ad being appended to the bottom of the email (but above the ESP footer)
5. Send the newsletter – observe a notice in the pre-send modal about the ads …

Add self-serve ads

---

includes/class-newspack-newsletters-renderer.php
includes/service-providers/class-newspack-newsletters-service-provider-controller.php
includes/service-providers/class-newspack-newsletters-service-provider.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp-controller.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
src/ads-admin/AdsManager/index.js
src/ads-admin/editor/index.js
src/ads-admin/utils.js
src/components/send-button/index.js
src/components/send-button/style.scss
src/editor/index.js
src/service-providers/mailchimp/ProviderSidebar.js
src/service-providers/mailchimp/index.js
src/service-providers/mailchimp/style.scss
src/service-providers/mailchimp/utils.js

Release 07/07/2020

---

includes/class-newspack-newsletters-renderer.php
includes/class-newspack-newsletters.php
includes/email-template.mjml.php
src/newsletter-editor/sidebar/index.js
src/newsletter-editor/sidebar/style.scss
src/newsletter-editor/styling/index.js

Closes #275.
1. Create a new newsletter
2. Observe a new field in Newsletter section of the sidebar - "Preview text"
3. Fill in the preview text, update it by clicking the button below
4. Send a test newsletter – observe the preview text displayed in the email client
5. Send the campaign – observe the preview text displayed in the email client
6. Create a newsletter without a preview – observe no preview in the email client

Add preview text option

---

composer.json
composer.lock
includes/class-newspack-newsletters-ads.php
includes/class-newspack-newsletters-editor.php
includes/class-newspack-newsletters-renderer.php
includes/class-newspack-newsletters.php
includes/email-template.mjml.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact-controller.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
newspack-newsletters.php
src/ads-admin/AdsManager/style.scss
src/ads-admin/editor/index.js
src/ads-admin/editor/style.scss
src/newsletter-editor/sidebar/index.js
src/newsletter-editor/sidebar/style.scss
src/newsletter-editor/styling/index.js
src/newsletter-editor/testing/index.js
src/service-providers/constant_contact/ProviderSidebar.js
src/service-providers/constant_contact/index.js
src/service-providers/index.js

Release Aug 04

---

src/editor/blocks/posts-inserter/query-controls.js
src/editor/blocks/posts-inserter/style.scss
src/editor/blocks/posts-inserter/utils.js

Closes #278
Closes #246
Closes #279
1. Use Posts Inserter in a Newsletter, observe maximum 20 posts can be insterted
2. Set an excerpt for a post, observe that Posts Inserter will now display the excerpt
3. Use a Heading block in a Newsletter, turn part of the text into a link
4. Observe the link color is same as text color
4. Set a custom text color to the Heading, observe the color is also set to the link

Fix assorted bugs

---

src/editor/blocks/posts-inserter/index.js
src/editor/blocks/posts-inserter/utils.js

Closes #282
1. Create a newsletter with Posts Inserter block. Observe that the styling of text and heading is as before.
2. Observe a preview or send a test email – observe the styles applied as they are in the editor
2. Observe two new panels in the sidebar – "Text style" and "Heading style"
3. Change styles of both text and headings – observe changes reflected in the editor
1. Observe a preview or send a test email – observe the styles applied as they are in the editor

Posts Inserter: add color, font size styling options

---

src/service-providers/mailchimp/index.js

1. On `master` and using Mailchimp provider,
2. Create a newsletter, click "Send" before setting a list
3. Observe an unrecoverable error
4. Switch to this branch, repeat 2. 
5. Observe no error being thrown, but a pre-send modal

Presend info bug fix

---

includes/class-newspack-newsletters-renderer.php
includes/class-newspack-newsletters-settings.php
includes/class-newspack-newsletters.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
includes/service-providers/interface-newspack-newsletters-wp-hookable.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
src/components/send-button/index.js
src/newsletter-editor/editor/index.js
src/newsletter-editor/index.js
src/newsletter-editor/public/index.js
src/newsletter-editor/public/style.scss
src/newsletter-editor/sidebar/index.js
src/service-providers/mailchimp/index.js

Alpha release Aug 20

---

includes/class-newspack-newsletters-renderer.php
includes/class-newspack-newsletters-settings.php
includes/class-newspack-newsletters.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
includes/service-providers/interface-newspack-newsletters-wp-hookable.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
src/components/send-button/index.js
src/newsletter-editor/editor/index.js
src/newsletter-editor/index.js
src/newsletter-editor/public/index.js
src/newsletter-editor/public/style.scss
src/newsletter-editor/sidebar/index.js
src/service-providers/mailchimp/index.js

Release 8/20/2020

---

includes/class-newspack-newsletters.php
newspack-newsletters.php

Update the icon of the Newsletter to Material's "Draft". This will match(-ish) the logo and banner for .org page

feat: update icon

---

.circleci/config.yml
includes/class-newspack-newsletters-renderer.php
includes/class-newspack-newsletters.php
includes/email-template.mjml.php
newspack-newsletters.php
src/editor/style.scss

Alpha release Aug 25

---

.circleci/config.yml
includes/class-newspack-newsletters-renderer.php
includes/class-newspack-newsletters.php
includes/email-template.mjml.php
newspack-newsletters.php
src/editor/style.scss

Release Aug 25

---

includes/class-newspack-newsletters.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
package-lock.json

Alpha release Sep 15

---

includes/class-newspack-newsletters.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
package-lock.json

Release Sep 15

---

includes/class-newspack-newsletters.php
src/components/send-button/index.js
src/newsletter-editor/editor/style.scss

Alpha release Sep 22

---

.circleci/config.yml
bin/install-wp-tests.sh
includes/class-newspack-newsletters-renderer.php
phpunit.xml.dist
tests/bootstrap.php
tests/test-renderer.php

Adds testing setup and some basic tests. Most of the files in this PR are generated by WP tests bootstraping.
1. Have a look at `tests/test-renderer.php` – are these tests all right?
1. Verify tests are passing on CI 👇

Add basic PHP tests

---

.circleci/config.yml
bin/install-wp-tests.sh
includes/class-newspack-newsletters-renderer.php
includes/class-newspack-newsletters.php
phpunit.xml.dist
src/components/send-button/index.js
src/newsletter-editor/editor/style.scss
tests/bootstrap.php
tests/test-renderer.php

Release Sep 22

---

includes/class-newspack-newsletters.php
src/components/send-button/index.js

Alpha release – Oct. 7

---

src/newsletter-editor/editor/index.js

Alpha release Oct 20

---

src/components/send-button/index.js
src/newsletter-editor/editor/index.js

Closes #357.
1. Create a newsletter, send it, and make it a public post
2. Observe that it can be updated – both content and the title
3. Observe that if it's made not public, the title disappears

Fix: public newsletter editing fixes

---

includes/class-newspack-newsletters.php
src/components/send-button/index.js
src/newsletter-editor/editor/index.js

Release - Oct. 20

---

.circleci/config.yml
composer.json
composer.lock
includes/class-newspack-newsletters-renderer.php
includes/class-newspack-newsletters-settings.php
includes/class-newspack-newsletters.php
includes/service-providers/campaign_monitor/class-newspack-newsletters-campaign-monitor-controller.php
includes/service-providers/campaign_monitor/class-newspack-newsletters-campaign-monitor.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
newspack-newsletters.php
src/components/init-modal/screens/api-keys/index.js
src/components/send-button/index.js
src/newsletter-editor/editor/index.js
src/newsletter-editor/sidebar/style.scss
src/service-providers/campaign_monitor/ProviderSidebar.js
src/service-providers/campaign_monitor/index.js
src/service-providers/campaign_monitor/style.scss
src/service-providers/index.js

Alpha release Nov 11

---

.circleci/config.yml
composer.json
composer.lock
includes/class-newspack-newsletters-renderer.php
includes/class-newspack-newsletters-settings.php
includes/class-newspack-newsletters.php
includes/service-providers/campaign_monitor/class-newspack-newsletters-campaign-monitor-controller.php
includes/service-providers/campaign_monitor/class-newspack-newsletters-campaign-monitor.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
newspack-newsletters.php
src/components/init-modal/screens/api-keys/index.js
src/components/send-button/index.js
src/newsletter-editor/editor/index.js
src/newsletter-editor/sidebar/style.scss
src/service-providers/campaign_monitor/ProviderSidebar.js
src/service-providers/campaign_monitor/index.js
src/service-providers/campaign_monitor/style.scss
src/service-providers/index.js

Release Nov 11

---

src/newsletter-editor/styling/index.js

Fixing a small bug.
1. On `master`, open a newsletter and set the editor mode to Code editor
2. Edit another newsletter and observe the editor crashing
3. Switch to this branch and rebuild
4. Observe the editor loading as it should

Fix crashing when loading the editor in code view

---

src/newsletter-editor/styling/index.js

Alpha release – Nov. 17

---

src/newsletter-editor/styling/index.js

Release – Nov. 17

---

includes/class-newspack-newsletters-settings.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php

Alpha release Dec 08

---

includes/class-newspack-newsletters-settings.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php

Release – Dec. 8

---

includes/class-newspack-newsletters-renderer.php
src/editor/blocks/posts-inserter/utils.js

Fixes broken image links.
1. Create a Newsletter using the "Daily/Weekly" template (ensure there's a post with a featured image in there)
2. Add an image block and make it link to a site
3. Send a test email – observe the featured image and the interted image block are linking correctly as intended

Fix image links

---

includes/class-newspack-newsletters-renderer.php
src/editor/blocks/posts-inserter/utils.js

Release Dec 09

---

includes/class-newspack-newsletters-renderer.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php

Alpha release Jan 12

---

includes/class-newspack-newsletters-renderer.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php

Release Jan 12

---

includes/class-newspack-newsletters.php

Alpha release Jan 19

---

includes/class-newspack-newsletters.php

Release Jan 19

---

includes/class-newspack-newsletters.php
src/components/send-button/index.js

Alpha release Jan 28

---

includes/class-newspack-newsletters.php
src/components/send-button/index.js

Release Jan 28

---

includes/class-newspack-newsletters-settings.php

Alpha release Feb 24

---

includes/class-newspack-newsletters-editor.php
includes/class-newspack-newsletters-settings.php
includes/class-newspack-newsletters.php
includes/email-template.mjml.php
src/newsletter-editor/editor/index.js
src/newsletter-editor/editor/style.scss

Alpha release Mar 16

---

includes/class-newspack-newsletters-editor.php
includes/class-newspack-newsletters-settings.php
includes/class-newspack-newsletters.php
includes/email-template.mjml.php
src/newsletter-editor/editor/index.js
src/newsletter-editor/editor/style.scss

Release Mar 16

---

includes/class-newspack-newsletters-editor.php
includes/class-newspack-newsletters.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php

Alpha release Mar 23

---

includes/class-newspack-newsletters-editor.php
includes/class-newspack-newsletters.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php

Release Mar 23

---

includes/class-newspack-newsletters.php

A small change that will make public Newsletters much more usable for publishers: adds support for custom excerpts to newsletters.
Closes #431.
1. On `master`, send/publish a newsletter with the "Make newsletter page public" option enabled.
2. Add the newsletter to a Homepage Posts block.
3. Observe that in the Homepage Posts block, the `/newsletter` CPT archive, category/tag archives, and search results, the newsletter appears with an auto-generated excerpt.
4. Check out this branch, edit the newsletter. Confirm that there's now an "Excerpt" sidebar panel to add a custom excerpt.
5. Add a custom excerpt. Now confirm that in the Homepage Posts block, the `/newsletter` CPT archive, category/tag archives, and search results, the newsletter appears with the custom excerpt.

feat: add support for excerpts for newsletter CPTs

---

includes/class-newspack-newsletters-editor.php
includes/class-newspack-newsletters.php
src/editor/blocks/posts-inserter/index.js

Alpha release Mar 30

---

.circleci/config.yml

Same workflow as in https://github.com/Automattic/republication-tracker-tool/pull/95
The changes are pretty hard to test locally or before merge, here's what's expected after these changes are on `master` and `release` is updated afterwards:   
1. A new version tagged and released on Github
2. A new version on WPORG
3. Latest `CHANGELOG.md` and version updated in relevant files on `master`

CI: WPORG releases

---

.circleci/config.yml

A new alpha release. Not really releasing anything, but testing new CI config.

Alpha release Apr 06

---

.circleci/config.yml

Release Apr 06

---

CHANGELOG.md
includes/class-newspack-newsletters-editor.php
newspack-newsletters.php
package-lock.json
package.json
src/editor/blocks/posts-inserter/utils.js
src/service-providers/constant_contact/ProviderSidebar.js
src/service-providers/mailchimp/ProviderSidebar.js
src/service-providers/mailchimp/index.js

Alpha release Apr 13

---

CHANGELOG.md
includes/class-newspack-newsletters-editor.php
newspack-newsletters.php
package-lock.json
package.json
src/editor/blocks/posts-inserter/utils.js
src/service-providers/constant_contact/ProviderSidebar.js
src/service-providers/mailchimp/ProviderSidebar.js
src/service-providers/mailchimp/index.js

Release Apr 13

---

includes/class-newspack-newsletters-renderer.php
tests/test-renderer.php

Closes #344.
1. Create or edit a newsletter, insert some reusable blocks (or create new ones from the existing content)
2. Send a test email, observe that the contents of reusable blocks are rendered as expected

Handle reusable blocks

---

CHANGELOG.md
includes/class-newspack-newsletters-renderer.php
newspack-newsletters.php
package-lock.json
package.json
tests/test-renderer.php

Alpha release Apr 27

---

CHANGELOG.md
includes/class-newspack-newsletters-renderer.php
newspack-newsletters.php
package-lock.json
package.json
tests/test-renderer.php

Release Apr 27

---

CHANGELOG.md
includes/class-newspack-newsletters.php
newspack-newsletters.php
package-lock.json
package.json
src/editor/blocks/posts-inserter/index.js
src/editor/blocks/posts-inserter/utils.js
src/newsletter-editor/editor/index.js
src/newsletter-editor/sidebar/index.js
src/newsletter-editor/styling/index.js
src/newsletter-editor/styling/style.scss

Alpha release May 13

---

CHANGELOG.md
includes/class-newspack-newsletters.php
newspack-newsletters.php
package-lock.json
package.json
src/editor/blocks/posts-inserter/index.js
src/editor/blocks/posts-inserter/utils.js
src/newsletter-editor/editor/index.js
src/newsletter-editor/sidebar/index.js
src/newsletter-editor/styling/index.js
src/newsletter-editor/styling/style.scss

Release May 13

---

CHANGELOG.md
newspack-newsletters.php
package-lock.json
package.json

Alpha release May 18

---

.distignore
includes/class-newspack-newsletters-editor.php
includes/class-newspack-newsletters.php
src/editor/blocks/index.js
src/editor/blocks/posts-inserter/block.json
src/editor/blocks/posts-inserter/index.js
src/editor/blocks/posts-inserter/style.scss
webpack.config.js

Alpha release Jun 08

---

CHANGELOG.md
includes/class-newspack-newsletters.php
newspack-newsletters.php
package-lock.json
package.json

Alpha release Jun 15

---

CHANGELOG.md
includes/class-newspack-newsletters.php
newspack-newsletters.php
package-lock.json
package.json

Release Jun 15

---

CHANGELOG.md
includes/class-newspack-newsletters-editor.php
newspack-newsletters.php
package-lock.json
package.json

Alpha release Jul 13

---

CHANGELOG.md
includes/class-newspack-newsletters-editor.php
includes/class-newspack-newsletters-settings.php
includes/class-newspack-newsletters.php
newspack-newsletters.php
package-lock.json
package.json
src/components/copy-html/index.js
src/components/copy-html/style.scss
src/components/init-modal/screens/api-keys/index.js
src/components/send-button/index.js
src/components/send-button/style.scss
src/newsletter-editor/editor/index.js
src/newsletter-editor/index.js
src/newsletter-editor/sidebar/index.js
src/service-providers/constant_contact/ProviderSidebar.js
src/service-providers/example/index.js
src/service-providers/index.js
src/service-providers/mailchimp/ProviderSidebar.js
src/service-providers/manual/index.js

Release Jul 13

---

CHANGELOG.md
includes/class-newspack-newsletters-editor.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
newspack-newsletters.php
package-lock.json
package.json
src/editor/blocks/posts-inserter/query-controls.js

Alpha release Jul 19

---

CHANGELOG.md
includes/class-newspack-newsletters-editor.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
newspack-newsletters.php
package-lock.json
package.json
src/editor/blocks/posts-inserter/query-controls.js

Release Jul 19

---

readme.txt

Closes #513. This PR bumps the tested version to the latest version of WP, because it's been tested up to the latest version of WP. Currently there's a big warning at the top of our .org listing about this not being tested with the latest 3 versions of WP: https://wordpress.org/plugins/newspack-newsletters/
n/a, just needs rubber stamp

Update tested WP version

---

.circleci/config.yml
CHANGELOG.md
includes/class-newspack-newsletters-editor.php
includes/class-newspack-newsletters-renderer.php
includes/class-newspack-newsletters.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
newspack-newsletters.php
package-lock.json
package.json
src/components/with-api-handler/index.js
src/editor/blocks/share/consts.js
src/editor/blocks/share/edit.js
src/editor/blocks/share/index.js
src/editor/blocks/share/save.js
src/editor/blocks/share/style.scss
src/editor/index.js

Alpha release Jul 27

---

.circleci/config.yml
CHANGELOG.md
includes/class-newspack-newsletters-editor.php
includes/class-newspack-newsletters-renderer.php
includes/class-newspack-newsletters.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
newspack-newsletters.php
package-lock.json
package.json
src/components/with-api-handler/index.js
src/editor/blocks/share/consts.js
src/editor/blocks/share/edit.js
src/editor/blocks/share/index.js
src/editor/blocks/share/save.js
src/editor/blocks/share/style.scss
src/editor/index.js

Release Jul 27

---

CHANGELOG.md
composer.json
composer.lock
includes/class-newspack-newsletters-settings.php
includes/class-newspack-newsletters.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact-controller.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact-sdk.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
newspack-newsletters.php
package-lock.json
package.json
src/components/init-modal/screens/api-keys/index.js
src/newsletter-editor/index.js
src/newsletter-editor/sidebar/index.js
src/newsletter-editor/testing/index.js
src/service-providers/constant_contact/ProviderSidebar.js
src/service-providers/constant_contact/index.js
src/service-providers/example/index.js

Alpha release Jul 29

---

CHANGELOG.md
composer.json
composer.lock
includes/class-newspack-newsletters-settings.php
includes/class-newspack-newsletters.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact-controller.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact-sdk.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
newspack-newsletters.php
package-lock.json
package.json
src/components/init-modal/screens/api-keys/index.js
src/newsletter-editor/index.js
src/newsletter-editor/sidebar/index.js
src/newsletter-editor/testing/index.js
src/service-providers/constant_contact/ProviderSidebar.js
src/service-providers/constant_contact/index.js
src/service-providers/example/index.js

Release Jul 29

---

CHANGELOG.md
newspack-newsletters.php
package-lock.json
package.json
readme.txt
src/editor/blocks/posts-inserter/block.json
src/editor/blocks/posts-inserter/index.js
src/editor/blocks/posts-inserter/utils.js

Alpha release Aug 03

---

CHANGELOG.md
newspack-newsletters.php
package-lock.json
package.json
readme.txt
src/editor/blocks/posts-inserter/block.json
src/editor/blocks/posts-inserter/index.js
src/editor/blocks/posts-inserter/utils.js

Release Aug 03

---

includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php

The current method for test emails depends on a synchronization performed elsewhere (currently through post save action). This approach allows sending outdated content due to silently failed synchronization.
On the other hand, although the "send" method verifies synchronization before continuing, it doesn't fail properly on error, allowing failed submission to be marked as published.
This PR reduces the possibility of synchronization issues with Mailchimp by ensuring the test emails are synchronized and publishing sync errors fail properly by modifying its status back to "draft" and displaying error notices.
1. On the master branch, create and configure a new newsletter with a properly configured Mailchimp account
2. Click on Send and wait for the confirmation modal to appear (do not …

fix: ensure sync on test email and handle failed publishing

---

.circleci/config.yml

Fixes a CI issue.
See that the CI job is passing. To reproduce the error, run the CI job locally with [`circleci`](https://circleci.com/docs/2.0/local-cli/): `$ circleci local execute --job test-php`

ci: fix test-php job

---

.circleci/config.yml
CHANGELOG.md
includes/class-newspack-newsletters-layouts.php
includes/class-newspack-newsletters.php
newspack-newsletters.php
package-lock.json
package.json
src/components/newsletter-preview/index.js
src/newsletter-editor/layout/index.js
src/newsletter-editor/styling/index.js

Alpha release Aug 17

---

.circleci/config.yml
composer.json
composer.lock
config/php-scoper/guzzlehttp.inc.php
config/php-scoper/psr.inc.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact-sdk.php
phpcs.xml
vendor_prefixed/.gitignore

Implements [`php-scoper`](https://github.com/humbug/php-scoper) to add a custom prefix to Guzzle namespace.
Closes #539.
1. In the master branch, install the plugin [Constant Contact Forms](https://wordpress.org/plugins/constant-contact-forms/) (it uses an older version of Guzzle that causes conflict)
2. With Constant Contact provider configured, attempt to create a new newsletter
3. Observe the fatal error
4. Switch to this branch, run `composer install` and confirm newsletter create/edit/publish works
5. Also confirm that the release build works:
1. Clear the `vendor/` and `vendor_prefixed/` directories (**do not remove the `vendor_prefixed/` entirely, leave it empty instead**)
2. Run `composer install --no-dev --no-scripts && composer dump-autoload && npm run release:archive`
3. …

fix: custom namespace for Guzzle

---

.circleci/config.yml
CHANGELOG.md
composer.json
composer.lock
config/php-scoper/guzzlehttp.inc.php
config/php-scoper/psr.inc.php
includes/class-newspack-newsletters-layouts.php
includes/class-newspack-newsletters.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact-sdk.php
newspack-newsletters.php
package-lock.json
package.json
phpcs.xml
src/components/newsletter-preview/index.js
src/newsletter-editor/layout/index.js
src/newsletter-editor/styling/index.js
vendor_prefixed/.gitignore

Release Aug 17

---

CHANGELOG.md
includes/class-newspack-newsletters.php
includes/service-providers/campaign_monitor/class-newspack-newsletters-campaign-monitor.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
includes/service-providers/interface-newspack-newsletters-esp-service.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
newspack-newsletters.php
package-lock.json
package.json
src/editor/blocks/posts-inserter/block.json
src/editor/blocks/posts-inserter/index.js
src/editor/blocks/posts-inserter/utils.js

Alpha release Aug 31

---

CHANGELOG.md
includes/class-newspack-newsletters.php
includes/service-providers/campaign_monitor/class-newspack-newsletters-campaign-monitor.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
includes/service-providers/interface-newspack-newsletters-esp-service.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
newspack-newsletters.php
package-lock.json
package.json
src/editor/blocks/posts-inserter/block.json
src/editor/blocks/posts-inserter/index.js
src/editor/blocks/posts-inserter/utils.js

Release Aug 31

---

CHANGELOG.md
includes/class-newspack-newsletters.php
newspack-newsletters.php
package-lock.json
package.json

Alpha release Sep 14

---

CHANGELOG.md
includes/class-newspack-newsletters.php
newspack-newsletters.php
package-lock.json
package.json

Release Sep 14

---

.circleci/config.yml
CHANGELOG.md
includes/class-newspack-newsletters-editor.php
includes/class-newspack-newsletters.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
newspack-newsletters.php
package-lock.json
package.json
src/service-providers/mailchimp/ProviderSidebar.js

Alpha release Nov 01

---

.circleci/config.yml

Update packages before using `apt install`.
CI tasks must pass.

chore(ci): ensure packages are updated before installing

---

.circleci/config.yml
CHANGELOG.md
includes/class-newspack-newsletters-editor.php
includes/class-newspack-newsletters.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
newspack-newsletters.php
package-lock.json
package.json
src/service-providers/mailchimp/ProviderSidebar.js

Release Nov 02

---

includes/class-newspack-newsletters-editor.php

Allows plugins to add allowed hooks in the email editor. For https://github.com/Automattic/newspack-plugin/pull/1187
_See https://github.com/Automattic/newspack-plugin/pull/1187_

feat: allow custom hooks in the email editor

---

.circleci/config.yml
CHANGELOG.md
includes/class-newspack-newsletters-editor.php
includes/class-newspack-newsletters-settings.php
includes/class-newspack-newsletters.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
newspack-newsletters.php
package-lock.json
package.json

Alpha release Nov 16

---

.circleci/config.yml
CHANGELOG.md
includes/class-newspack-newsletters-editor.php
includes/class-newspack-newsletters-settings.php
includes/class-newspack-newsletters.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
newspack-newsletters.php
package-lock.json
package.json

Release Nov 18

---

CHANGELOG.md
README.md
composer.lock
includes/class-newspack-newsletters-renderer.php
includes/class-newspack-newsletters-settings.php
includes/class-newspack-newsletters.php
includes/service-providers/letterhead/class-newspack-newsletters-letterhead.php
includes/service-providers/letterhead/dtos/class-newspack-newsletters-letterhead-promotion-dto.php
includes/service-providers/letterhead/models/class-newspack-newsletters-letterhead-promotion.php
newspack-newsletters.php
package-lock.json
package.json
src/components/send-button/index.js

Alpha release Dec 09

---

CHANGELOG.md
README.md
composer.lock
includes/class-newspack-newsletters-renderer.php
includes/class-newspack-newsletters-settings.php
includes/class-newspack-newsletters.php
includes/service-providers/letterhead/class-newspack-newsletters-letterhead.php
includes/service-providers/letterhead/dtos/class-newspack-newsletters-letterhead-promotion-dto.php
includes/service-providers/letterhead/models/class-newspack-newsletters-letterhead-promotion.php
newspack-newsletters.php
package-lock.json
package.json
src/components/send-button/index.js

Release Dec 14

---

CHANGELOG.md
composer.lock
includes/class-newspack-newsletters-editor.php
includes/class-newspack-newsletters-renderer.php
includes/email-template-mjml.css
newspack-newsletters.php
package-lock.json
package.json
src/editor/style.scss
src/newsletter-editor/index.js
src/newsletter-editor/styling/index.js
src/newsletter-editor/styling/style.scss
src/service-providers/index.js
tests/test-renderer.php

Alpha release Dec 16

---

src/newsletter-editor/public/index.js
src/newsletter-editor/public/style.scss
src/newsletter-editor/sidebar/index.js
src/newsletter-editor/sidebar/style.scss
src/service-providers/campaign_monitor/ProviderSidebar.js
src/service-providers/constant_contact/ProviderSidebar.js
src/service-providers/example/index.js
src/service-providers/mailchimp/ProviderSidebar.js
src/service-providers/manual/index.js
src/service-providers/manual/style.scss

Add "Subject", "From", "Send to" sections to the sidebar so it's better organised
_E.g. Mailchimp_
2. Edit/Create a Newsletter
3. Test with various providers

Reorganise sidebar

---

CHANGELOG.md
composer.lock
includes/class-newspack-newsletters-editor.php
includes/class-newspack-newsletters-renderer.php
includes/email-template-mjml.css
newspack-newsletters.php
package-lock.json
package.json
src/editor/style.scss
src/newsletter-editor/index.js
src/newsletter-editor/styling/index.js
src/newsletter-editor/styling/style.scss
src/service-providers/index.js
tests/test-renderer.php

Release Jan 04

---

includes/class-newspack-newsletters-renderer.php
src/editor/blocks/posts-inserter/index.js
src/editor/blocks/posts-inserter/posts-preview.js

Alpha release Jan 18

---

src/editor/blocks/mailchimp-merge-tags/index.js
src/editor/blocks/mailchimp-merge-tags/style.scss

Tiny PR that slightly adjusts the style of the merge tags dropdown
1. In a newsletter, try adding a merge tag
3. Refresh editor and try adding a merge tag again

Update merge tags style

---

includes/class-newspack-newsletters-editor.php
includes/class-newspack-newsletters-renderer.php
includes/email-template-mjml.css
src/editor/style.scss

Slight adjustment to the typography in order to match 1:1 editor/email
1. Create new newsletter
2. Add various paragraphs, headings, quote
3. Play with style, sizes
4. Send a test
5. Switch to this branch
6. Send a new test and compare the result

Fix font size vertical rhythm and fix quote and paragraph

---

includes/class-newspack-newsletters-renderer.php

Implement MJML rendering of block padding.
Closes #649.
| Gutenberg | Rendered Markup |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/820752/152415561-f3871e86-0937-44b3-b79f-2ea8c897d229.png) | ![image](https://user-images.githubusercontent.com/820752/152415728-1489701d-8aaa-4692-b742-0961a4cceb5d.png) |
1. Checkout this branch and create a blank newsletter
2. Add a group block with a custom background and padding
3. Send the newsletter and confirm the applied styles
4. Send a newsletter using the "Daily/Weekly" template and confirm there's no regression

feat: support block padding

---

CHANGELOG.md
includes/class-newspack-newsletters-editor.php
includes/class-newspack-newsletters-renderer.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
newspack-newsletters.php
package-lock.json
package.json
src/newsletter-editor/editor/index.js
src/newsletter-editor/editor/style.scss
src/newsletter-editor/sidebar/index.js
src/service-providers/campaign_monitor/ProviderSidebar.js
src/service-providers/constant_contact/ProviderSidebar.js
src/service-providers/example/index.js
src/service-providers/mailchimp/ProviderSidebar.js
src/service-providers/manual/index.js

Release Mar 08

---

includes/class-newspack-newsletters-editor.php
includes/class-newspack-newsletters-renderer.php
includes/email-template.mjml.php

Implements hooks to allow theme customization to newsletter styles.
Test instructions at https://github.com/Automattic/newspack-theme/pull/1730

feat: allow theme customization

---

.circleci/config.yml
CHANGELOG.md
includes/class-newspack-newsletters-editor.php
includes/class-newspack-newsletters-renderer.php
includes/email-template.mjml.php
newspack-newsletters.php
package-lock.json
package.json

Release Mar 22

---

includes/class-newspack-newsletters-editor.php
includes/class-newspack-newsletters-renderer.php
includes/email-template.mjml.php
package-lock.json
package.json
src/components/with-api-handler/index.js
src/editor/api/index.js
src/editor/index.js
src/newsletter-editor/editor/index.js
src/newsletter-editor/editor/style.scss
src/newsletter-editor/sidebar/index.js
src/service-providers/campaign_monitor/ProviderSidebar.js
src/service-providers/constant_contact/ProviderSidebar.js
src/service-providers/example/index.js
src/service-providers/mailchimp/ProviderSidebar.js
src/service-providers/manual/index.js

Alpha release Mar 31

---

CHANGELOG.md
includes/class-newspack-newsletters-editor.php
includes/class-newspack-newsletters-renderer.php
includes/email-template.mjml.php
newspack-newsletters.php
package-lock.json
package.json
src/components/with-api-handler/index.js
src/editor/api/index.js
src/editor/index.js
src/newsletter-editor/editor/index.js
src/newsletter-editor/editor/style.scss
src/newsletter-editor/sidebar/index.js
src/service-providers/campaign_monitor/ProviderSidebar.js
src/service-providers/constant_contact/ProviderSidebar.js
src/service-providers/example/index.js
src/service-providers/mailchimp/ProviderSidebar.js
src/service-providers/manual/index.js

Release Apr 05

---

includes/class-newspack-newsletters-settings.php
includes/class-newspack-newsletters.php
includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign-controller.php
includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
newspack-newsletters.php
src/components/init-modal/screens/api-keys/index.js
src/service-providers/active_campaign/ProviderSidebar.js
src/service-providers/active_campaign/index.js
src/service-providers/active_campaign/style.scss
src/service-providers/index.js

Alpha release Apr 08

---

src/editor/api/index.js

Closes #607
1. On `master`, create a new newsletter, start with a blank
2. Insert some content and save it as a new layout via the "Layout" sidebar panel
3. Create a new newsletter, choose the new layout as the layout
4. Make some changes to the content, try to update the layout – observe that the layout is not updated (not in the sidebar, not in the new-newsletter layout-choosing modal)
5. Switch to this branch, observe the layouts can be updated
6. Observe that a new layout can be created

fix(layouts): updating layouts

---

includes/class-newspack-newsletters-editor.php

Alpha release May 20

---

src/components/init-modal/screens/layout-picker/index.js
src/components/init-modal/style.scss

This PR simplifies the style of the sidebar, mainly the buttons.
* Instead of having a custom class, we're using `primary` or `tertiary`
* Added a light grey background colour to differentiate it from the header (and it's primary and secondary buttons)
* Tweaked the small screen min-width
* Reduced the width of the sidebar to 280px in order to match the Editor's sidebar.
__After__
__Before__
1. Add a new newsletter -- stay on the modal
3. Refresh screen

Update init modal sidebar design

---

package-lock.json
package.json

This reverts commit c65e8a05f9ac2655963bf5ee6d15bc7736339f94, which appears to be breaking the master branch.

Revert "chore(deps): bump commitlint from 16.2.4 to 17.0.2"

---

.circleci/config.yml
includes/class-newspack-newsletters-renderer.php
includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
includes/service-providers/campaign_monitor/class-newspack-newsletters-campaign-monitor.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
includes/service-providers/interface-newspack-newsletters-esp-service.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
package-lock.json
package.json

Alpha release Jun 16

---

CHANGELOG.md
includes/class-newspack-newsletters-renderer.php
includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
includes/service-providers/campaign_monitor/class-newspack-newsletters-campaign-monitor.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
includes/service-providers/interface-newspack-newsletters-esp-service.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
newspack-newsletters.php
package-lock.json
package.json

Release Jun 27

---

includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php

The same as #885 but rebased to alpha

fix(activecampaign): paginate through segments (alpha)

---

CHANGELOG.md
includes/class-newspack-newsletters.php
includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign-controller.php
includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
newspack-newsletters.php
package-lock.json
package.json
src/service-providers/active_campaign/ProviderSidebar.js
src/service-providers/active_campaign/index.js

Release Jul 11

---

includes/class-newspack-newsletters-blocks.php
includes/class-newspack-newsletters-editor.php
includes/class-newspack-newsletters-settings.php
includes/class-newspack-newsletters-subscription.php
includes/class-newspack-newsletters.php
includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
includes/service-providers/campaign_monitor/class-newspack-newsletters-campaign-monitor.php
includes/service-providers/interface-newspack-newsletters-esp-service.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
newspack-newsletters.php
package-lock.json
package.json
src/blocks/index.js
src/blocks/subscribe/block.json
src/blocks/subscribe/edit.js
src/blocks/subscribe/editor.scss
src/blocks/subscribe/index.js
src/blocks/subscribe/index.php
src/blocks/subscribe/style.scss
src/blocks/subscribe/view.js
webpack.config.js

Alpha release Jul 14

---

CHANGELOG.md
includes/class-newspack-newsletters-blocks.php
includes/class-newspack-newsletters-editor.php
includes/class-newspack-newsletters-settings.php
includes/class-newspack-newsletters-subscription.php
includes/class-newspack-newsletters.php
includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
includes/service-providers/campaign_monitor/class-newspack-newsletters-campaign-monitor.php
includes/service-providers/interface-newspack-newsletters-esp-service.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
newspack-newsletters.php
package-lock.json
package.json
src/blocks/index.js
src/blocks/subscribe/block.json
src/blocks/subscribe/edit.js
src/blocks/subscribe/editor.scss
src/blocks/subscribe/index.js
src/blocks/subscribe/index.php
src/blocks/subscribe/style.scss
src/blocks/subscribe/view.js
webpack.config.js

Release Jul 25

---

includes/class-newspack-newsletters-logger.php
includes/class-newspack-newsletters-subscription.php
newspack-newsletters.php

Adds logging when a contact is added or updated.
1. Switch Newspack Plugin to `feat/logger-tweaks` branch (https://github.com/Automattic/newspack-plugin/pull/1807)
1. Set env. variable `NEWSPACK_LOG_LEVEL` to `2`
2. Trigger a contact add (e.g. via the new signup block)
3. Observe an event logged in the debug log (`wp-content/debug.log` if `WP_DEBUG_LOG` is `true`)

chore: logging

---

includes/class-newspack-newsletters-subscription.php
includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php

Enables full contact data fetching when requesting contact data.
_Follow instructions in https://github.com/Automattic/newspack-popups/pull/927_

feat: full contact data fetching

---

src/blocks/subscribe/index.php

Fixes a small issue.
_Follow instructions in https://github.com/Automattic/newspack-plugin/pull/1819_

fix(subscribe-block): empty lists config handling

---

includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php

Define more fields as date fields.

feat(active-campaign): more date fields

---

includes/class-newspack-newsletters-subscription.php

Updates wording in My Account -> Newsletters.

feat: copy tweak

---

.prettierrc
includes/class-newspack-newsletters-logger.php
includes/class-newspack-newsletters-subscription.php
includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
includes/service-providers/campaign_monitor/class-newspack-newsletters-campaign-monitor.php
includes/service-providers/class-newspack-newsletters-service-provider.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
includes/service-providers/interface-newspack-newsletters-esp-service.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
newspack-newsletters.php
package-lock.json
package.json
src/blocks/subscribe/editor.scss
src/blocks/subscribe/index.php
src/components/init-modal/style.scss
src/editor/blocks/mailchimp-merge-tags/style.scss
src/editor/blocks/posts-inserter/index.js
src/editor/blocks/posts-inserter/style.scss
src/editor/blocks/visibility-attribute/style.scss
src/editor/style.scss
src/newsletter-editor/editor/index.js
src/newsletter-editor/layout/style.scss
src/newsletter-editor/sidebar/style.scss
src/newsletter-editor/styling/style.scss
src/subscriptions/index.js
src/subscriptions/style.scss
webpack.config.js

Alpha release Aug 05

---

includes/class-newspack-newsletters-subscription.php

Details and instructions at https://github.com/Automattic/newspack-plugin/pull/1873

fix(subscriptions): verify email on reader verification

---

includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php

Implementing RAS increased by a lot the number of requests made to retrieve and update contact data. This PR implements some optimizations to reduce the load time on account registration.
1. With RAS, register with SSO and regular email
2. Select all lists from the registration block
3. Make sure there are no errors
4. Visit AC dashboard and confirm the metadata is stored

feat(ActiveCampaign): optimize and reduce API requests

---

includes/class-newspack-newsletters-subscription.php
includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
package-lock.json
package.json

Alpha release Aug 12

---

includes/class-newspack-newsletters-subscription.php
includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
package-lock.json
package.json
src/blocks/subscribe/index.php
src/blocks/subscribe/style.scss
src/blocks/subscribe/view.js

Alpha release Aug 26

---

includes/class-newspack-newsletters-subscription.php

Updates an external class name after changes in https://github.com/Automattic/newspack-plugin/pull/1937

feat: handle updated from & name settings from Newspack plugin

---

includes/class-newspack-newsletters-renderer.php

Make sure the processed link has a valid URL before appending the `utm_medium` parameter to it.
Closes https://github.com/Automattic/newspack-plugin/issues/1952
1. On master, save the RAS' Verification Email
2. Register as a new reader and confirm the "Verification link" doesn't work
3. Check out this branch, save the RAS' Verification Email again (so it re-renders the HTML)
4. Register as a new reader and confirm the "Verification link" now works

fix: only process links with valid url

---

includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php

When ActiveCampaign fails to send the test campaign the editor is showing a success message. This PR fixes it:
It also ensures the deletion of lingering test campaigns when trashing a campaign.
As of this writing, our sandbox account is not able to send a campaign directly through the API due to ActiveCampaign's internal spam control.
1. With ActiveCampaign setup, try to send a test campaign with our sandbox account
2. Confirm you receive the error message as attached above
3. Confirm the test campaign is created on AC's dashboard
4. Trash the draft campaign and confirm the test campaign is deleted on AC's dashboard

fix(ActiveCampaign): handle error on test campaign

---

includes/class-newspack-newsletters-renderer.php
includes/class-newspack-newsletters-subscription.php
includes/class-newspack-newsletters.php
includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
package-lock.json
package.json
src/blocks/subscribe/index.php

Alpha release Sep 06

---

includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
src/blocks/subscribe/style.scss

Alpha release Sep 07

---

composer.json
composer.lock
includes/class-newspack-newsletters-subscription.php
includes/service-providers/campaign_monitor/class-newspack-newsletters-campaign-monitor.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
includes/service-providers/interface-newspack-newsletters-esp-service.php
includes/service-providers/letterhead/class-newspack-newsletters-letterhead.php
package-lock.json
package.json
phpunit.xml.dist
tests/bootstrap.php

Alpha release Sep 16

---

src/blocks/subscribe/style.scss

Fixes a styling issue.
1. On `master`, insert a Newsletter Subscription block
2. Observe that the color of the text is black, which results in a poor contrast
3. Switch to this branch, observe the text color is white

feat(subscribe-block): button text color

---

includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact-sdk.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
package-lock.json
package.json
src/blocks/subscribe/style.scss
src/editor/blocks/posts-inserter/block.json
src/editor/blocks/posts-inserter/index.js
src/editor/blocks/posts-inserter/query-controls.js

Alpha release Sep 21

---

includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php

Ensures all contact metadata fields are fetched when getting all contact data. By default, the API returns 20 items, so when there are more metadata fields, they would not have been fetched. 
Closes https://github.com/Automattic/newspack-plugin/issues/1995, which was caused by not all fields being fetched. This caused the plugin to [treat the contact as a new contact](https://github.com/Automattic/newspack-plugin/blob/cfabb5a7a90848c209c40b35749504f2feaded4c/includes/plugins/class-newspack-newsletters.php#L131-L134) and override the metadata field.
1. On `master`
1. Set up Active Campaign as the ESP
2. Ensure there are more than 20 metadata fields 
3. Fetch a contact which has > 20 fields filled (execute `Newspack_Newsletters_Active_Campaign::get_contact_data( 't-5D33406C@mail.com', true …

fix(active-campaign): ensure all metadata fields are handled

---

includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php

Alpha release Sep 26

---

CHANGELOG.md
composer.json
composer.lock
includes/class-newspack-newsletters-subscription.php
includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
includes/service-providers/campaign_monitor/class-newspack-newsletters-campaign-monitor.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact-sdk.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
includes/service-providers/interface-newspack-newsletters-esp-service.php
includes/service-providers/letterhead/class-newspack-newsletters-letterhead.php
newspack-newsletters.php
package-lock.json
package.json
phpunit.xml.dist
src/blocks/subscribe/style.scss
src/editor/blocks/posts-inserter/block.json
src/editor/blocks/posts-inserter/index.js
src/editor/blocks/posts-inserter/query-controls.js
tests/bootstrap.php

Release Sep 27

---

package-lock.json
package.json
src/blocks/subscribe/block.json
src/blocks/subscribe/edit.js
src/blocks/subscribe/editor.scss
src/blocks/subscribe/index.php
src/blocks/subscribe/style.scss

Alpha release Oct 21

---

composer.lock
includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign-controller.php
includes/service-providers/campaign_monitor/class-newspack-newsletters-campaign-monitor-controller.php
includes/service-providers/class-newspack-newsletters-service-provider-controller.php
includes/service-providers/class-newspack-newsletters-service-provider.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact-controller.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact-sdk.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp-controller.php

Alpha release Oct 24

---

CHANGELOG.md
composer.lock
includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign-controller.php
includes/service-providers/campaign_monitor/class-newspack-newsletters-campaign-monitor-controller.php
includes/service-providers/class-newspack-newsletters-service-provider-controller.php
includes/service-providers/class-newspack-newsletters-service-provider.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact-controller.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact-sdk.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp-controller.php
newspack-newsletters.php
package-lock.json
package.json
src/blocks/subscribe/block.json
src/blocks/subscribe/edit.js
src/blocks/subscribe/editor.scss
src/blocks/subscribe/index.php
src/blocks/subscribe/style.scss

Release Oct 31

---

includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php

Constant Contact may not always return the access token on request. The result may also not be a valid JSON as requested. This PR ensures that unexpected responses from the provider don't cause fatal errors.
1. On a JN that is failing to connect, confirm the fatal error (ping me for JN)
2. Deploy this branch and confirm the unexpected result is handled
3. Deploy this branch on a non-failing instance and confirm the connection still works

fix(constant-contact): validate access token fetch response

---

package-lock.json
package.json

Same as https://github.com/Automattic/newspack-plugin/pull/2109.
Updates `newspack-script` to a version which handles the weird `HookWebpackError: error:0308010C:digital envelope routines::unsupported` error, [as seen here](https://app.circleci.com/pipelines/github/Automattic/newspack-plugin/5484/workflows/41c1fbe0-f1ff-4bff-9949-97e45aaa10dd/jobs/25721/parallel-runs/0/steps/0-105).
The real test will be whether the CI job ran on `master` (after this is merged) build the JS files successfully. In the meantime, here's how it can be approximated:
1. Visit [CI for this branch](https://app.circleci.com/pipelines/github/Automattic/newspack-plugin?branch=fix%2Fci-build)
2. Go to the latest `all` workflow and select `build` step
3. Rerun the step with SSH
4. Ensure the step runs to completion, …

fix(ci): update newspack-scripts to fix CI builds

---

.circleci/config.yml

Updates the CI orb to the latest version.

chore: update CircleCI orb

---

.circleci/config.yml
package-lock.json
package.json

merge master into epic/tags-support

---

composer.json
includes/class-newspack-newsletters.php
includes/class-subscription-lists.php
newspack-newsletters.php

Creates a CPT to manage Subscription Lists
1. Check the code
2. Verify the Lists menu added under Newsletters
3. Try adding/editing Lists
4. Verify the content only shows a simple textarea

feat: bootstrapping lists CPT

---

.circleci/config.yml
CHANGELOG.md
includes/class-newspack-newsletters-subscription.php
includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
newspack-newsletters.php
package-lock.json
package.json

Alpha release Nov 17

---

CHANGELOG.md
includes/class-newspack-newsletters-subscription.php
newspack-newsletters.php
package-lock.json
package.json

Merge master

---

includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php

Refactors the handling of field upsertion on contact creation in order to fix #1034 
1. Check out this branch
2. Open your site shell with `wp shell`
3. Set a contact with metadata: `$contact  = ['email' => 'test@test.com', 'metadata' => [ 'My Test Field' => 'My Test Value' ] ];`
4. Set your list id: `$list_id = {your list id};`
5. Instantiate the provider: `$provider = new Newspack_Newsletters_Active_Campaign();`
6. Create the contact with the metadata: `$provider->add_contact( $contact, $list_id );`
7. Visit the contact's dashboard page and confirm the field is available and with the value set

fix(ActiveCampaign): update fields API version

---

CHANGELOG.md
includes/class-newspack-newsletters-renderer.php
includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
newspack-newsletters.php
package-lock.json
package.json
src/editor/blocks/posts-inserter/block.json

Alpha release Dec 01

---

includes/service-providers/class-newspack-newsletters-service-provider.php

The relationship between the `is_public` meta and `post_status` should also make sure the post status is correct if the value is updated from `update_post_meta()`, which is the case when updating in bulk.
Closes #1015
1. While on the master branch, send a newsletter with `Public` toggled off
2. Confirm the newsletter is "Private"
3. Visit the Newsletters table page
4. Select the newsletter and select the bulk action to "Make newsletter page public" 
5. Attempt to access the newsletter URL in incognito and confirm you still get 404
6. Select the newsletter and select the bulk action to "**Make newsletter page non-public**"
7. Switch to this branch
8. Repeat steps 3-5 and confirm the page renders as expected

fix: handle post status on "public" meta update

---

includes/class-newspack-newsletters-subscription.php
includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
includes/service-providers/class-newspack-newsletters-service-provider.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php

This PR add complete support to tag based Lists on the My Account page
1. Set your ESP as Mailchimp
2. Create a couple of Local lists in Newsletter > Lists
3. Register as a new user to your site
4. Subscribe to a newsletter
5. Go to My Account > Newsletters
6. Confirm that the page correctly shows the newsletters you have subscribed to
7. Check and uncheck different newsletters and save
8. Confirm that everytime the correct tags are applied to the contact on Mailchimp and the checkboxes are properly updated
9. In the admin (as an admin) switch the ESP to Active Campaign
10. Back to your reader user, go to My Account > Newsletters again
11. All newsletters should be unchecked
12. This user does not exist in the ESP yet, let's see if it will be created on the fly
13. Check one or several …

Tags support my account

---

CHANGELOG.md
includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
newspack-newsletters.php
package-lock.json
package.json
src/editor/blocks/posts-inserter/block.json

Release Dec 12

---

CHANGELOG.md
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact-controller.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact-sdk.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
newspack-newsletters.php
package-lock.json
package.json
src/service-providers/constant_contact/ProviderSidebar.js
src/service-providers/constant_contact/style.scss

Release Jan 24

---

includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php

Supports changes in https://github.com/Automattic/newspack-plugin/pull/2249.
Follow instructions in https://github.com/Automattic/newspack-plugin/pull/2249.

feat(ras): support custom contact metadata prefixes for RAS

---

composer.lock
includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp-cached-data.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp-controller.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
package-lock.json
package.json
src/editor/api/index.js
src/service-providers/mailchimp/ProviderSidebar.js

Alpha release Feb 16

---

CHANGELOG.md
includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp-cached-data.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
newspack-newsletters.php
package-lock.json
package.json

Release Feb 15

---

includes/class-newspack-newsletters-subscription.php

Adds a new `origin` metadata to all contacts added via the plugin so we can easily identify and filter them in the ESP data.
1. Register to the site via different entry points (register block, newsletter subscriptio, making a donation with RAS enabled)
2. Confirm that the contact is addedd to the ESP with a new `origin = newspack` metadata

feat: add origin metadata to all contacts

---

src/editor/api/index.js

Reverts a change in the editor (https://github.com/Automattic/newspack-newsletters/pull/1074) that added a but when using Mailchimp Dynamic content inside a Newsletter item
1. Check if the editor works well

fix: Revert changes in editor

---

composer.lock
includes/class-newspack-newsletters-renderer.php
includes/class-newspack-newsletters-settings.php
includes/class-newspack-newsletters-subscription.php
includes/class-subscription-lists.php
includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp-cached-data.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp-controller.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
package-lock.json
package.json
src/blocks/subscribe/editor.scss
src/components/init-modal/style.scss
src/editor/api/index.js
src/editor/style.scss
src/service-providers/mailchimp/ProviderSidebar.js

Alpha release Mar 02

---

includes/class-newspack-newsletters-subscription.php
src/blocks/subscribe/index.php

Adjust newsletter subscription hooks to include data need for the Data Events api. https://github.com/Automattic/newspack-plugin/pull/2330
See https://github.com/Automattic/newspack-plugin/pull/2330

feat: adjust data passed by subscription hooks

---

CHANGELOG.md
includes/class-newspack-newsletters-renderer.php
includes/class-newspack-newsletters-settings.php
includes/class-newspack-newsletters-subscription.php
includes/class-subscription-list.php
includes/class-subscription-lists.php
includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
includes/service-providers/class-newspack-newsletters-service-provider.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact-sdk.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
includes/service-providers/interface-newspack-newsletters-esp-service.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp-groups.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
newspack-newsletters.php
package-lock.json
package.json
src/blocks/subscribe/editor.scss
src/blocks/subscribe/index.php
src/components/init-modal/style.scss
src/editor/style.scss

Release Mar 13

---

src/blocks/subscribe/index.php

Changes the param passed by the hook.
Note that this param was recently introduced, and we know exactly the only place where it's used. And it's been updated by https://github.com/Automattic/newspack-plugin/pull/2337
See https://github.com/Automattic/newspack-plugin/pull/2337

feat: update hook param

---

package-lock.json
package.json
src/blocks/subscribe/index.php

Alpha release Mar 21

---

.circleci/config.yml
CHANGELOG.md
README.md
composer.lock
includes/class-newspack-newsletters-subscription.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
newspack-newsletters.php
package-lock.json
package.json
src/blocks/subscribe/index.php
src/components/with-api-handler/index.js

Release Mar 27

---

src/blocks/subscribe/view.js

fix(subscription-block): use domReady for initializing block js

---

.hooks/pre-push
composer.json
package.json

Prevents direct pushes to master.
1. Run composer install
2. Commit something to master
3. try to push and see the error message

fix: commit hook and add pre push

---

includes/class-newspack-newsletters-blocks.php
src/blocks/subscribe/edit.js

Same as https://github.com/Automattic/newspack-plugin/pull/2397 but for the Newsletters Subscription Form Block.

feat(subscription): add recaptcha panel in the editor

---

composer.lock
includes/class-newspack-newsletters-editor.php
package-lock.json
package.json
src/blocks/subscribe/block.json
src/blocks/subscribe/edit.js
src/blocks/subscribe/editor.scss
src/blocks/subscribe/index.php
src/blocks/subscribe/style.scss
src/blocks/subscribe/view.js
src/editor/style.scss

Alpha release Apr 28

---

CHANGELOG.md
composer.lock
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
newspack-newsletters.php
package-lock.json
package.json
src/blocks/subscribe/block.json
src/blocks/subscribe/edit.js
src/blocks/subscribe/editor.scss
src/blocks/subscribe/index.php
src/blocks/subscribe/style.scss
src/blocks/subscribe/view.js

Release May 08

---

composer.json
composer.lock
includes/class-newspack-newsletters-blocks.php
includes/class-newspack-newsletters-editor.php
includes/class-newspack-newsletters-renderer.php
includes/class-newspack-newsletters-subscription.php
includes/class-subscription-lists.php
includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
includes/service-providers/campaign_monitor/class-newspack-newsletters-campaign-monitor.php
includes/service-providers/class-newspack-newsletters-service-provider.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp-groups.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
package-lock.json
package.json
src/blocks/subscribe/block.json
src/blocks/subscribe/edit.js
src/blocks/subscribe/index.php
src/components/init-modal/style.scss
src/editor/blocks/conditional-content/index.js
src/editor/blocks/conditional-content/style.scss
src/editor/blocks/visibility-attribute/style.scss
src/editor/index.js
src/newsletter-editor/layout/style.scss
src/service-providers/campaign_monitor/ProviderSidebar.js
src/service-providers/mailchimp/ProviderSidebar.js

Alpha release May 11

---

CHANGELOG.md
composer.json
composer.lock
includes/class-newspack-newsletters-blocks.php
includes/class-newspack-newsletters-editor.php
includes/class-newspack-newsletters-renderer.php
includes/class-newspack-newsletters-subscription.php
includes/class-subscription-lists.php
includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
includes/service-providers/campaign_monitor/class-newspack-newsletters-campaign-monitor.php
includes/service-providers/class-newspack-newsletters-service-provider.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp-groups.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
newspack-newsletters.php
package-lock.json
package.json
src/blocks/subscribe/block.json
src/blocks/subscribe/edit.js
src/blocks/subscribe/index.php
src/components/init-modal/style.scss
src/editor/blocks/conditional-content/index.js
src/editor/blocks/conditional-content/style.scss
src/editor/index.js
src/newsletter-editor/layout/style.scss
src/service-providers/campaign_monitor/ProviderSidebar.js
src/service-providers/mailchimp/ProviderSidebar.js

Release May 23

---

composer.lock
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
package-lock.json
package.json

Alpha release May 25

---

newspack-newsletters.php

Adds `Author URI` and `License` to the plugin header.

Plugin header

---

CHANGELOG.md
includes/class-newspack-newsletters-editor.php
includes/class-newspack-newsletters-renderer.php
includes/class-newspack-newsletters-settings.php
includes/class-newspack-newsletters.php
newspack-newsletters.php
package-lock.json
package.json
src/blocks/subscribe/edit.js
src/blocks/subscribe/editor.scss
src/blocks/subscribe/index.php
src/blocks/subscribe/style.scss
src/blocks/subscribe/view.js
src/editor/style.scss

Release Jun 19

---

composer.lock
includes/class-newspack-newsletters.php
newspack-newsletters.php
package-lock.json
package.json
src/blocks/subscribe/edit.js
src/blocks/subscribe/editor.scss
src/blocks/subscribe/style.scss

Alpha release Jun 22

---

CHANGELOG.md
composer.lock
includes/class-newspack-newsletters.php
newspack-newsletters.php
package-lock.json
package.json
src/blocks/subscribe/edit.js
src/blocks/subscribe/editor.scss
src/blocks/subscribe/style.scss

Release Jul 03

---

composer.lock
package-lock.json
package.json
src/blocks/subscribe/editor.scss
src/blocks/subscribe/view.js

Alpha release Jul 20

---

CHANGELOG.md
composer.lock
newspack-newsletters.php
package-lock.json
package.json
src/blocks/subscribe/editor.scss
src/blocks/subscribe/view.js

Release Aug 07

---

composer.lock
package-lock.json
package.json
src/blocks/subscribe/index.php

Alpha release Aug 21

---

CHANGELOG.md
composer.lock
newspack-newsletters.php
package-lock.json
package.json
src/blocks/subscribe/index.php

Release Aug 24

---

includes/class-newspack-newsletters-renderer.php
package-lock.json
package.json

Alpha release Sep 12

---

src/editor/blocks/posts-inserter/query-controls.js

Alpha release Sep 13

---

CHANGELOG.md
includes/class-newspack-newsletters.php
includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
newspack-newsletters.php
package-lock.json
package.json
src/blocks/subscribe/block.json
src/blocks/subscribe/edit.js
src/blocks/subscribe/editor.scss
src/blocks/subscribe/index.php
src/components/init-modal/screens/layout-picker/index.js
src/components/send-button/index.js
src/editor/api/index.js
src/newsletter-editor/editor/index.js
src/newsletter-editor/index.js
src/newsletter-editor/layout/index.js
src/newsletter-editor/utils.js
src/service-providers/active_campaign/ProviderSidebar.js
src/service-providers/campaign_monitor/ProviderSidebar.js

Alpha release Sep 29

---

src/ads/newsletter-editor/disable-auto-ads.js

A tiniest of tweaks!
1. On `master`, create a new newsletter, configure it, and click "Send" to open the "Send your newsletter?" modal
2. Observe that there's a warning about improper use of `getBlocks` selector in the JS console
3. Switch to this branch, repeat, observe there's no warning

refactor: proper use of editor-related selectors

---

includes/class-newspack-newsletters.php
includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
src/newsletter-editor/sidebar/index.js
src/service-providers/active_campaign/ProviderSidebar.js
src/service-providers/active_campaign/index.js
src/service-providers/campaign_monitor/ProviderSidebar.js
src/service-providers/campaign_monitor/index.js
src/service-providers/constant_contact/index.js
src/service-providers/example/index.js
src/service-providers/mailchimp/index.js

#1287 and #1299 introduced changes that require fine-tuning before release:
- aa50408bb118b21372f914208e15fa483710cf31: fixes the schema for the new `newsletter_send_errors` meta
- d6b823e03461b3f85064ec78dd7dbed88cc2cfe2: removes the `getFetchDataConfig()` function, which had its use deprecated in #1287 
- 5d63e70c77e95629ecf77e127c91462b56ac5100: fixes the `newsletterData` handling for ActiveCampaign, which was not updating on editor changes, preventing the editor to detect whether the newsletter is valid to send ("Send" always greyed-out)
1. Configure your plugin to use an ActiveCampaign account
2. While on the master branch, draft a new newsletter and attempt to save the draft
3. Confirm you get an error
4. Manually apply the change from aa50408bb118b21372f914208e15fa483710cf31 (so …

fix: newsletterData and ActiveCampaign editor tweaks

---

README.md
newspack-newsletters.php
package-lock.json
package.json
readme.txt
src/blocks/subscribe/block.json
src/blocks/subscribe/edit.js
src/blocks/subscribe/index.php
src/branding/index.js
src/editor/style.scss
tests/test-renderer.php

Alpha release Oct 16

---

includes/tracking/class-pixel.php

feat(tracking): experimental pixel tracking through log files (#1317 hotfix)

---

includes/class-newspack-newsletters-editor.php
includes/email-template-mjml.css
includes/service-providers/class-newspack-newsletters-service-provider.php
includes/service-providers/interface-newspack-newsletters-esp-service.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp-groups.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp-usage-reports.php
includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
newspack-newsletters.php
package-lock.json
package.json
src/components/init-modal/screens/layout-picker/index.js
src/components/init-modal/style.scss
tests/test-usage-reports.php

Alpha release Nov 03

---

.editorconfig

feat: add editorconfig file

---

.gitignore
bin/install-wp-tests.sh
composer.json
composer.lock

Fixes tests when running locally.
1. Reinstall Composer packages, run PHP tests, confirm all are passing
2. Tests should also pass on CI

test: fix tests when running locally

---

composer.lock
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact-sdk.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact-usage-reports.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
newspack-newsletters.php
package-lock.json
package.json

Alpha release Dec 15

---

CHANGELOG.md
composer.lock
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact-sdk.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact-usage-reports.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
newspack-newsletters.php
package-lock.json
package.json

Release Jan 08

---

src/newsletter-editor/editor/index.js

Fixes an issue with post meta interaction.
1. On `master`, create a new newsletter and save a draft. Open the editor preferences (via the three-dot menu in the top-right corner of editor UI) and in the "Panels" section enable "Custom Fields"
2. Edit the newsletter and save draft – observe the edits are not saved in the meta field (`wp post meta get <post-id> newspack_email_html`)
3. Switch to this branch, reload the editor, observe a warning notice being displayed, with a button to open the editor preferences:
5. Open the preferences using the button in the notice and update them so that "Custom Fields" is off. 
6. Make a change, save the draft again, and observe that now the changes are reflected in the meta field. 
---
- To see the specific tasks where the Asana app for GitHub is being …

feat: display warning if custom fields meta box is visible

---

includes/class-newspack-newsletters-renderer.php
includes/class-newspack-newsletters-subscription.php
includes/plugins/class-woocommerce-memberships.php
includes/tracking/class-click.php
package-lock.json
package.json
src/newsletter-editor/editor/index.js

Alpha release Jan 11

---

includes/class-newspack-newsletters-ads.php
includes/class-newspack-newsletters-layouts.php
includes/class-newspack-newsletters-quick-edit.php
includes/class-newspack-newsletters-subscription.php
includes/class-newspack-newsletters.php
includes/class-subscription-list.php
includes/class-subscription-lists.php
includes/service-providers/class-newspack-newsletters-service-provider.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
package-lock.json
package.json

Alpha release Feb 01

---

includes/test-file.php

This is a test.
Closes # .
1.
2.
3.

feat: test feature for epic release flow raz

---

includes/test-file.php

Reverts Automattic/newspack-newsletters#1415

Revert "feat: test feature for epic release flow raz"

---

CHANGELOG.md
composer.lock
includes/class-newspack-newsletters-ads.php
includes/class-newspack-newsletters-layouts.php
includes/class-newspack-newsletters-quick-edit.php
includes/class-newspack-newsletters-subscription.php
includes/class-newspack-newsletters.php
includes/class-subscription-list.php
includes/class-subscription-lists.php
includes/service-providers/class-newspack-newsletters-service-provider.php
includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
newspack-newsletters.php
package-lock.json
package.json
src/components/send-button/index.js
src/components/send-button/style.scss

Release Feb 06
