Automattic/newspack-newsletters

- src/components/template-modal/index.js
Adds placeholder text to the template picker's preview pane. If the blank template is selected: "Blank template." If no template is selected: "Select a layout to preview." At present there is no way to have no template selected, but I left this state in just in case the logic changes.
Closes https://github.com/Automattic/newspack-newsletters/issues/35.
1. Create a new Newsletter.
2. Verify "Blank template." text in the preview pane.
3. Select Template 1, verify the text disappears and is replaced by a preview of the template.
> feat: placeholder text for no template or blank template

- README.md
- includes/class-newspack-newsletters-renderer.php
- includes/class-newspack-newsletters-settings.php
Moves MJML API credentials input location from environment to plugin settings.
Closes #16.
1. Set up plugin as outlined in the README
2. Remove MJML credentials from environment (wp-config.php, probably)
3. Create a newsletter with some content, preview in Mailchimp. Should work as expected.
> feat: move MJML creds to plugin settings

- includes/class-newspack-newsletters-renderer.php
At the default timeout of 5s MJML API requests seem to be timing out frequently when converting complex content. This PR increases the timeout to 45s and fixes an issue that caused PHP to fatal when there was a timeout.
Closes https://github.com/Automattic/newspack-newsletters/issues/37
1. On `master` insert Template 1, and save the post. If you're "lucky" this will cause a timeout which will cause this PHP fatal in the log:
```
PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in /srv/www/newspack-repos/newspack-newsletters/includes/class-newspack-newsletters-renderer.php:514
```
2. Switch to this branch and try saving numerous times. There should be no fatals and the content should be converted successfully.
> fix: increase mjml request timeout, handle errors

- includes/class-newspack-newsletters.php
- src/editor/editor/style.scss
- src/editor/sidebar/index.js
- src/editor/sidebar/style.scss
This PR resolves the title/subject confusion in the following way:
- Post title is hidden, via CSS
- Subject field added to sidebar, which is bound to post title.
- New newsletter titles are the current date.
Closes https://github.com/Automattic/newspack-newsletters/issues/19
1. Create a new newsletter.
2. Verify the title is hidden.
3. Verify there is a subject field in the sidebar, and it is set to the current date.
4. Change the subject field, save the post, verify the change persists.
5. Send a test email, or actual campaign, verify the subject of the email matches the subject field.
> Subject In Sidebar

- includes/class-newspack-newsletters.php
Synchronizes newsletter post content with Mailchimp immediately before publishing. This resolves an issue where changes made between the last save and the publish do not get conveyed to Mailchimp and the campaign that is sent is out of date.
Closes https://github.com/Automattic/newspack-newsletters/issues/33
1. On `master`, create a new Newsletter, then Save.
2. Make some changes, then without saving again, click Publish. 
3. Observe that the campaign that is sent does not include the changes.
4. Switch to this branch, repeast.
5. Observe the last minute changes are reflected in the campaign that is sent.
> fix: send content to mailchimp immediately before sending campaign

- .circleci/config.yml
- .gitignore
- package.json
Production code uses composer packages, so they should be included in the release zip.
1. Remove `vendor` folder
2. Run `composer install --no-dev --no-scripts`
3. Run `npm run release:archive`
1. Observe that a `release/newspack-newsletters.zip` files has been created
1. Add the plugin manually on a WP site
1. All should work as expected
> fix: include vendor in release package

- src/editor/blocks-validation/blocks-filters.js
- src/editor/pre-publish-slot/index.js
- src/editor/sidebar/index.js
- src/editor/sidebar/style.scss
- src/editor/utils.js
This PR wraps the pre-check error messages into a `Notice` component.
I've also reorganised the sidebar settings.
2. Try to publish without selecting a list and/or a sender name/email (you should see the error(s))
> feat: update pre-check with notice and reorganize sidebar

- includes/class-newspack-newsletters.php
Thumbnail size will automatically crop a logo to a square which is not ideal when most logos aren't 1:1.
Instead this PR uses the Medium size. If it's too large for a user, they can use the Image Dimensions settings.
__Before:__
__After:__
1. Update your site logo to something else other than a square or circle (you can test with this [cool Newspack logo](https://user-images.githubusercontent.com/177929/79442538-951f4100-7fd0-11ea-839f-47839077f72e.png))
2. Add a new Newsletter. Notice your logo is now cropped.
3. Switch to this branch.
4. Add another new Newsletter. This time your logo should be displayed properly.
> Change logo size to medium

- src/components/template-modal/style.scss
This PR fixes a few visual inconsistencies since Gutenberg 7.9
It adds a light background to the content of the modal and fixes the height of the layout thumbnails.
1. Make sure you have the latest version of Gutenberg
2. Add a new Newsletter and admire the bugs! 😱 
3. Switch to this branch
4. Try to add a new Newsletter... it should look better now 😅
> Fix modal content background and preview items since Gutenberg 7.9

- src/editor/index.js
Closes #45 
1. Create new newsletter 
2. Wait for a minute
3. Observe that the URL has changed (post has been saved), but the modal is still visible
1. Reload the page, the modal should still be visible as there is no content
1. Add some content, save draft, reload page – observe that the modal is not there anymore
> Prevent modal closing after autosave

- includes/class-newspack-newsletters.php
Adds support for multiple test emails.
Closes https://github.com/Automattic/newspack-newsletters/issues/57
1. Create a new Newsletter, and populate with a template.
2. In Sidebar click `Send Test`.
3. Observe the help text below the text input.
4. Input multiple email addresses, separated by commas.
5. Verify all emails receive the test email.
> Support Multiple Test Emails

- includes/class-newspack-newsletters.php
When a newsletter is trashed, the corresponding Mailchimp campaign will be deleted. The campaign deletion occurs when the newsletter is trashed, _not_ when permanently deleted. Campaigns that have already been sent will not be deleted in Mailchimp, only drafts. If a trashed newsletter is restored, a new Mailchimp campaign will be created with the post content.
@adekbadek note I had to unravel the `$update` logic we discussed so that a new campaign is always created if the post doesn't have a campaign id stored. Let me know if you think this is problematic.
Closes https://github.com/Automattic/newspack-newsletters/issues/29
1. Create a newsletter, populate with a template, save. Observe the corresponding campaign is created in Mailchimp.
2. Trash the newsletter in WordPress. Observe the …
> Delete Mailchimp Campaign After Post Is Trashed

- includes/class-newspack-newsletters.php
- src/admin/index.js
- webpack.config.js
Adds an info notification after installation instructing users to go to Settings to input API keys. The notification will appear on all admin pages except for those associated with Newsletters. If all three API keys are set the notification will not be shown. The notification can be dismissed, after which it will never be shown again. 
Closes https://github.com/Automattic/newspack-newsletters/issues/73
1.  On settings page, clear all API keys, then navigate to the Dashboard home. Verify the notification is shown.
2. Verify the link to Settings is correct.
3. Navigate to Settings and fill in all three API key fields. Verify the notification is no longer shown.
4. Clear API keys so the notification comes back. Click the X to dismiss it. Verify that it no longer appears on any pages.
If …
> Post-Activation Banner

- includes/class-newspack-newsletters-settings.php
Moves Settings submenu to Newsletters, rename to "Settings."
Closes https://github.com/Automattic/newspack-newsletters/issues/68
1. Verify "Settings" submenu under Newsletters.
2. Verify page continues to function as before.
3. Verify "Newspack Newsletter Settings" removed from top-level Settings menu.
> fix: move settings menu item to newspack newsletters menu

- includes/class-newspack-newsletters.php
This way theme styles are not applied to the Newsletter editor.
Closes #7 
Closes #69 
1. Create a new post, observe that it has some of theme's styling and potentially* a custom colour palette
2. Create a new newsletter, observe that it has just the default Gutenberg editor styles and the default colour palette
* `twentytwenty` theme has one for example
> Remove any other editor modifications

- src/editor/sidebar/index.js
Adds a List Management link beneath list `SelectControl` that links to Mailchimp Admin page for the list.
@thomasguillot there's no space between the link and the Groups UI beneath, but I left untouched.
Question: This assumes the base URL for Mailchimp admin URLs is `https://us7.admin.mailchimp.com`. This may not always be true. I've opened https://github.com/Automattic/newspack-newsletters/issues/76 to keep track of this question.
Closes https://github.com/Automattic/newspack-newsletters/issues/65
Select a list, verify the `ExternalLink` appears beneath it. Verify the link leads to Mailchimp's list administration page.
> feat: list management link

- src/components/template-modal/index.js
- src/components/template-modal/style.scss
Since the editor width has changed the previews look slightly off
__Before:__
__After:__
1. Add a new newsletter. Layouts look broken 
3. Refresh
> Fix layout preview viewport width

- includes/class-newspack-newsletters.php
- package.json
- src/components/template-modal/index.js
- src/components/template-modal/screens/api-keys/index.js
- src/components/template-modal/screens/template-picker/index.js
- src/components/template-modal/style.scss
- src/editor/index.js
- src/editor/sidebar/index.js
Adds a first screen to the Template Picker modal where users input the API keys needed to use the plugin (Mailchimp and MJML). 
- Refactor of the template picker to support multiple screens. Also refactored using React Hooks.
- New endpoints to get and set the API keys: `newspack-newsletters/v1/keys` GET|POST
- When keys are set they are also verified by pinging the services. 
Notes for @thomasguillot: 
- To avoid confusion I've left this completely un-styled. 
- I used `Spinner` components to show the In-Flight state, but these are ugly and poorly placed. I suspect you'll have a different idea about this state anyway, so I put them in just to demonstrate how to detect the state.
- I included error messages for Mailchimp and MJML if the keys are empty or invalid. I assume you'll also want …
> API Key Modal

- includes/class-newspack-newsletters.php
Adds support for reusable blocks in Newsletters. 
Closes https://github.com/Automattic/newspack-newsletters/issues/81
1. On `master`, create a Newsletter and insert a tempalte.
2. Select any block, then click the triple dot icon in the toolbar. Verify "Add To Reusable Blocks" is not present. 
3. Switch to this branch, verify "Add To Reusable Blocks" is now present and works correctly.
> fix: support for reusable blocks in newsletters

- src/editor/index.js
Changed title from "Newsletter Settings" to simply "Newsletter".
1. Check the title of the sidebar panel
> Simplify title of newsletter settings panel

- src/editor/sidebar/index.js
- src/editor/utils.js
Restores the Groups UI and functionality. 
Closes https://github.com/Automattic/newspack-newsletters/issues/89
Create a new Newsletter, select a list with Groups defined, observe the groups UI and functionality is back.
> fix: bring back groups ui

- includes/class-newspack-newsletters.php
- src/components/template-modal/screens/api-keys/index.js
- src/editor/editor/index.js
There are two issues in the initial setup flow: `"false"` values in credentials inputs (#97) and empty campaign being returned. This fixed both.
Closes #97
1. Ensure branch is `master`
2. Remove credentials (`wp db query "DELETE FROM wp_options WHERE option_name LIKE 'newspack_newsletters%'"`)
3. Add new newsletter post, observe:
- an error in network tab and JS console – a call to Mailchimp API was made without the API key
- values for credentials are all `"false"` (#97)
1. Fill in the credentials, choose layout, and save draft. Observe that now the spinner in the sidebar, next to "Retrieving Mailchimp data…", is spinning indefinitely. Observe in the network tab that an empty campaign data was returned. 
1. Switch to this branch, clear the credentials again. 
1. Add a new newsletter …
> Fix initial setup errors

- src/editor/index.js
- src/editor/sidebar/index.js
- src/editor/testing/index.js
Adds a `Testing` panel in the sidebar with test email `TextControl` and `Button` to send test. After https://github.com/Automattic/newspack-newsletters/pulls lands we'll be able to notify on success and failure when sending test emails.
Closes https://github.com/Automattic/newspack-newsletters/issues/94
1. Create a Newsletter.
2. Observe Testing panel in the sidebar.
3. Send a test to a real email, verify the email is sent.
> feat: separate panel for test email ui

- src/editor/sidebar/index.js
The data center prefix on Mailchimp dashboard URLs will differ from account to account, but if it is omitted from a dashboard URL Mailchimp will redirect to the correct one (h/t @BradHudson for the solution). In this PR the `Manage List` link URLs are corrected accordingly.
Closes https://github.com/Automattic/newspack-newsletters/issues/76
1. Create a Newsletter, select a list.
2. Verify the `Manage List` link goes to the list's management page in the Mailchimp dashboard.
> fix: remove data center prefix from mailchimp url

- includes/class-newspack-newsletters.php
- src/editor/index.js
- src/editor/layout/index.js
- src/editor/layout/style.scss
Sidebar panel which displays the current layout and offers an option to pick a new one. 
@thomasguillot: I left it almost entirely unstyled. Note this will probably only work with newly created Newsletters, since the template selection is persisted as custom post meta.
Closes https://github.com/Automattic/newspack-newsletters/issues/72
> feat: sidebar ui to change template

- includes/class-newspack-newsletters.php
- src/components/with-api-handler/index.js
- src/components/with-newsletter-api/index.js
- src/editor/editor/index.js
- src/editor/sidebar/index.js
Adds a Higher Order Component to handle error/success notifications for all API traffic, as well as managing "in flight" state (taken pretty directly from https://github.com/Automattic/newspack-newsletters/pulls, h/t @adekbadek ). Implements error and success messaging for the test email feature. 
After this PR lands, we'll open separate PRs for error/success notification in other specific features.
Closes https://github.com/Automattic/newspack-newsletters/issues/27.
1. Create a Newsletter, send a test email to `a@example.com`. Observe  detailed error message.
2. Send a test email to a real address. Observe success message. Verify the email has actually been sent. 
3. Refresh editor. In another window, navigate to Newsletters->Settings, clear out the Mailchimp API key and Save. Send a …
> Test Email Notifications

- src/editor/post-status-slot/index.js
- src/editor/testing/index.js
Also, the preview button will be disabled instead of hidden to prevent UI jumping.
Closes #25
1. Open a newsletter post or create one
2. Make some changes, but don't save
3. Hit "Preview" – observe that the post is first saved, then the preview is shown. The preview should contain the up-to-date version.
1. Send a test email – observe that the post is first saved. The email should contain the up-to-date version.
> Save post before previewing or sending test email

- src/editor/sidebar/index.js
Fixes some issues arising from sender data being in the `Sidebar`'s state and campaign data.
1. Ensure branch is `master`
2. Open a newsletter and set sender name and email
3. Close and open the "Newsletter" panel
1. Observe that sender name and email disappeared
1. Repeat pt. 3
1. Observe that sender data is there as expected
> Sidebar: store sender data in post meta

- includes/email-template.mjml.php
This PR applies some "default" style to links, making sure they inherit the colour of the parent element, that they have an underline and a focus state (important for accessibility!).
Closes #116 and #122
1. Change the colour of some links.
2. Publish the newsletter (or send test, or preview)
3. Links should be using the default's browser styles
4. Switch to this branch
5. Retry to send
> Fix link colour and text-decoration

- includes/class-newspack-newsletters.php
Adds try/catches to the API endpoint callbacks for setting the sender name and reply-to email.
Partially addresses https://github.com/Automattic/newspack-newsletters/issues/24
1. Create a Newsletter.
2. In another browser window, navigate to Newsletters->Settings and clear out the Mailchimp API key.
3. In the first window, input the sender name and email, then click to update. Observe the error notification.
> feat: error notifications for from name/email changes

- src/components/with-api-handler/index.js
- src/editor/testing/index.js
A series of merges caused a regression in the test email functionality, causing notification after successful tests (or errors) to fail. This branch corrects this. 
1. Create a Newsletter. 
2. Send a test to a real email address. Observe the success message when test is sent.
3. Send a test to `a@example.com`. Observe failure message.
> fix: regression of test email error/success notifications

- src/editor/sidebar/index.js
Fixes a bug that causes the editor to crash when sender name or email are edited.
Closes https://github.com/Automattic/newspack-newsletters/issues/117
1. On `master`, create a new Newsletter, insert a template, and begin editing the sender name field in the `Newsletter` sidebar.
2. Observe the editor crash.
3. Switch to this branch and repeat. Observe no crash.
> fix: crash when editing 'from' fields

- includes/class-newspack-newsletters-renderer.php
- includes/class-newspack-newsletters.php
Adds error notifications in save and publish operations. These are trickier to catch since they are handled by standard Gutenberg XHR requests as opposed to custom endpoint defined by the plugin. To work around this, errors caught in save/publish are stored in a transient for 45 second, and are then displayed the next time the Mailchimp data retrieval endpoint is hit. This is tricky to test since many things you could do to break the flow will _also_ break the retrieval endpoint, so it's not clear where the error is coming from. The best way to test is to break the MML operation because this only occurs during save. 
1. Create a Newsletter, select a template.
2. In Newsletters->Settings, add a character to one of the MJML fields.
3. In the editor, save or publish the post. Observe the …
> feat: error handling in save and publish operations

- includes/class-newspack-newsletters.php
Adds error catching and notification when retrieving Mailchimp data.
Partially addresses https://github.com/Automattic/newspack-newsletters/issues/24
1. Create a Newsletter, insert a template, verify the Newsletter sidebar loads correctly with no errors. 
2. In another window navigate to Newsletters->Settings, delete Mailchimp key and Save.
3. Refresh the editor window, observe error.
4. After restoring Mailchimp API key, enable custom fields for the post (3 dots, options, Custom fields), then add a random character to the `mc_campaign_id` field. 
5. Refresh the editor window, observe error.
6. After restoring the campaign ID, log in to Mailchimp and delete the campaign linked to the post.
7. Refresh the editor window, observe error.
> feat: error notifications when retrieving mailchimp data

- includes/class-newspack-newsletters.php
- src/components/template-modal/screens/api-keys/index.js
Improved permissions for Newsletter features:
1) Administrators can do everything.
2) Editors do not see the Settings page.
3) If an editor sees the API keys modal, the fields will be blank and error messages will inform that only Administrators can set keys.
4) Editors can do everything else.
5) Users below Editor level don't even see the menu item, and can't do anything.
Closes https://github.com/Automattic/newspack-newsletters/issues/88
1. Log in as an administrator. Verify you can set keys and create/save/publish newsletters. 
2. Log in as an editor. Verify you can create/save/publish newsletters. 
3. Verify you don't see the Settings page.
4. Logged in as an admin, clear at least one of the API keys.
5. As an editor verify the error messages in the API keys modal.
6. Log in as an …
> feat: improved permissions

- includes/class-newspack-newsletters-renderer.php
- includes/class-newspack-newsletters.php
Clearer error messages for Mailchimp API interactions. 
Support for `NEWSPACK_NEWSLETTERS_DEBUG_MODE` wp-config flag, which will cause original Mailchimp error messages to be displayed as received.
Closes https://github.com/Automattic/newspack-newsletters/issues/129
1. From within a Newsletter send a test email to `a@example.com`. Observe error message: `Error sending test email.`
2. Edit `wp-config.php` and add `define( 'NEWSPACK_NEWSLETTERS_DEBUG_MODE', true );`
3. Send test email to `a@example.com`, observe error message: `test_emails must contain valid emails. these emails are invalid: a@example.com`
4. To test more thoroughly, step through `includes/class-newspack-newsletters.php`. For every time you encounter `validate_mailchimp_operation`, mangle the Mailchimp API request (e.g. …
> feat: clearer error messages

- includes/class-newspack-newsletters.php
Now that we have errors present, one issue has surfaced. It looks like the `sync_with_mailchimp`
1. [on `master` branch]
2. Create and send a newsletter 
3. Observe an error notice about setting content of a sent campaign being shown
3. Switch to this branch, repeat step 2
3. Observe no error notice being shown
> Prevent updating content of a sent campaign

- src/components/template-modal/screens/api-keys/index.js
- src/components/template-modal/screens/template-picker/index.js
- src/components/template-modal/style.scss
- src/editor/layout/index.js
Reworks the handling of blank templates. In the Template Picker blank template no longer has a thumbnail. Instead there is a button in the upper right that gives the user a blank canvas to work from. After selecting blank template, no thumbnail is shown in the sidebar either.
Closes https://github.com/Automattic/newspack-newsletters/issues/111
1. Create a Newsletter. Verify there are only 5 template thumbnails and blank is not one of them. 
2. Click `Start From Scratch`. Verify the modal disappears and a blank editor is shown.
3. In the Layout sidebar panel, verify there is no thumbnail.
4. Click Change Layout, then select one of the 5 templates.
5. Verify insertion works as expected, and that the thumbnail for the template is shown in the sidebar.
> refactor: rework the blank template ui

- includes/class-newspack-newsletters.php
- src/components/with-api-handler/index.js
- src/editor/sidebar/index.js
- src/editor/sidebar/style.scss
The reply-to email address used in a Mailchimp campaign must be verified or the campaign will fail to send. More on domain verification: https://mailchimp.com/help/verify-a-domain/. When the sender email is set, all verified domains are fetched from Mailchimp and if the email address is not part of one of these, an error notification is displayed.
Closes https://github.com/Automattic/newspack-newsletters/issues/23
1. Create a Newsletter, select a template, set the From Email to an unverified domain (e.g. `test@unverifieddomain.com`)
2. Observe error notification like this: `unverifieddomain.com is not a verified domain. Verified domains for the linked Mailchimp account are: verifieddomain1.com, verifieddomain2.com, verifieddomain1.com.`
3. Set the From Email to a verified domain, observe …
> feat: throw error for unverified reply-to email

- .circleci/config.yml
Add alpha branch to CircleCI configuration.
> fix: add alpha to branches

- package-lock.json
- package.json
- src/editor/blocks/posts-inserter/index.js
- src/editor/blocks/posts-inserter/utils.js
Previous solution relied on memoization of `getTemplateBlocks` function in order to ensure the hook that calls `setAttributes` is only called if `templateBlocks` changes. Probably because of the comparison algorithm used by the hook (which compares the current and previous items in the dependencies array) this did not work as intended – hook function was called even though the contents of `templateBlocks` array stayed the same. 
The new solutions is based on realisation that the only thing that can change the intended content of `innerBlocksToInsert` are the block attributes.
Closes #146 
1. [on `master`]: Create a new newsletter, choose "Daily/Weekly" template
2. Observe that images in Posts Inserter block in layout preview flicker and an ever-increasing amount of requests is made for …
> Fix Posts Inserter infinite loop

- src/editor/index.js
Closes #153
1. In a newsletter, insert a group block
2. Observe lack of "wide" alignment setting
> Remove wide alignment for group block

- includes/class-newspack-newsletters.php
Background Gradients are not supported by MJML (`background-image`) so we shouldn't show the option.
Fixes #138 
1. To a group or button, change the background colour, check that you can select gradients
3. Gradients should be gone
> Remove support for background gradients

- src/editor/sidebar/index.js
Renames "list" to "audience," to reflect Mailchimp's naming convention.
Closes https://github.com/Automattic/newspack-newsletters/issues/148
1. Create a Newsletter, insert a template. Observe the list selection dropdown reads "-- Select an audience --" 
2. Make a list selection. Observe the convenience link below reads "Manage audience."
> fix: rename list->audience to reflect mailchimp

- src/editor/blocks/posts-inserter/index.js
Follow up to changes from #151, which is the problem of 
1. saving the Posts Inserter inner blocks in an attribute*
2. in a way that does not trigger an infinite loop
Which is basically the question of memoization. After trying out different approaches with regular memoization, I've settled on a perhaps ugly solution of using a stringified form of the attribute to be updated as the `useEffect` dependency. This means that the hook function will be fired only when the value of `innerBlocksToInsert` will _really_ change. It might be a new object on each render, but as long as the stringified version remains the same, there will be no inifinite loop.
*so it can be rendered without needing to duplicate attributes-to-posts logic on the backend
The wrong assumption behind changes in #151 was …
> Fix posts inserter no-insertion workflow

- src/components/template-modal/screens/template-picker/index.js
- src/components/template-modal/style.scss
- src/editor/layout/index.js
- src/editor/layout/style.scss
Instead of relying on Gutenberg styles to display the different layouts – since it's constantly evolving – this PR adds its own set of styles for the layouts thumbnails
Closes #172
_Note: when Gutenberg is disabled, the modal header is slightly different which creates a slight bug by the "W" when fullscreen. I can't fix of an easy fix and it should be resolved when more Gutenberg updates are shipped directly into Core._
1. Follow instructions in #172
3. Repeat
> Fix newsletter layouts preview thumbnails

- src/components/template-modal/screens/template-picker/index.js
- src/editor/blocks/posts-inserter/consts.js
- src/editor/blocks/posts-inserter/deduplication.js
- src/editor/blocks/posts-inserter/index.js
- src/editor/blocks/posts-inserter/utils.js
- src/editor/layout/index.js
Prevents duplicate posts when multiple instances of Posts Inserter block are on a post.
Closes #147 
1. Create or edit a newsletter, insert a couple of Posts Inserter blocks
2. Observe that the posts displayed are not duplicated
3. Experiment with adding/removing/changing parameters of the Posts Inserter blocks – all the time there should be no duplicated posts
4. Observe the posts are updated after a previous block is changed/removed – that is, if there are two Posts Inserter blocks with default settings, removing the top one should update posts in the remaining one with the three latest posts.
> Posts Inserter deduplication

- package-lock.json
- package.json
- src/editor/blocks/posts-inserter/index.js
- src/editor/blocks/posts-inserter/query-controls.js
- src/editor/blocks/posts-inserter/style.scss
Enable selecting specific post ids
1. Create or edit a newsletter, add a Posts Inserter block
2. Toggle "Display specific posts", observe UI change to a token field
3. Choose some posts, observe only these are rendered in the Posts Inserter block
> Enable selecting specific post ids

- includes/class-newspack-newsletters-renderer.php
- includes/email-template.mjml.php
- src/components/template-modal/screens/template-picker/index.js
- src/components/template-modal/style.scss
- src/editor/blocks/posts-inserter/index.js
- src/editor/editor/style.scss
- src/editor/layout/index.js
- src/editor/sidebar/style.scss
This increases the overall padding from 16px to 20px.
The PR also fixes some margin inconsistencies with blocks in the editor vs the actual email
screencast: https://cloudup.com/izPdpgD1Hac
1. Create a new newsletter, play with different blocks
2. Send a test and compare the editor with what you received
> Update general padding of newsletter to increase white space

- src/editor/layout/index.js
Prevent a bug occurring when there's a Posts Inserter block in post content, and the template modal on top of the post, with a Posts Inserter block in a preview.
1. On master branch:
1. Edit a newsletter with a Posts Inserter block, or create one
2. Change the layout, choose the "Daily/Weekly" layout
3. Observe Posts Inserter blocks in the preview flickering
1. Repeat 2, 3; observe no flickering
> Prevent post flickering in template selection

- src/components/send-button/index.js
- src/editor/editor/style.scss
- src/editor/layout/index.js
- src/editor/layout/style.scss
- src/editor/sidebar/index.js
- src/editor/utils.js
- src/service-providers/example/index.js
- src/service-providers/mailchimp/index.js
- src/service-providers/mailchimp/utils.js
Closes #139
1. Create a newsletter and fill settings so that it is valid ("Send" button is active) – set just list, without the group.
2. Click "Send" - observe a confirmation modal appears with the set list name and subscriber count
3. Cancel 
3. Set a group and click "Send" – observe that the modal now has information about the group and group's subscriber count
4. Send the campaign, observe that it is sent
> Add pre-send confirmation

- includes/class-newspack-newsletters-renderer.php
Closes #162
1. Create a columns block with two columns
1. Set one of them to a custom width
1. Send a test email or campaign – columns should have the widths as in the editor
> Fix custom column width issue

- includes/class-newspack-newsletters-renderer.php
- includes/class-newspack-newsletters.php
- src/editor/editor/index.js
Closes #173
1. On `master` branch, create a newsletter and set color of something to "Vivid Purple"*
2. Send or preview email, observe that the color is not handled
3. Switch to this branch
3. Send or preview email, observe that the color is there
*
> Handle color palette as it appears in the editor

- src/service-providers/mailchimp/ProviderSidebar.js
Fixes a regression that caused the Campaign Sent `Notice` to not be shown after sending.
Closes https://github.com/Automattic/newspack-newsletters/issues/188
1. Create a Newsletter, populate the fields, send it.
2. Verify the Newsletter sidebar panel displays a green Notice instead of the fields.
> fix: missing notice after campaign has been sent

- includes/class-newspack-newsletters.php
Settings URL in post-activation nag was not updated after settings were moved to a plugin page.
1. Remove the plugin settings from DB or install plugin on a fresh WP instance
2. Install and activate the plugin
3. Observe the post-activattion nag ("Thank you for activating Newspack Newsletters…") – the link to settings should lead to plugin settings on the plugin page
> Fix settings url in post-activation nag

- includes/class-newspack-newsletters.php
Trashing a Newsletter will lead to a Fatal if the Mailchimp API key is invalid or missing. This branch allows the Mailchimp API request to fail silently.
Closes https://github.com/Automattic/newspack-newsletters/issues/206
1. On `master`, create a Newsletter.
2. In Newsletters->Settings, remove or mangle the Mailchimp API key. 
3. On the Newsletters list page, trash the post, observe fatal error. 
4. Switch to this branch, retry deletion. Observe post is trashed with no error.
> fix: when trashing post allow mailchimp api call to fail silently

- src/newsletter-editor/editor/index.js
This PR addresses a regression introduced in https://github.com/Automattic/newspack-newsletters/pull/176. When creating the very first Newsletter, a sequence occurs which clears the Mailchimp Campaign ID field which leads to a confusing error message (`No Mailchimp campaign ID found for this Newsletter`) and creation of duplicate Mailchimp campaigns. The `useEffect` that sets the `color_palette` meta field executes before there is a campaign ID set. This leads to a sequence where the campaign ID is set, then unset, and multiple campaigns are created.
One side effect of this fix is that the colors may be incorrect the very first time a campaign is synced, but the post will always be saved again before testing or sending so this is not a serious issue. 
Closes …
> fix: situation that overwrote mc campaign id

- src/editor/blocks/posts-inserter/utils.js
Correct a bug that occurs with posts that have an empty custom excerpt. The Posts Inserter block will display their full content as the excerpt, and the word count control does nothing.
Closes https://github.com/Automattic/newspack-newsletters/issues/204
h/t @adekbadek for the fix!
1. Edit the top post. In the Excerpt sidebar, put in a single space and Update the post. Do the same for the next few ones too.
2. While still on `master`, create a Newsletter from a template. Observe in the Posts Inserter blocks the edited posts show all of their content as the excerpt. 
3. Change the `Max number of words in excerpt` `RangeControl`. Observe this has no effect on the length of the excerpts.
4. Switch to this branch.
5. Observe the excerpts are displayed correctly and the `RangeControl` …
> fix: resolve excerpt length issue

- src/editor/blocks/posts-inserter/utils.js
Closes #201
1. On master,
2. Create a post without a featured image, then add a new newsletter
2. Observe the templates that use Posts Inserter block display an empty image block in place of the featured image
3. Switch to this branch, rebuild
4. Redo step 2, observe that there is no empty image block in Posts Inserter block
> Prevent empty featured image rendering

- src/editor/blocks/posts-inserter/index.js
Closes #199.
1. On master
2. Create a new newsletter. Wait until the previews load Posts Inserter blocks and you see one in "Breaking News" layout preview
3. Click on "Daily/Weekly" layout preview
4. Observe that the Posts Inserter in "Breaking News" layout preview is updated
5. Switch to this branch and rebuild
6. Redo steps 2-3, observe that the Posts Inserter in "Breaking News" layout preview is not updated
> Prevent deduplication in layout picker preview

- includes/class-newspack-newsletters-renderer.php
- includes/class-newspack-newsletters.php
- src/components/select-control-with-optgroup/index.js
- src/editor/style.scss
- src/newsletter-editor/index.js
- src/newsletter-editor/typography/index.js
Add font selection to the Newsletters plugin. Adds a Typography sidebar panel with `SelectControl`s for choosing body and header fonts. The options are all web-safe fonts, described in screenshots in https://github.com/Automattic/newspack-newsletters/issues/198. Selected fonts will immediately be used in the editor and in rendered emails. 
Note: the editor font switching uses CSS variables, which are not supported in IE11: https://caniuse.com/#feat=css-variables.
Closes https://github.com/Automattic/newspack-newsletters/issues/198
1. Create a Newsletter.
2. Experiment with different changes to the Header and Body fonts in the Typography sidebar panel.
3. Observe the typography in the editor changes to reflect the selections.
4. Send yourself a test email, observe the correct fonts are …
> feat: font picker

- includes/class-newspack-newsletters.php
- src/service-providers/mailchimp/ProviderSidebar.js
The Mailchimp lists endpoint defaults to returning ten items. For customers with more than ten lists, they have no way to select a list. This PR raises the limit to 1000, the maximum. Additionally it contains a fix for a crash that occurs if a Newsletter's `list_id` isn't found in the lists array. This doesn't address the case of a Mailchimp account with more than 1000 lists, but that feels like a very extreme case, especially considering typical segmentation strategies.
Closes https://github.com/Automattic/newspack-newsletters/issues/220
1. Add more than 10 lists to Mailchimp account, or switch API key to an account with more than 10 lists.
2. On `master`, create a Newsletter. Observe only the first 10 lists are shown in the `SelectControl` in the Newsletter sidebar panel.
3. Switch to …
> fix: raise list limit to maximum

- includes/email-template.mjml.php
On smaller screens, disregard explicit image height.
Closes #221
1. Create a newsletter with an image. Set the image dimensions, but keep the aspect ratio so it still looks ok.
2. Send a test email and open it on GMail and Outlook apps on iOS device with a screen smaller than 590px (e.g. iPhone 8). 
3. Observe the image preserves aspect ratio (is not squished)
> Fix: image height on smaller screens

- includes/class-newspack-newsletters.php
Namespace argument in `register_rest_route` should not start nor end with a slash. Including it does not break anything, but pollutes the error log which impairs development.
> Fix namespace use in register_rest_route

- includes/class-newspack-newsletters-renderer.php
- src/editor/blocks-validation/blocks-filters.js
As discussed in #231, column middle alignment is a tricky issue because Gutenberg uses flexbox, and MJML uses `vertical-align` CSS property. Recreating flexbox somehow is a bigger undertaking, so as a compromise the possibility of an all-column-middle-aligned layout is introduced in this PR. Before, middle alignment of columns was not possible in any configuration. 
Closes #231 
1. Create a newsletter, insert a columns block with some columns
2. Set the column**s** block to middle vertical alignment (the content should be of different heights for the effect to be visible) – send a test email and observe the content is indeed middle-aligned, as in the editor.
3. Change one of the columns to a non-middle alignment – observe a warning being shown.
4. Fix the error by either setting the …
> Handle column middle alignment

- src/editor/blocks-validation/blocks-filters.js
#235 Introduced a regression, this PR fixes it.
1. On `master`, 
2. Insert a Posts Inserter block in a fresh newsletter
2. Observe block rendering failing in the editor
3. Switch to this branch and rebuild
4. Redo 2, observe block rendering as expected
> Fix Posts Inserter columns warning

- src/newsletter-editor/index.js
- src/newsletter-editor/styling/index.js
Fixes a subtle bug, see below
1. On `master`
2. Create a newsletter, apply custom styling in the Styling panel in Sidebar, **close** the panel and refresh the page
3. Observe that the custom styling is not applied until the Styling panel is opened
4. Switch to this branch, rebuild
4. Redo step 2, refresh the page – observe that the custom styling is applied
> Fix: apply custom styles even if styling tab in sidebar is closed

- src/editor/blocks/posts-inserter/index.js
Closes #236.
1. Try to reproduce #236, observe the flickering situation is greatly improved*
\* The posts in Posts Inserter flicker only when loading the images
> Fix Posts Inserter flickering

- includes/class-newspack-newsletters-renderer.php
Links applied to Image blocks don't render in emails. 
Closes https://github.com/Automattic/newspack-newsletters/issues/253
1. On `master` with latest Gutenberg plugin create a Newsletter, add an image, apply a link to it.
2. Send a test email to yourself. Observe the image is not linked.
3. Switch to this branch. Save and send another test. Observe the image is linked as expected.
> feat: support linked images

- includes/service-providers/class-newspack-newsletters-service-provider-controller.php
- includes/service-providers/class-newspack-newsletters-service-provider.php
Resolves some PHP notices.
Closes https://github.com/Automattic/newspack-newsletters/issues/250
1. On `master` create a new release.
2. Spin up a Jurassic Ninja instance, install and activate the release.
3. Observe PHP notices are sent to the browser.
4. Switch to this branch, create a new release.
5. Replace the plugin on the JN site with the new release.
6. Observe the notices go away.
7. Create a newsletter, paste in API keys.
8. Send a test email to yourself, be sure it works as expected.
> fix: resolve php notices

- includes/class-newspack-newsletters.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp-controller.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
- src/components/send-button/index.js
- src/components/send-button/style.scss
- src/service-providers/mailchimp/ProviderSidebar.js
- src/service-providers/mailchimp/index.js
- src/service-providers/mailchimp/style.scss
- src/service-providers/mailchimp/utils.js
Adds Mailchimp segmentation via tags. Tag creation will be handled in a separate PR. 
Closes #21
1. Create a newsletter, after selecting a list observe a new input below Groups selection – Tags
2. (Create some tags in Mailchimp if there are none)
3. Start typing a tag name, observe autocomplete in action, choose a tag
4. Observe the tag is added to the campaign on Mailchimp
> Mailchimp: tags segmentation

- includes/class-newspack-newsletters-renderer.php
- src/editor/index.js
Enables alignment options for social icons block.
1. Add a newsletter, insert a social icons block
2. Test with different alignment options – in the email the alignment should work as in the editor
> MJML: handle social icons block aligment options

- includes/class-newspack-newsletters-renderer.php
- src/ads-admin/AdsManager/index.js
- src/ads-admin/editor/index.js
- src/ads-admin/utils.js
Closes #251.
1. Create a newsletter ad, do not an expiry date, publish
2. Observe that it's listed as active in the newsletter ads view, with a note about not expiration date set
3. Publish a newsletter, observe the ad is appended to the bottom
> Ads: allow no expiry date

- includes/class-newspack-newsletters-editor.php
Makes it possible to add multiple buttons.
1. Add a Buttons block in a Newsletter
2. Observe that a "Add Button" button is visible, allowing to add more buttons
> Fix: support adding multiple buttons

- src/editor/blocks/posts-inserter/index.js
- src/editor/blocks/posts-inserter/style.scss
In the Post Inserter block, images sometime take a while to get inserted into the `BlockPreview`. This adds a "loading" state with the WP spinner component while image blocks are still being inserted. Note that there may be a very brief delay after the blocks are shown while the image actually loads—this is unavoidable unless we attach event listeners to the actual DOM for image `load` events, which gets messy fast since the `BlockPreview` elements get rendered inside iframes and don't currently support any on ready callbacks. I tried testing this in #248, but after doing this refactor I believe we should avoid mixing virtual DOM and true DOM logic as a best practice.
Since the preview blocks are built from post data using array mapping functions instead of true asynchronous behavior, the …
> feat: show spinner while Post Inserter is loading image blocks

- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
- src/components/with-api-handler/index.js
- src/newsletter-editor/testing/index.js
- src/newsletter-editor/testing/style.scss
Sending a test email is an async op. This adds a spinner to the Testing panel while the op is still in progress. It also improves the error messaging if the test fails to send.
This adds a spinner animation while sending a test email (an async op) is still in progress:
https://d.pr/i/NG4WDY
It also improves the error messaging so that a.) the message sticks around after being displayed, and b.) it appends the error message returned from Mailchimp to help inform the user:
https://d.pr/i/PP1vjl
Closes #158.
1. Check out this branch and rebuild JS.
2. Draft a new Newsletter.
3. Send a test email using the Testing UI in the sidebar. The first few sends should be successful.
4. Keep sending tests until Mailchimp starts returning rate limit errors. Observe the error messaging when that happens.
> Add spinner while sending test emails

- includes/class-newspack-newsletters-ads.php
- includes/class-newspack-newsletters-editor.php
- includes/class-newspack-newsletters-renderer.php
- includes/class-newspack-newsletters.php
- src/ads-admin/AdsManager/style.scss
- src/ads-admin/editor/index.js
- src/ads-admin/editor/style.scss
- src/newsletter-editor/sidebar/index.js
- src/newsletter-editor/sidebar/style.scss
- src/newsletter-editor/styling/index.js
Closes #237. Also, fixes a small visual bug in the ad removal modal.
1. Add some newsletter ads, set positions in sidebar settings
2. Observe that an ad has 100% position (bottom of content) by default
3. Observe that the ads are placed accordingly in newsletter HTML
4. _Additional thing_: Click "Delete" on an ad in ad manager to remove it. Observe the buttons in the modal have some spacing between.
> Ads: handle setting ad position

- composer.json
- composer.lock
- includes/class-newspack-newsletters.php
- includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact-controller.php
- includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
- newspack-newsletters.php
- src/newsletter-editor/testing/index.js
- src/service-providers/constant_contact/ProviderSidebar.js
- src/service-providers/constant_contact/index.js
- src/service-providers/index.js
Adds support for Constant Contact. 
To avoid overcomplicating this PR, the branch doesn't include UI for selecting ESP and inputting Constant Contact API key and access token. This will be tackled in another PR immediately after this one lands. Temporarily, API key and access token are set as `wp-config` constants.
The implementation uses the V2 API and requires an API key and Access Token. The V3 API seems to require an oAuth flow which wouldn't be appropriate for this use case since there is no centralized application. If this proves problematic we could rearchitect with a WordPress.com endpoint, but this doesn't seem warranted at the moment. 
Here are a few differences between the Constant Contact and Mailchimp implementations:
- Besides list selection, there is no segmentation support …
> feat: constant contact integration

- includes/class-newspack-newsletters-renderer.php
Fixes a regression that caused Group block background colors to get lost.
Closes https://github.com/Automattic/newspack-newsletters/issues/289
1. On `master` create a Newsletter. Add Group blocks, set background color.
2. Send a test email, observe the background colors are ignored.
3. Switch to this branch, resend test. Observe the background colors are present in the email.
> fix: group block background color

- includes/class-newspack-newsletters-renderer.php
Closes #229.
1. On `master`, create a newsletter with buttons. Set colors on them – custom and picked from color palette
2. Send a test email or preview the email, observe the custom colors are lost
3. Switch to this branch, send or preview again, observe colors are all there
> Fix custom colors on buttons

- includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
- src/newsletter-editor/editor/index.js
- src/newsletter-editor/sidebar/index.js
This branch fixes two issues that occur after selecting the Email Service Provider for the first time. 
1. Selecting ESP in the modal occurs too late to update the Service Provider sidebar. As a result, the ESP's sidebar is not correctly loaded.
2. API calls with be made to `/example/` endpoints.
Closes https://github.com/Automattic/newspack-newsletters/issues/298
1. On `master`, navigate to Newsletter->Settings. Remove ESP key, set the Service Provider to "Select service provider," and Save.
2. Create a new Newsletter.
3. In the modal, choose Mailchimp and input Mailchimp API key.
4. Select a Layout.
5. Observe the Newsletter sidebar does not show Mailchimp lists Select.
1. On `master` create a Newsletter.
2. Navigate to Newsletter->Settings, remove ESP key and set Service Provider to …
> fix: corrected flow after setting esp in modal

- includes/class-newspack-newsletters-renderer.php
- includes/email-template.mjml.php
- src/editor/style.scss
Originally, the newsletters added 20px padding around each element, which means there's typically 40px between things like paragraphs in the newsletters. This feels like a bit too much -- for comparison, the theme has 32px between elements, and the fonts are larger, so it's less space relative to how large the fonts are.
This PR reduces the padding to 12px, leaving a 24px gap between elements, which feels like it fits a bit more.
Closes #281.
1. Draft up an email, using one of the pre-made layouts, so you have a good variety of elements. Send a test email to yourself.
2. View the email in the editor, and your email client, and note the spacing:
**Editor:**
**Email:**
3. Apply the PR and run `npm run build`.
4. Refresh the editor and send a new fresh test email; confirm that the spacing …
> Reduce padding between elements in newsletter emails

- src/components/init-modal/style.scss
This PR fixes the modal header which was off by 1px and make sure the settings have the correct margin on small screens.
1. Remove your API keys.
2. Create a Newsletter -- notice the header border bottom slightly off
3. On the settings screen, resize your screen at 600px
4. Switch to this branch
5. Refresh and check again
> Fix modal margin and header height

- includes/class-newspack-newsletters.php
- includes/service-providers/class-newspack-newsletters-service-provider.php
3 sentences in the plugin have the wrong domain. It should be `newspack-newsletters`, not `newspack`
> Fix escaped domain

- includes/class-newspack-newsletters-settings.php
- includes/class-newspack-newsletters.php
Adds a setting to select the public newsletter slug. The default is `newsletter`. After changing the slug, permalinks will be flushed automatically.
Closes https://github.com/Automattic/newspack-newsletters/issues/318
1. Create a Page and set the permalink to `newsletter`.
2. Create at least one Newsletter, switch on `Make newsletter page public?`, and publish. 
3. On the frontend, navigate to `/newsletter`. Observe the Newsletter archive page, not the Page created.
4. Navigate to Newsletter->Settings, change `Public Newsletter Posts Slug` to `newsletter-archive`
5. On the frontend navigate to `/newsletter` and observe the Page created in step 1.
6. Navigate to `/newsletter-archive`, observe the Newsletter archive page.
7. Click to view a Newsletter, and observe that `newsletter-archive` …
> feat: option to specify public newsletters slug

- includes/class-newspack-newsletters-editor.php
I noticed the following errors are thrown when saving events calendar events:
```
[02-Sep-2020 17:48:21 UTC] PHP Notice:  Trying to get property 'post_type' of non-object in /wordpress/plugins/newspack-newsletters/1.11.0/includes/class-newspack-newsletters-editor.php on line 157
[02-Sep-2020 17:48:21 UTC] PHP Notice:  Trying to get property 'post_type' of non-object in /wordpress/plugins/newspack-newsletters/1.11.0/includes/class-newspack-newsletters-editor.php on line 165
```
`get_post` can potentially return `null`, so the code should verify that a post was returned before getting fields from the post. This PR simplifies the post type check and prevents those sorts of issues from happening.
I have a patch for this same issue in Newspack Sponsors at …
> Harden post type checks

- src/editor/blocks/posts-inserter/query-controls.js
I've tested on Gutenberg versions from `8.5.0` to current (`8.9.2`) and the issue (component crashing without the `categoriesList` prop supplied) is not reproducible, which seems like a good enough buffer. Contrary to what I wrote in #285, it must've been fixed earlier than `8.5.0`.
Closes #285.
1. Create a Newsletter, insert a Posts Inserter block
2. Observe that there is no empty category select field (issue #285)
> Posts Inserter: remove empty category select

- includes/class-newspack-newsletters.php
Fixes a regressions introduced with the ESP selection UI. 
1. On `master`, remove MJML credentials in the plugin settings
2. Create a new newsletter – observe that there is no settings modal preventing you from doing so
3. Switch to this branch and rebuild
4. Create a new newsletter – observe a settings modal prompting to input MJML credentials
> Fix: gate editor with settings modal when no MJML creds are set

- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
The API call to retrieve Mailchimp tags seems can run slow if there are many tags. For Washington City Paper, one of their lists has ~50 tags, and the request was timing out at 10s, which is the default timeout. This branch increases it to 20s.
Simply verify that tag retrieval continues to work as expected.
> fix: increase timeout for api tag retrieval

- includes/class-newspack-newsletters.php
#330 introduced a regression – there should be a check before provider's method is called. 
1. On a site which does not have Newsletters plugin configured, observe `master` causing a fatal error (both frontend and admin)
2. Switch to this branch, observe things go smoothly
> Fix: handle missing provider

- includes/class-newspack-newsletters.php
- src/components/send-button/index.js
- src/newsletter-editor/editor/style.scss
Adds `author` support for newsletters, so editors can control the byline displayed with public newsletter posts. Also updates the criteria for the `isDirty` flag so the post can be updated if certain post settings are changed that can affect the published newsletter post.
1. On `master`, create a newsletter and send it. Make sure the `Make newsletter page public` option is enabled.
2. View the post on the site. Note that the byline displayed here is whoever created the newsletter, but that there is no Author field to change the author in the editor.
3. Switch to this branch and refresh the editor. Observe that there's now an Author field to select the post's author. Also observe that there's no longer a "switch to draft" button (as switching an already-sent newsletter to draft makes it …
> feat: add author support for newsletter CPT

- newspack-newsletters.php
Because of this error while submitting to WPORG:
> Error: Your plugin and author URIs are the same. Your plugin headers in the main plugin file headers have the same value for both the plugin and author URI (Uniform Resource Identifier). A plugin URI is a webpage that provides details about this specific plugin. An author URI is a webpage that provides information about the author of the plugin. Those two must be different. You are not required to provide both, so pick the one that best applies to your situation.
> Chore: remove author URI

- includes/class-newspack-newsletters-renderer.php
- phpcs.xml
We were thinking that WP query would return only published posts by default, but it's different in admin context:
> And if the query is run in an admin context (administration area or AJAX call), protected statuses are added too. By default protected statuses are ‘future‘, ‘draft‘ and ‘pending‘.
([source](https://developer.wordpress.org/reference/classes/wp_query/#status-parameters))
There's also a tiny tweak to PHPCS configuration here.
1. Create a draft ad
2. On `master`, observe it's inserted into the newsletter
3. Switch to this branch, observe the ad is not inserted into the newsletter
> fix: prevent draft ads from being inserted into newsletters

- src/newsletter-editor/editor/index.js
Handles breaking changes introduced in https://github.com/WordPress/gutenberg/pull/25419/files#diff-984d8e4bc7759027f99c018c4217d51fa6b563f2c47ed4d5291bac1cd3f305b7R7
Closes #358.
1. Ensure Gutenberg version is 9.1.1
1. Create or edit a newsletter, set colors of something to some color paletter values (*not* custom colors)
2. Observe that the colors are displayed properly in an email
3. Switch Gutenberg to < 9.0.0
4. Repeat 2, 3
> Fix: handle updated gutenberg colors setting

- includes/class-newspack-newsletters-settings.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
Adds a settings checkbox to opt-in to use Mailchimp tags. If unchecked (the default) tags will not be retrieved, and the UI will not be shown. 
Closes https://github.com/Automattic/newspack-newsletters/issues/378
1. Navigate to Newsletter->Settings. If Mailchimp is the selected provider observe new `Use Mailchimp Tags?` checkbox.
2. Switch to a different provider and save. Observe the checkbox is only visible if Mailchimp is selected.
3. With the checkbox off, create a Newsletter, and select a list. Observe no tags UI is shown.
4. Switch the checkbox on, create  Newsletter and select a list. Assuming there are tags created in the Mailchimp account, you should now see the UI and it should work as it always has.
> feat: setting to opt-in to mailchimp tags

- includes/class-newspack-newsletters-renderer.php
If the MJML API request failed, first a PHP would throw with `Uncaught Error: Cannot use object of type WP_Error`. This PR fixes it by doing the `is_wp_error` check first.
> Improve MJML request error handling

- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
Sending a test email often fails with no useful error message, although the email is sent anyway. This is most likely due to an API timeout. This branch simply increases the timeout for test sends to 60s, which is much higher than before.
Closes https://github.com/Automattic/newspack-newsletters/issues/140
This one is difficult to test.  Just try sending a bunch of test emails from a slow environment and verify there is always a success message.
> fix: longer timeout for test send

- includes/class-newspack-newsletters-renderer.php
Alignment changes in `Heading` and `Paragraph` blocks recently stopped working in emails, probably due to https://github.com/WordPress/gutenberg/pull/26492. This branch converts `textAlign` attributes to `align`, resolving the issue.
1. On `master` create a Newsletter with a variety of paragraph and heading alignments.
2. Send a test to yourself, observe the alignment choices are ignored.
3. Switch to this branch, resend the test.
4. Observe correct alignments in the email.
> fix: alignment for elements using textAlign

- includes/class-newspack-newsletters.php
Adds support for displaying Newsletters in Homepage Posts block. 
1. `newspack-blocks` should be current (https://github.com/Automattic/newspack-blocks/pull/663 should be merged in)
2. Create several public Newsletters.
3. Create a page, add Homepage Posts block. At the bottom of the block sidebar check Newsletters and uncheck Posts.
4. Observe recent Newsletters populate the block.
5. Publish, observe the same Newsletters appear in the front end.
> feat: add support for homepage posts block

- includes/class-newspack-newsletters.php
- src/components/send-button/index.js
Also: deprecate the custom taxonomy (migration strategy TBD). Also: allow Newsletters to be saved/updated after they've been sent, whether or not they've been set to be public.
Deprecates the custom taxonomies for the Newsletter CPT in favor of regular post categories and tags. This will make it easier to make newsletters appear in Homepage Posts blocks with the right settings, and will also allow public newsletters to appear in category and tag archives alongside regular posts.
Also fixes a tangentially related bug where once you've sent a newsletter and set it to be publicly visible, you could never change the option to make it non-public.
Closes #397.
1. Check out this branch and run `npm run build`.
2. In the WP admin dashboard, hover over the Newsletters menu item and confirm that …
> feat: make Newsletters use post categories + tags

- includes/class-newspack-newsletters-settings.php
For settings consumption by other plugins.
1. Visit the plugin settings, observe the values are displayed correctly
2. Update some of them, refresh the page, observe it working as expected
> Provide settings' values early

- includes/class-newspack-newsletters-settings.php
Adds a method to update settings (externally). 
1. Visit the settings page, observe all settings inputs are present, regardless of the chosen provider
2. Verify settings updating works as expected
> Add settings update method

- includes/class-newspack-newsletters-editor.php
- src/newsletter-editor/editor/index.js
Probably due to some Gutenberg changes, the color settings in the editor were updated later than it was expected. This PR changes it so the color palette is updated on every color settings change.
Closes #414.
1. Ensure you have custom colors set in theme options
2. Edit a newsletter, observe any block color settings are using the custom colors
3. Send a test email or the newsletter with some blocks colored w/ custom colors - observe the colors are applied
> Fix theme colors in editor

- includes/email-template.mjml.php
- src/newsletter-editor/editor/index.js
- src/newsletter-editor/editor/style.scss
Closes #409.
1. On `master`, create or edit a newsletter. Insert a heading block followed by a posts inserter block. Set some nice colors on the headings in the latter.
2. Observe that the block toolbar is not visible when the top block is selected
3. Send a test email - observe the headings in posts inserter are not colored (at least in Gmail web client)
4. Switch to this branch, observe both issues are resolved
> Fix: colors of headings with links; top block space in editor

- includes/class-newspack-newsletters.php
Adds support for revisions to Newsletter CPTs (not ads or layouts). Figured it would be useful since publishers tend to workshop newsletters like editorial content.
1. Check out this branch
2. Edit an existing newsletter, make some changes, and update. Refresh the page and confirm you see the Revisions sidebar panel and can review and select revisions.
3. Create a new newsletter, make some changes, save as a draft. Refresh the page and confirm you see the Revisions sidebar panel and can review and select revisions.
> feat: add revisions support for newsletter CPTs

- includes/class-newspack-newsletters-editor.php
- includes/class-newspack-newsletters.php
Adds support for featured images to Newsletter posts. If using a Newspack theme, also adds support for the featured image options from the theme, and respects the default featured image set for posts in Customizer.
Also includes a slight refactor of two redundant `pre_get_posts` filters which each affected category/tag archives and newsletter CPT archives in slightly different ways. Now there's just a single callback that handles both cases.
Closes #423.
1. In Customizer > Template Settings > Post Settings, update the "Featured Image Default Position" setting and publish.
2. Create a new newsletter or edit an existing one.
3. Expand the Featured Image panel and confirm that the option selected by default matches your Customizer selection.
4. Add a featured image and enable the "Make …
> feat: featured images and pre_get_posts refactor

- includes/class-newspack-newsletters-editor.php
- src/editor/blocks/posts-inserter/index.js
Filters the excerpt length server-side so that the length set in Posts Inserter block attributes can override the site's excerpt length.
Because Newsletters uses standard REST API endpoints and not custom endpoints, we need to hook into `rest_post_query` and `the_posts` hooks to know when to set and reset the excerpt length, respectively.
Should behave similarly to https://github.com/Automattic/newspack-blocks/pull/701.
Closes #424.
1. Create or edit a newsletter, add a Posts Inserter block.
2. Turn on the "Display post excerpt" option and set an excerpt length to something much longer than the default (55), such as `100`.
3. On `master`, observe that in the block preview and a sent test email, the excerpts shown in the block don't exceed 55 words even though the block attribute is set to …
> fix: respect excerpt length setting while not messing up site excerpts

- src/service-providers/constant_contact/ProviderSidebar.js
- src/service-providers/mailchimp/ProviderSidebar.js
- src/service-providers/mailchimp/index.js
Should avoid a mysterious error reported by a publisher that resulted in a hard editor crash:
```
TypeError: Cannot read property 'map' of undefined
at ProviderSidebar (webpack:///./src/service-providers/mailchimp/ProviderSidebar.js?:185:101)
at we (https://newspack.test/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:84:293)
at He (https://newspack.test/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:97:464)
at zj (https://newspack.test/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:228:406)
at Th (https://newspack.test/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:152:223)
at tj (https://newspack.test/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:152:152)
at Te (https://newspack.test/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:146: …
```
> fix: avoid potentially undefined nested property

- includes/class-newspack-newsletters-editor.php
- src/editor/blocks/posts-inserter/utils.js
https://github.com/Automattic/newspack-blocks/pull/725 broke the display of authors in the Posts Inserter block, exposing a dependency on the Newspack Blocks plugin. This PR gets author info in the Newsletters plugin so there's no dependency. Works both with and without Co-Authors Plus.
1. On `master` create or edit a newsletter draft and insert a Posts Inserter block.
2. In the block attributes, turn on the "Display author" option. Observe that the author bylines are not rendered in either the preview (both before and after clicking "Insert posts") or the sent email after sending yourself a test.
3. Check out this branch, run `npm run build`.
4. Refresh the newsletter. This time confirm that the author bylines are displayed with each post when the "Display author" option is on, both in …
> fix (posts inserter): display authors attribute

- includes/class-newspack-newsletters-renderer.php
- src/editor/blocks/posts-inserter/index.js
- src/editor/blocks/posts-inserter/query-controls.js
- src/editor/blocks/posts-inserter/utils.js
Some low-hanging fixes for various minor issues.
Column blocks with a `width` attribute were getting converted to MJML with an extra `%`, breaking their styling in the sent email. Fixes #432.
1. Insert two sets of Columns blocks into a newsletter. One should have columns with no set width, the other should have width values (such as 50%/50% or 33%/66%—the exact values don't matter).
2. On `master`, send yourself a test email. Confirm that the rendering of the second set of columns (with column widths set) is as described in #432.
3. Check out this branch, send another test.
4. Confirm that both sets of columns now render as expected, respecting the widths defined in block settings.
Closes #427.
1. Insert a Posts Inserter block in a newsletter. Confirm that there is no longer an "Order by" …
> fix: minor bugfixes

- includes/class-newspack-newsletters.php
Recent changes changed what is passed to the MJML-rendering method from a full WP Post to a post-like object. To be safe and ready for other integrations (#399) this PR ensures a full post is passed to the method.
This is a refactor, email processing should work as expected.
> Fix: use full post object in renderer

- .distignore
- includes/class-newspack-newsletters-editor.php
- includes/class-newspack-newsletters.php
- src/editor/blocks/index.js
- src/editor/blocks/posts-inserter/block.json
- src/editor/blocks/posts-inserter/index.js
- src/editor/blocks/posts-inserter/style.scss
- webpack.config.js
Closes #451 
1. Edit a newsletter, create a reusable block containing Posts Inserter
2. Edit the reusable block, observe the Posts Inserter is loading 
3. Ensure all blocks settings are carried over after being edited as the reusable block
> feat: register posts inserter block if editing a reusable block

- includes/class-newspack-newsletters.php
Closes #467 
Gravity Forms was injecting un-escaped scripts into the newsletter markup, breaking the JSON. Since newsletters don't need and can't have any scripts, this PR prevents Gravity Forms from injecting their scripts on newsletters.
1. Install and activate Gravityforms.
2. Save a draft newsletter. Observe "Update failed" message.
3. Activate this PR. Save a draft newsletter. Observe no "Update failed" message
> Prevent Gravity Forms scripts from being injected into newsletter markup

- includes/class-newspack-newsletters-ads.php
- includes/class-newspack-newsletters.php
Editor users currently have only partial access to the newsletters plugin. They can view newsletter posts, but they don't have access to the MJML renderer (so they can't send emails) and they can't see newsletter ads in the dashboard. This PR updates permissions to allow editors to fully edit newsletters, send test and live email campaigns, and view and edit newsletter ads. It still blocks access to the Newsletter Settings page, which seems like it was an intentional choice.
1. Log into a test site as an editor user (not admin).
2. Observe that in the dashboard, the "Newsletters" menu item only has the following submenu items: All Newsletters, Add New, Categories, Tags (no Ads or Settings)
3. Edit an existing newsletter post. Observe an error saying "You cannot use this resource" when you …
> fix: allow editor users to edit and send newsletters

- includes/class-newspack-newsletters-bulk-actions.php
- includes/class-newspack-newsletters-quick-edit.php
- includes/class-newspack-newsletters.php
- newspack-newsletters.php
- src/quick-edit/index.js
- webpack.config.js
Thir PR implements **bulk action** and **quick edit** options for modifying the public page option for a newsletter.
Closes #325.
1. Visit Newsletters list dashboard
2. Select multiple newsletters for bulk edit
3. Select "Make newsletters page public" from Bulk actions and apply
https://user-images.githubusercontent.com/820752/124185083-d9d9af80-da90-11eb-9cf2-cc7a5fa4f4f9.mov
1. Visit Newsletters list dashboard
2. Click `Quick Edit` option on a newsletter
3. Click on `Make newsletter page public?` checkbox
4. Click on Update
https://user-images.githubusercontent.com/820752/124185131-f1189d00-da90-11eb-869f-4b3e2a8b7648.mov
> Public newsletters – add bulk and quick edit option

- includes/class-newspack-newsletters-editor.php
- includes/service-providers/campaign_monitor/class-newspack-newsletters-campaign-monitor-controller.php
- includes/service-providers/class-newspack-newsletters-service-provider-controller.php
- includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact-controller.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp-controller.php
- src/newsletter-editor/index.js
- src/newsletter-editor/testing/index.js
Populate the field for email testing with the address(es) previously set by the user. If no email has been previously set, populates the field with the user email address.
Closes #156.
1. Write a newsletter
2. Send a test to a custom email address (or multiple comma-separated addresses)
3. Refresh the page or create a new newsletter and see that the emails have persisted
> Persist user defined test emails as user meta

- includes/class-newspack-newsletters-editor.php
Removes enqueued styles that does not exist since a3ce0cd0beeebff778af217988d05b6410e095bd.
> Fix: remove non-existent enqueued styles

- includes/class-newspack-newsletters-settings.php
- includes/class-newspack-newsletters.php
- src/components/copy-html/index.js
- src/components/copy-html/style.scss
- src/components/init-modal/screens/api-keys/index.js
- src/components/send-button/index.js
- src/components/send-button/style.scss
- src/newsletter-editor/editor/index.js
- src/newsletter-editor/index.js
- src/newsletter-editor/sidebar/index.js
- src/service-providers/constant_contact/ProviderSidebar.js
- src/service-providers/example/index.js
- src/service-providers/index.js
- src/service-providers/mailchimp/ProviderSidebar.js
- src/service-providers/manual/index.js
Implements "manual" provider to accommodate features from #470.
Although the issue mentions a "generic" provider approach, this PR interprets the required features as a manual approach, as it does not consist in new provider in its concept nor in our [ESP service interface](https://github.com/Automattic/newspack-newsletters/blob/master/includes/service-providers/interface-newspack-newsletters-esp-service.php). The manual option is available as a provider option for the user, which is interpreted in the editor to implement the necessary features.
The implemented features/changes in the editor are:
- Isolate the "preview text" input into `renderPreviewText` so it can be available outside of a provider sender context.
- Added HTML markup copy to clipboard in pre-send info modal.
- Added …
> Add "manual" provider for email markup copy

- includes/class-newspack-newsletters-editor.php
Changes `allowed_block_types` filter name to `allowed_block_types_all`, since the former is deprecated in WP 5.8.
1. With WP 5.8 and on `master` branch, obsere a PHP notice about `allowed_block_types` being deprecated on post editor
2. Switch to this branch, observe the notice is not shown
3. Switch to WP <5.8, ensure the blocks are still filtered on Newsletter editor, e.g. a Jetpack Mailchimp block can't be added
> fix: change allowed_block_types filter name

- src/editor/blocks/posts-inserter/query-controls.js
While selecting individual posts in the Posts Inserter block, the block would encounter a JS error and break, as identified in #493.
I identified the issue occurring only on 5.8. While searching for posts, the `FormTokenField` would eventually process an empty string, which was not properly handled by `decodePost`.
I was not able to identify the reason why an empty string is sent to `displayTransform`, but it does not seem to persist in the selected options or suggestions list.
This PR ensures that `displayTransform` always returns a string.
Closes #493.
1. Update to 5.8 RC3 with this plugin's master branch to identify the error
2. Make sure your installation have multiple posts to be inserted
3. Create newlestter with Posts Inserter block
4. Select "Display specific posts" and attempt to …
> fix(wp-5.8): ensure string for displayTransform

- includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
Execute `sync()` method instead of return error when `retrieve()` method is unable to identify an existing campaign id.
Warning: Although the change in Constant Contact provider follows the same logic as for Mailchimp, I was not able to test it due to #503.
Closes #499.
1. In `master` branch, create a newsletter draft using the Manual provider
2. Change your provider to Mailchimp with valid API keys
3. Edit the created draft and see the "no campaign ID" error.
4. Switch to this PR branch, repeat steps and see that no error is displayed and the newsletter is synchronized with the ESP.
Steps should also be executed using Constant Contact instead of Mailchimp.
> Fix: sync instead of erroring for missing campaign id

- includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
Fixes a sync error when syncing after changing service providers to a new ESP.
1. Install and activate the [v1.29.2-alpha.1](https://github.com/Automattic/newspack-newsletters/releases/tag/v1.29.2-alpha.1) built asset on a fresh site.
2. Go to **Newsletters > Settings** and set the provider to "manual".
3. Create a new newsletter draft and save.
4. Go back to Settings and set the provider to Mailchimp with a valid Mailchimp API key.
5. Edit the newsletter draft. Observe a fatal error:
```
[19-Jul-2021 21:45:39 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Newspack_Newsletters_Mailchimp::sync(), 0 passed in /srv/users/user44cb75cc/apps/user44cb75cc/public/wp-content/plugins/newspack-newsletters/includes/service-providers/mailchimp/class-newspack-newslette …
```
> fix: ensure post object for syncs

- includes/class-newspack-newsletters-editor.php
Since the 5.8 upgrade, newsletters and newsletter ads editor does not display the toolbar for text formatting (bold, italic, etc...).
This PR includes the "formatting" asset as an allowed asset in the newsletter and newsletter ad editor.
Closes #520.
1. In the master branch verify the missing toolbar (see #520 for reference).
2. Checkout this branch and verify that the toolbar is back.
> Fix: include format assets editor

- composer.json
- composer.lock
- includes/class-newspack-newsletters-settings.php
- includes/class-newspack-newsletters.php
- includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact-controller.php
- includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact-sdk.php
- includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
- newspack-newsletters.php
- src/components/init-modal/screens/api-keys/index.js
- src/newsletter-editor/index.js
- src/newsletter-editor/sidebar/index.js
- src/newsletter-editor/testing/index.js
- src/service-providers/constant_contact/ProviderSidebar.js
- src/service-providers/constant_contact/index.js
- src/service-providers/example/index.js
Implements our own [simplified SDK](https://github.com/Automattic/newspack-newsletters/blob/fix/refactor-constant-contact/includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact-sdk.php) to handle the [maintained v3 API](https://v3.developer.constantcontact.com/api_guide/index.html) with OAuth integration.
Instead of storing a generated access token, the API credentials now store API's `key` and `secret`, used to manage access and refresh tokens. After the first configuration with the app's credentials, the editor sidebar is replaced with an Authorization button, which will prompt the OAuth flow, update the tokens seamlessly for the user and synchronize the post with the provider.
I struggled a little bit to implement the ability to synchronize the …
> Fix: refactor constant contact provider

- composer.json
- composer.lock
- newspack-newsletters.php
Fixes a dependency bug that was only revealed by the production CI job. 
1. Check out this branch, delete the `vendor` folder.
2. Run `composer install --no-dev --no-scripts` to install PHP dependencies the same way CI does.
3. Run `npm run release:archive` and install on a fresh site. Verify that the plugin works as expected.
> fix: composer dependency bug

- readme.txt
Update readme to include Campaign Monitor as ESP.
> fix: add campaign monitor to readme

- src/editor/blocks/posts-inserter/block.json
- src/editor/blocks/posts-inserter/index.js
- src/editor/blocks/posts-inserter/utils.js
Subtitle as a displayable post meta on post inserter.
Closes #295.
1. Check out this branch and run `npm run build`
2. Create a new post with subtitle and another without
3. Create a newsletter with Post Inserter block
4. Make the Post Inserter block display 2 posts and enable **Post subtitle**
5. Observe the post subtitle being displayed accordingly without errors
6. Send a test email to confirm that its also displayed as expected
> feat: subtitle support for post inserter

- includes/class-newspack-newsletters-renderer.php
- tests/test-renderer.php
As seen on #484, different mail clients apply CSS rules differently. While in Chrome the global `a { color: inherit !important; }` gets overwritten by the element rule `style="color:#FFFFFF;"`, it is not the case for Safari (and Mac's Mail client).
This PR ensures user-defined colors are rendered on any browser/mail client and changes the default button radius to the default value on the Newspack theme.
Closes #484.
1. Change your provider to Manual
2. On the master branch create a newsletter with 2 different buttons:
1. with bright text and dark background
2. with dark text and bright background
3. Click on send, copy and save the resulting HTML.
4. Open the HTML file in different browsers (Chrome, Firefox, Edge, and Safari) and observe the consistency issue.
5. Checkout this branch, …
> fix: renderer button styling

- includes/class-newspack-newsletters-layouts.php
- includes/class-newspack-newsletters.php
- src/components/newsletter-preview/index.js
- src/newsletter-editor/layout/index.js
- src/newsletter-editor/styling/index.js
Implements custom CSS to layouts.
Closes #538.
1. In the master branch, create a newsletter with custom CSS and save it as a new layout
2. Create a newsletter with the saved layout and observe that it didn't save the custom CSS
3. Switch to this branch, run `npm run build`, repeat steps, and observe the custom CSS being saved and applied
> fix: add custom css to layouts

- .circleci/config.yml
- composer.json
After some investigation with @claudiulodro (see #552), this PR fixes the missing namespaced Guzzle from the autoload by running the custom prefix command outside of the autoload dump event.
1. Check out this PR, `run rm -r vendor; rm -r vendor_prefixed/*`, then run `composer install --no-dev --no-scripts && composer prefix-guzzle && composer dump-autoload`, then run `cat vendor/composer/autoload_classmap.php`. You should see the Guzzle classes in the classmap.
> fix: unbind prefix command from composer dump event

- includes/class-newspack-newsletters.php
- src/newsletter-editor/sidebar/index.js
- src/service-providers/mailchimp/ProviderSidebar.js
Fixes a bug.
1. On `master`, create a new newsletter using Mailchimp as the ESP
2. Input something into to "From" name and email, but don't click "Update Sender"
3. Update the newsletter - set or change the target group or save draft
4. Observe the "From" inputs are cleared
5. Switch to this branch and rebuild, observe the inputs are not cleared after an update
> fix: prevent sender data overwrite on updates

- includes/class-newspack-newsletters-settings.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp-controller.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
- src/service-providers/mailchimp/ProviderSidebar.js
- src/service-providers/mailchimp/index.js
- src/service-providers/mailchimp/style.scss
- src/service-providers/mailchimp/utils.js
This PRs proposes a change on how we support segmentation with the Mailchimp provider. Currently, we have support for selecting a group and multiple tags. The tags implementation also included saved segments, although not supported due to the segmentation options for `saved` segments being different for `static` segments (tags).
The redesign fixes the segmentation support and proposes a simpler approach, similar to how Mailchimp's wizard works, in which you are able to select one of the available groups, tags, or segments. For what we generally propose in terms of form complexity, this approach avoids scenarios in which the user would select a group and different segments that don't match existing recipients.
It also removes the `Use Mailchimp tags` field. It looks like an unnecessary …
> Refactor Mailchimp recipients and segmentation options

- package-lock.json
- package.json
The update of the CI image for the `build` task from `circleci/php:7.2-node-browsers` to `circleci/php:7.4-node-browsers` requires an update to the `stylelint-config-wordpress`.
The `node-sass` dependency version from the current version of this package is not compatible with the recently updated build image.
1. On the master branch, run `circleci local execute --job build` and observe the error
2. Switch to this branch, run `npm ci` and `circleci local execute --job build` and observe that the task succeeds
> fix: update stylelint version

- src/editor/blocks/posts-inserter/block.json
- src/editor/blocks/posts-inserter/index.js
- src/editor/blocks/posts-inserter/utils.js
Fix the text and headings font-size update and set the default styles to empty so it follows the newsletter standard or the custom CSS.
Closes #566.
1. In the master branch, create a newsletter with the Posts Inserter block
2. Attempt to modify the font size of the text and observe it doesn't change
3. Switch to this branch, run `npm run build` observe that you are able to modify the font size
1. Still in this branch, create a newsletter and paste the following custom CSS to it: `h3 { color: #f00; font-size: 30px; }`
2. Insert a Posts Inserter block and observe the posts titles reflect the custom CSS
> fix: post inserter default styles

- includes/class-newspack-newsletters-editor.php
- includes/class-newspack-newsletters-embed.php
- includes/class-newspack-newsletters-renderer.php
- includes/email-template-mjml.css
- newspack-newsletters.php
- src/editor/blocks/embed/index.js
- src/editor/blocks/embed/style.scss
- src/editor/index.js
- tests/test-renderer.php
Add support for the embed block. There are 4 types of embeddable content, as [specified on oEmbed](https://oembed.com/). For each available type we'll have the following behavior:
Displays thumbnail with caption, which is the video title by default or the inline caption manually inserted. If no thumbnail is provided by the service, attempts to create a link with the title or caption.
Displays image with caption, which is the image title by default or the inline caption manually inserted.
Validates HTML content, allowing `blockquote`, `p`, `a`, `br`, `em` and `strong`. If no valid HTML is returned after filtering, a link is generated with the resource title.
Examples are:
- Twitter: returns a `blockquote`, which renders nicely
- Amazon: returns an `iframe`, which becomes a link with the …
> feat: add support for embed

- includes/class-newspack-newsletters.php
Handle errors for ESP lists are not available, either due to the `self::$provider` not being set or using manual newsletters.
1. In the master branch, set your Newsletters configuration to Manual
2. Visit the Reader Revenue wizard and Stripe Settings
3. Observe the error message on the Newsletters lists section
4. Switch to this branch, refresh the page and observe the new error message
> fix: handle unavailable lists

- includes/class-newspack-newsletters.php
A bugfix. 
Closes #510 
1. On `master`, set up Mailchimp as ESP (with API key) and observe that setting the ESP to "Manual" is not possible - value is reverted to Mailchimp 
2. Switch to this branch, observe a change from Mailchimp to Manual is possible
> fix: manual provider setting

- includes/class-newspack-newsletters-editor.php
The `core/social-links` block requires an unlisted inner block called `core/social-link` that must be allowed for the block to function properly.
Closes #595.
1. On the master branch, edit a newsletter and attempt to create Social Links
2. Observe that the appender element is not visible and you are not able to add links
3. Check out this branch, refresh the page and observe the block is now working as expected
> fix: allow social-link inner block

- .circleci/config.yml
As seen on https://github.com/Automattic/newspack-ads/pull/214 and ab2f8926765ff6216bf87ef7be15ddad9159d7c2, this PR changes the circle ci tasks PHP images from `circleci` to `cimg`.
CI tasks must pass.
> chore: fix circleci build

- src/newsletter-editor/index.js
- src/newsletter-editor/styling/index.js
- src/newsletter-editor/styling/style.scss
Instead of having the styles hidden in all the different sidebar settings, I moved the styling to its own sidebar, kind of similar to "Global Styles".
1. Create/Edit a Newsletter
2. Notice the Styling panel somewhere in the sidebar
3. Switch to this branch and refresh the editor
4. Now the styles are behind the `styles` icon at the top
5. Check if the settings are still working
> Move styling settings to its own sidebar

- includes/class-newspack-newsletters-editor.php
- src/service-providers/index.js
The localized data should be printed before the `newspack-newsletters-editor`, and not `newspack-newsletters-newsletter-editor`. The current implementation does not allow the service provider to be detected for the Mailchimp merge tags custom filters.
1. On the master branch using the Mailchimp as service provider, edit a newsletter
2. Start a new paragraph block and observe the `*|` autocompleter is not available
3. Check out this branch, run `npm run build` and refresh the editor
4. Confirm the `*|` autocompleter is now working for paragraph blocks
> fix: editor script data

- includes/class-newspack-newsletters-renderer.php
- includes/email-template-mjml.css
- src/editor/style.scss
- tests/test-renderer.php
* Small tweak to the vertical rhythm to follow an 8px baseline.
* Simplify separator block to only a thin 1px line irregardless of the block style
* Update button font-weight and padding
1. Create a newsletter and send yourself a preview
2. Compare the editor with the email you've just received
3. Switch to this branch and refresh the editor
4. Send yourself another preview
5. Check the email against the editor
> Update vertical rhythm and various blocks to match sent email

- src/components/init-modal/screens/layout-picker/SingleLayoutPreview.js
- src/components/init-modal/screens/layout-picker/index.js
- src/components/init-modal/style.scss
- src/components/newsletter-preview/index.js
- src/components/newsletter-preview/style.scss
- src/editor/blocks/posts-inserter/index.js
- src/editor/blocks/posts-inserter/posts-preview.js
- src/newsletter-editor/layout/index.js
- src/newsletter-editor/styling/index.js
This PR implements the required hooks to apply a newsletter layout custom CSS to the Post Inserter block previews. It fixes the display for layout preview and newsletter editing.
Closes #687 
1. Make sure you have WordPress 5.9 RC 2 installed
2. While on the master branch, create a newsletter layout with custom fonts and a Posts Inserter block
3. Click to create a new newsletter, choose the created layout and observe the Posts Inserter block does not apply the selected fonts
4. Check out this branch, run `npm run build` and refresh the page
5. Observe the fonts are now applied
6. Select the layout to enter the newsletter editor and observe the fonts are also applied
7. Repeat the steps above in WordPress 5.8 to make sure there are no regressions
> fix: append layout preview css to iframe head

- src/editor/blocks/posts-inserter/index.js
- src/editor/blocks/posts-inserter/posts-preview.js
Fix the rule of hooks infringement by placing the `useCustomFontsInIframe` hook in the top-level component `PostsPreview`.
Make sure you are able to create the Post Inserter block and click on "Insert Posts" in instances using WordPress 5.8 and 5.9 RC2.
> fix(post-inserter): preview ref hook on top level component

- includes/class-newspack-newsletters-renderer.php
Fixes a PHP warning triggered by the new "Layout" attribute in WP 5.9, that results from MJML trying to convert an array attribute value to a string.
1. Test on a site running WP 5.9.
2. On `master`, create a new newsletter and add a block with the Layout attribute (such as Buttons or Social Icons—both are part of the default newsletter layouts, so you can easily test with one of those).
3. Save the newsletter and observe a PHP error on save:
```
PHP Notice:  Array to string conversion in /Users/dkoo/Local Sites/newspack/app/public/wp-content/plugins/newspack-newsletters/includes/class-newspack-newsletters-renderer.php on line 61
```
4. Check out this branch and save again. Confirm that the warning no longer appears and that the `newspack_email_html` meta value is saved with MJML markup …
> fix: php warning when converting non-string attributes to mjml

- includes/class-newspack-newsletters-settings.php
This PR adds some more keys to the settings: onboarding, help, helpURL and placeholder. It also adds proper sanitisation.
1. Switch to this branch and update `newspack-plugin` to https://github.com/Automattic/newspack-plugin/pull/1449
2. Test the Setup Wizard Services `/wp-admin/admin.php?page=newspack-setup-wizard#/services` 
3. Same with Engagmement `/wp-admin/admin.php?page=newspack-engagement-wizard#/newsletters`
4. Check Newsletter > Settings
> Add new keys to settings list

- package-lock.json
- package.json
Resolves a build issue.
`newspack-scripts` uses PostCSS v8, but an indirect dependency must be setting it to a lower version. Requiring v8 explicitly resolves a build issue.
1. On `master`, try to build (`npm run build`)
2. Observe it logging warnings about PostCSS usage
3. Switch to this branch, build again, observe building without issues
> fix: require postcss explicitly

- src/components/init-modal/index.js
- src/components/init-modal/screens/api-keys/index.js
- src/components/init-modal/screens/layout-picker/SingleLayoutPreview.js
- src/components/init-modal/screens/layout-picker/index.js
- src/components/init-modal/style.scss
- src/newsletter-editor/editor/style.scss
- src/newsletter-editor/layout/index.js
- src/newsletter-editor/testing/index.js
This PR redesigns the `Modal` on init and removes the big preview area to focus on the layouts instead.
2. Remove all the Newsletter settings so you can also see the 1st step
3. Create a new newsletter
> Update init modal design

- src/components/init-modal/style.scss
- src/editor/blocks/posts-inserter/index.js
- src/editor/blocks/posts-inserter/posts-preview.js
- src/editor/blocks/posts-inserter/style.scss
- src/newsletter-editor/layout/style.scss
This PR adds a bit more consistency with the Post Inserter iframe preview.
Fixes #695
1. Create a new newsletter
2. Add the post inserter block
3. Switch between the different featured image positions
> Fix iframe styles for post inserter

- src/editor/index.js
Removes duotone filters for every block on newsletters. They are not supported and shouldn't be displayed as an option.
1. Check out this branch and create a new newsletter with an image block
2. Confirm the duotone filter is not available on the block toolbar
3. Edit a regular post with an image block, confirm the duotone filter continues to work as expected
> fix: remove duotone filters

- includes/class-newspack-newsletters-editor.php
This PR removes the Patterns shipped with WP.
They don't work well with Newsletters and we should avoid displaying stuff that can break the editor 🙂
For some reason I couldn't make `remove_theme_support( 'core-block-patterns' );` work (open to suggestion here!) so instead I'm making sure I'm not loading the [Pattern Directory](https://wordpress.org/patterns/) and I removed the extra block pattern that was still there (`'core/social-links-shared-background-color'`)
2. Create a newsletter and check the patterns (you shouldn't see any)
3. Create a new post/page/cpt-of-your-choice and check if the patterns are available (they should be!)
> Remove wp-bundled block patterns

- includes/class-newspack-newsletters-editor.php
#731 unregisters a block pattern by name, but the `unregister_block_pattern` function doesn't gracefully handle an argument for a pattern that isn't already registered and will throw a PHP warning in that case. This change checks whether the block pattern is actually registered before attempting to unregister.
I'm not 100% sure under what conditions the block pattern is or isn't registered. It's just a warning, so it shouldn't cause any issues, but it might cause a lot of noise in debug logs.
1. On `master`, visit the Newsletters post list in WP admin.
2. Observe a PHP warning being thrown:
```
[10-Feb-2022 23:20:38 UTC] PHP Notice:  WP_Block_Patterns_Registry::unregister was called <strong>incorrectly</strong>. Pattern "core/social-links-shared-background-color" not found. Please see <a …
```
> fix: php warning when unregistering a block pattern that isn't registered

- includes/class-newspack-newsletters-editor.php
- src/newsletter-editor/editor/index.js
- src/newsletter-editor/editor/style.scss
- src/newsletter-editor/sidebar/index.js
- src/service-providers/campaign_monitor/ProviderSidebar.js
- src/service-providers/constant_contact/ProviderSidebar.js
- src/service-providers/example/index.js
- src/service-providers/mailchimp/ProviderSidebar.js
- src/service-providers/manual/index.js
Inspired by pcD9cT-I4-p2, this PR completely removes the "Subject" field from the sidebar and instead reintroduces the standard Post Title in the editor, just slightly restyled.
2. Edit the subject
3. Send newsletter and check if subject is correct
> feat: remove subject input (title) from the sidebar

- includes/class-newspack-newsletters-renderer.php
Support image's `figcaption` to have the following inline tags:
- s      
- b      
- strong 
- i      
- em     
- mark   
- u      
- small  
- sub    
- sup    
- a
Closes #744.
1. Create a new newsletter with an image block
2. Add a caption with link, bold and italic
3. On the master branch, confirm the sent newsletter (or rendered markup) breaks the caption text on the first inner tag occurrence
4. Check out this branch and confirm the markup now contains the allowed tags
> fix: support for image caption inner html

- CHANGELOG.md
- newspack-newsletters.php
- package-lock.json
- package.json
Pulls changes in from `release` after the [last post-release job failed](https://app.circleci.com/pipelines/github/Automattic/newspack-newsletters/1868/workflows/0965a957-e015-470d-b23a-9c84e9bd51e1/jobs/4568).
> fix: bad post-release merge

- includes/class-newspack-newsletters-editor.php
- includes/class-newspack-newsletters-renderer.php
- includes/email-template.mjml.php
The email editor strips all default editor styles, this also removes the `.has-{color-name}-color` used by the "Highlight" (`<mark />`) attribute used for inline coloring of texts.
1. While on the master branch, create a new newsletter and apply "highlight" to a selected text
2. Observe the background color works as expected but not the text color (background color uses inline CSS rules)
3. Check out this branch, apply the highlight text color and observe the changes are applied
4. Send the newsletter with a highlighted text and confirm it is also highlighted on the sent email
> fix: color palette css rules

- src/components/with-api-handler/index.js
- src/editor/api/index.js
- src/newsletter-editor/editor/index.js
[Email content larger than 102kb gets clipped by Gmail](https://mailchimp.com/pt-br/help/gmail-is-clipping-my-email/). This PR implements a notice to let the user know their content may get clipped if we detect a resulting body larger than 100,000 bytes. This approximation is assuming that the ESP will add extra tags for tracking, footer, etc.
It also implements the minifying options to MJML to reduce the chance of clipping. My local tests produced a reduction of 25% of an email with ~100k bytes.
1. Check out this PR and run `npm run build`
2. Send an email using multiple different blocks to make sure the markup is not altered by the minification
3. Add multiple text blocks in a newsletter draft until it reaches > 100k bytes
4. Save the draft and confirm you see the notice in the …
> feat: minify and notify clipable email body

- src/editor/index.js
[As pointed out](https://github.com/Automattic/newspack-newsletters/pull/764#pullrequestreview-916140528) by @dkoo, the "Row" block, which is a Group block variation, is not supported by our renderer. Instead of a row, the result is a regular group.
This PR unregisters the block variation.
1. While on the master branch, send a newsletter using the "Row" block
2. Confirm the unexpected layout
3. Check out this branch and confirm you are no longer able to use the "Row" block
4.
> fix: disable row group block variation

- includes/class-newspack-newsletters-editor.php
- src/newsletter-editor/editor/index.js
- src/newsletter-editor/editor/style.scss
- src/newsletter-editor/sidebar/index.js
- src/service-providers/campaign_monitor/ProviderSidebar.js
- src/service-providers/constant_contact/ProviderSidebar.js
- src/service-providers/example/index.js
- src/service-providers/mailchimp/ProviderSidebar.js
- src/service-providers/manual/index.js
This PR is basically reverting #735. There's a bug in WP 5.9  and it also confused our publishers.
1. Create new Newsletter
3. Edit subject
> fix: move subject back to the sidebar

- src/editor/blocks/visibility-attribute/index.js
- src/editor/blocks/visibility-attribute/style.scss
This PR simplifies the `ToolbarDropdownMenu` of the Visibility option.
* Remove the use of icons (except for the "check")
* Display the all the options if the Newsletter is public (default: "Email and Web")
2. Enable Newsletter Public
3. Play with visibility settings
4. Also check if you disable Newsletter Public, the settings stay
> Simplify visibility option

- src/components/init-modal/screens/layout-picker/index.js
`savePost()` is intended to be called after the selection of the layout ID but instead it's assuming the `editPost()` action will be fulfilled after 1 ms, which is not good practice.
This PR updates the `savePost()` action to be executed as a callback to the `setNewsletterMeta()`.
Confirm layout selection and draft saving behaves as expected and the selected layout is saved (the layout picker is not displayed again after refreshing the editor).
> fix(layouts): ensure selected layout is saved

- src/editor/blocks/visibility-attribute/style.scss
When setting the visibility to a block that has some sort of float/alignment, the outline will look broken
E.g.
This PR clears the floating element and adjust the min-height so that the first line of a sentence is readable.
1. Add a right align text and set its visibility to something other than newsletter and web
2. Notice the outline above the text -- it should be wrapped around it
3. Switch to this branch
4. Refresh your editor
> Fix height of block visibility when using floats

- src/newsletter-editor/layout/index.js
Ensures the `usedLayout` data contains the proper layout ID after a layout update.
Closes #794 
1. On the master branch, create a new layout based on a newsletter
2. Edit the newsletter and click to update the layout a couple of times
3. You may get a 404 error or a duplicate layout being created (I've experienced both and couldn't pinpoint why the different side-effects from an `undefined` ID)
4. If you don't get a 404 error on the console, create a new newsletter and confirm there are duplicate saved layouts
5. Check out this branch, repeat the step 2 and confirm there are no errors or duplicate layouts created
6. Create a new newsletter based on the saved layout and confirm the changes are saved
> fix: ensure layout update has ID

- includes/class-newspack-newsletters.php
- includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
- includes/service-providers/campaign_monitor/class-newspack-newsletters-campaign-monitor.php
- includes/service-providers/class-newspack-newsletters-service-provider.php
- includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
- includes/service-providers/interface-newspack-newsletters-wp-hookable.php
- includes/service-providers/letterhead/class-newspack-newsletters-letterhead.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
- src/components/send-button/index.js
- src/editor/api/index.js
- src/newsletter-editor/editor/index.js
This PR refactors how the plugin handles sending Newsletters on status changes by moving the hook to the abstract class, avoiding duplicate logic for improved readability and maintenance. It also simplifies each provider's `send()` method to only perform the send action and return `true|WP_Error`  to be handled by the `send_newsletter()` abstract class method.
The hook was changed from `post_status_changes` to `pre_post_update` so it can prevent the status change in case of a failed send. The current method requires a `wp_update_post()` to revert the post back to draft, which is not ideal.
The new `pre_post_update()` hooked method also verifies if a sent newsletter is changing status after being sent and prevents such action - unless it's changing to/from trash, which it should always …
> refactor: sending newsletters on status changes

- src/editor/api/index.js
#754 introduced a couple of bugs to the API middleware for handling MJML updates:
1. A logic error caused #816, not allowing other post meta - outside of newsletters meta - to be updated.
2. Using only `NEWSLETTER_CPT_SLUG` to filter out requests from the middleware breaks the support for Reader Revenue emails and other CPTs that may use the editor
This PR fixes the logic issue and ensures that requests from any of the `mjmlHandlingPostTypes` go through the middleware:
https://github.com/Automattic/newspack-newsletters/blob/0c349a4942a03efabb2acef0da7f36c9e3b83769/src/editor/api/index.js#L44-L47
It also refactors to exit early for better readability and to follow the standard practice across the plugin. It also removes promises to consolidate the use of async/await.
Closes #816
1. On the …
> fix: api middleware execution logic

- includes/class-newspack-newsletters-editor.php
Enable CoAuthors Plus functionality by allowing Co-Authors Plus editor assets to be enqueued on the newsletter editor.
Closes #805 
1. Instal Co-Authors Plus, add a new guest author, check out this branch and create a new newsletter draft
2. Confirm you see the Co-Authors Plus settings on the editor sidebar
3. Add the guest author and save the draft
4. Refresh the editor and confirm the guest author is saved
> fix: allow Co-Authors Plus assets on editor

- CHANGELOG.md
- includes/class-newspack-newsletters.php
- includes/service-providers/class-newspack-newsletters-service-provider.php
- newspack-newsletters.php
- package-lock.json
- package.json
- src/components/send-button/index.js
- src/service-providers/constant_contact/index.js
- src/service-providers/mailchimp/index.js
The refactor from #798 was missing the integration with scheduled posts. WP scheduling uses `wp_publish_post()`, which does not fire `pre_post_update` or any other hook before updating the database 😢 
This requires us to use a hook after the post is published (`transition_post_status`) to handle sending scheduled newsletters.
This PR implements that case and also updates some phrasing on the UI. The sending confirmation modal for scheduled newsletters should state "Schedule newsletter" instead of "Send".
The error handling of scheduled newsletters should later be adjusted, along with the other error transients, to have a better UI integration. Currently it only serves to allow the failed send to return to draft after publishing. It should properly display the error message regardless of …
> fix: sending scheduled newsletters

- includes/service-providers/class-newspack-newsletters-service-provider.php
The release auto-merge has a very aggressive rule and overwrites `master` code. This PR restores some code removed from [the latest hotfix merge](https://github.com/Automattic/newspack-newsletters/commit/3ebe7dfea2602f98068319d67f879b3d97451f2d#diff-746392f50a90cb7179a3928b87ef9cc9d8062f62480df31e02293ad5527dc1f3).
> chore: restore code overwritten by release merge

- CHANGELOG.md
- includes/class-newspack-newsletters.php
- includes/service-providers/class-newspack-newsletters-service-provider.php
- newspack-newsletters.php
- package-lock.json
- package.json
Sending scheduled newsletters is still not working appropriately due to how we approach the `is_newsletter_sent()` method. For legacy reasons, it has to assume that `publish` newsletters are sent. By the time `send_newsletter()` checks that on scheduled newsletters, WP scheduling has already called `wp_publish_post()`, so our check method will assume the newsletter is sent and bail.
This PR implements a lock mechanism through a disposable meta, just to guarantee that the scheduled sending window goes through the legacy check.
Repeat steps from #831 and confirm the newsletter is sent from the ESP dashboard.
> fix: ensure scheduled newsletter is sent through a lock meta

- includes/service-providers/class-newspack-newsletters-service-provider.php
The recently implemented hotfix for scheduled newsletters is being executed for all posts. This PR ensures to only execute for newsletters.
1. Schedule a regular post and confirm it publishes at the appropriate time
2. Schedule a new newsletter send and confirm it sends at the appropriate time
3. Confirm on your ESP dashboard that the post is not stored as a newsletter draft and the scheduled newsletter is sent
> fix: ensure scheduled sending only fires for newsletters

- includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
- includes/service-providers/campaign_monitor/class-newspack-newsletters-campaign-monitor.php
- includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
- includes/service-providers/interface-newspack-newsletters-esp-service.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
Use a common error message for newsletters without a subject. Such cases usually display an error thrown from the ESP. We can avoid a confusing message by providing our own intelligible notice.
Closes #851.
1. Check out this branch and setup keys for Mailchimp, ActiveCampaign, and Campaign Monitor (Constant Contact is currently unsupported due to #802)
2. Using each provider, start a new newsletter draft, erase the subject and attempt to send
3. Confirm you see the message as shown above on the screenshot
> fix: validate newsletter subject

- includes/class-newspack-newsletters-renderer.php
Fixes the rendered separator block.
| Master | This branch |
| --- | --- |
| <img width="648" alt="image" src="https://user-images.githubusercontent.com/820752/172248433-87b37575-d72d-4ef6-b0d0-8100a44145cd.png"> | <img width="629" alt="image" src="https://user-images.githubusercontent.com/820752/172251091-ffa8b7c2-2d78-413e-acd3-ac53e5fe1bae.png"> |
Closes #838 
1. Check out this branch and create a new newsletter with 2 separator blocks
2. To the first, apply a color from the palette and set it to "wide"
3. The second, apply a custom color from the picker
4. Send the email and confirm they are rendered as expected
> fix: separator background rendering

- includes/class-newspack-newsletters-layouts.php
- includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
Removes a reminiscent action hook that generates errors editing posts when ActiveCampaign is selected as ESP.
ea36fa763f386c32235577ab2e0eea209c85ab0a also fixes a warning introduced by #796, which created layouts without titles.
1. With debug mode on, select AC as your ESP
2. Confirm the errors displayed while creating any post
3. Check out this branch and confirm the errors are gone
> fix: remove reminiscent action hook

- includes/class-newspack-newsletters-layouts.php
- includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign-controller.php
- includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
- src/service-providers/active_campaign/ProviderSidebar.js
- src/service-providers/active_campaign/index.js
Implements support for sending newsletters to Active Campaign's segments.
Active Campaign currently supports APIs v1 and v3 and to implement this feature we must use both versions. v1 does not have a method for fetching existing segments whereas v3 does not have a method to create campaigns. To handle that in an organized manner, `api_v1_request()` and `api_v3_request()` methods were implemented.
This ESP has campaigns and messages, a campaign can hold multiple messages and choose which message to send on the scheduling/sending action of the campaign. The current sync action creates a message and a campaign, attaching the message to the campaign. This is problematic because neither API (v1 or v3) has an endpoint for editing a campaign. Once a sync occurs with a specific target (sender and …
> feat: active campaign segments support

- includes/class-newspack-newsletters.php
Restores the expected behavior of newsletter display in archives.
Closes #863.
1. Send a newsletter with a category and marked as public
2. In the master branch, visit the category page and confirm the newsletter is not visible
3. Check out this branch and confirm the newsletter is visible
4. Send a newsletter with a category and private
5. visit the category page and confirm the newsletter is not visible
6. Navigate through other archive pages (date, search, post type archives) and confirm the expected posts are displayed
> fix: display newsletters in archives

- includes/class-newspack-newsletters-blocks.php
- includes/class-newspack-newsletters-editor.php
- includes/class-newspack-newsletters-settings.php
- includes/class-newspack-newsletters-subscribe.php
- includes/class-newspack-newsletters-subscription.php
- includes/class-newspack-newsletters.php
- includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
- includes/service-providers/campaign_monitor/class-newspack-newsletters-campaign-monitor.php
- includes/service-providers/interface-newspack-newsletters-esp-service.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
- newspack-newsletters.php
- src/blocks/index.js
- src/blocks/subscribe/block.json
- src/blocks/subscribe/edit.js
- src/blocks/subscribe/editor.scss
- src/blocks/subscribe/index.js
- src/blocks/subscribe/index.php
- src/blocks/subscribe/style.scss
- src/blocks/subscribe/view.js
- webpack.config.js
Implements subscription lists management and ESP-agnostic subscription block. It currently supports Campaign Monitor, Mailchimp, and ActiveCampaign. Constant Contact is currently unavailable due to #802.
Once a provider is selected, the existing lists become available to configure as subscription lists with a custom title and description:
Once the subscription lists are configured by an admin, an editor can use the **Newsletters Subscription Block** to configure one or multiple lists to subscribe to.
Closes #430
Closes #636 
1. Check out this branch and https://github.com/Automattic/newspack-plugin/pull/1734
2. Visit the Engagement wizard, select a provider you have multiple lists and save
3. Confirm the "Subscription Lists" section is updated once the config is saved
4. Enable, apply …
> feat: subscription lists and subscription block

- src/blocks/subscribe/index.php
Pre-filling of email input of the Subscribe block, if an email is available. 
cc @miguelpeixe in case that was something you had planned :) 
1. Insert a Subscribe block
2. As a logged in user, observe the email address is pre-filled
3. In a new session, use the Reader Registration block from the Newspack plugin to pre-authenticated as an existing reader
4. Observe the email is pre-filled, despite user not being logged in
> feat(subscribe-block): prefill email input

- includes/class-newspack-newsletters-subscription.php
- includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
- includes/service-providers/class-newspack-newsletters-service-provider.php
- includes/service-providers/interface-newspack-newsletters-esp-service.php
- src/subscriptions/index.js
- src/subscriptions/style.scss
- webpack.config.js
Implements email verification for subscription management through WooCommerce's "My Account" page.
For reviewing purposes, this PR implements subscription management only for ActiveCampaign at the moment. Other ESPs should follow.
Partial of https://github.com/Automattic/newspack-plugin/issues/1743
1. Make sure you have WC installed and active, a way to intercept WP's sent emails, and ActiveCampaign as your ESP
2. Visit the "Engagement" wizard and make sure you have at least one subscription list enabled
3. Visit "My Account" page and click on "Newsletters"
4. Confirm you see a button to confirm your email
5. Click on the button and confirm you receive an email with a link
6. Click on the link and confirm the success message and the list of subscription lists to toggle
7. Toggle the lists …
> feat: email verification and subscription management

- includes/class-newspack-newsletters-subscription.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
Enables signalling that the contact should be upserted without any change in list selection. Before, the list selection was an empty array by default, implicitly meaning that the upserted contact should not be subscribed to any list in the absence of this parameter. 
With this change, when an empty array of lists is supplied, it means the contact is unsubscribed from any lists. When a `false` value of the list ids parameter means that the contact has no change in lists selection.
_Follow instructions in https://github.com/Automattic/newspack-plugin/pull/1816_
> feat: enable contact adding w/out lists, as opposed to w/ empty lists

- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
Implement the management of Mailchimp list subscription
Partial of https://github.com/Automattic/newspack-plugin/issues/1743
1. Make sure you have Mailchimp as your ESP configured with multiple subscription lists
2. With WooCommerce installed, visit the "My Account" -> Newsletters page
3. Verify your email if required (intercept the sent link)
4. Subscribe and unsubscribe to the lists and confirm:
1. The contact is created if not yet available
2. Unsubscribing does not delete the contact, it changes the contact status instead
3. Subscribing an unsubscribed contact will modify its status
> feat: manage mailchimp subscription

- includes/class-newspack-newsletters-subscription.php
This PR introduces filters for `add_contact()` lists and a few fixes:
- The contact data filter should have `$contact` as initial argument, otherwise it'll be replaced with the provider name when no filters are applied
- The logger was producing a warning for attempting to `implode()` a `$lists` set to `false`
Closes #896 
Instructions at https://github.com/Automattic/newspack-plugin/pull/1818
> feat: filter contact lists and small fixes

- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
Fixes a bug. `PATCH` will only update, but `PUT` [will update or create](https://mailchimp.com/developer/marketing/api/list-merges/).
1. Set up MC w/ two audiences
2. Using Reader Activation, register and subscribe to both lists
3. On `master`, the reader will be subscribed to only the first list, on this branch to both
> fix: updating a list member

- includes/class-newspack-newsletters-subscription.php
Adds existing subsriber data for hooks triggered in `add_contact`. 
_Testing steps in https://github.com/Automattic/newspack-plugin/pull/1828_
> feat: pass existing contact data to the add_contact hooks

- includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
Because arguments are passed as URL parameters in ActiveCampaign's API, email addresses need to be passed through `urlencode` before they hit the API.
1. On a site connected to ActiveCampaign, subscribe via the Register or Subscribe blocks with an email address containing a `+` character.
2. On `master`, go to My Account and update your newsletter preferences. Observe an error message: `You selected a list that does not allow duplicates. The email <email address> is in the system already, please edit that contact instead.`.
3. Check out this branch and repeat step 2. Confirm that you're able to update list subscriptions as expected.
> fix: urlencode email addresses passed as URL params to ActiveCampaign API

- includes/class-newspack-newsletters-subscription.php
#909 implemented passing contact data to `add_contact` hooks, but detailed data will be needed for https://github.com/Automattic/newspack-plugin/pull/1840
_Follow instructions in https://github.com/Automattic/newspack-plugin/pull/1840 when it's ready, or just do a smoke test._
> feat: return all contact data for the add_contact hooks

- includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
Implement proper data type for date fields
In order to test it, I created a new custom field called `NP_Test Date` to not disrupt the current sandbox. Existing fields cannot have their type changed, so we'll need to delete them in order to implement the new format.
1. Checkout this branch and https://github.com/Automattic/newspack-plugin/pull/1855
2. Either create a new dummy field at https://github.com/Automattic/newspack-plugin/pull/1855 or delete the existing fields so they can be recreated
3. Make an anonymous donation with Stripe
4. Confirm the created contact has the proper date values for `NP_Registration Date`, `NP_Last Payment Date`, `NP_Next Payment Date`
5. Edit the value and confirm it triggers a date picker with calendar
> fix(active-campaign): format date fields

- .prettierrc
- package-lock.json
- package.json
- src/blocks/subscribe/editor.scss
- src/components/init-modal/style.scss
- src/editor/blocks/mailchimp-merge-tags/style.scss
- src/editor/blocks/posts-inserter/index.js
- src/editor/blocks/posts-inserter/style.scss
- src/editor/blocks/visibility-attribute/style.scss
- src/editor/style.scss
- src/newsletter-editor/editor/index.js
- src/newsletter-editor/layout/style.scss
- src/newsletter-editor/sidebar/style.scss
- src/newsletter-editor/styling/style.scss
Similar to https://github.com/Automattic/newspack-theme/pull/1845 and https://github.com/Automattic/newspack-blocks/pull/1174, updates prettier, stylelint and Newspack scripts to the latest versions:
* `newspack-scripts@4.3.0` was installed
* `wp-prettier` (aliased to prettier) was updated
* styles were migrated with `npx sass-migrator module src/**/*.scss`
* styles were fixed with `npm run lint:scss -- --fix`
* JS was fixed with `npm run lint:js -- --fix`
For the formatting, I gave all the colours coming from `~@wordpress/base-styles/colors` the prefix `wp-colors` rather than the default `colors`, to go with how this was handled in the [Newspack Plugin](https://github.com/Automattic/newspack-plugin/pull/1713). Unlike the main Newspack plugin, this plugin doesn't include and Sass colour …
> chore(deps): update newspack-scripts, prettier

- includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
Ensure that adding a contact to a list makes them subscribed to it on ActiveCampaign.
Closes #923
1. With reader activation and AC as your ESP, register a new account subscribed to all newsletters
2. Visit "My Account -> Newsletters" and unsubscribe to all newsletters
3. Log out and use the same email subscribing to all newsletters on a Registration Block
4. Sign in with the magic link you've received and confirm you're resubscribed to all newsletters
> fix(activecampaign): resubscribe on adding contact

- includes/class-newspack-newsletters-subscription.php
Uses new methods established in https://github.com/Automattic/newspack-plugin/pull/1880 to set the from email address and name for transactional emails (for this plugin, just the verification emails).
Since the standalone verification flow is locked when Reader Activation is active, this probably won't have any major effects, but it's just for completion's sake and/or in case we decide to handle the Newsletters area of My Account separately in the future.
1. Check out https://github.com/Automattic/newspack-plugin/pull/1880 and this branch.
2. With Reader Activation features active, register a new email address and sign up for at least one newsletter.
3. Temporarily disable Reader Activation features (otherwise you can't access the standalone verification flow in this plugin).
4. Go to My …
> feat: use Reader Activation custom sender info for verification emails

- src/blocks/subscribe/index.php
- src/blocks/subscribe/style.scss
- src/blocks/subscribe/view.js
Similar to https://github.com/Automattic/newspack-plugin/pull/1896, implements a honeypot trap field for the Subscribe block's form. This is implemented fully in this plugin so that it has no dependencies on the main plugin.
1. Check out this branch. Confirm that the Subscribe block looks and functions as normal.
2. Temporarily comment out or delete [this SCSS block](https://github.com/Automattic/newspack-newsletters/pull/932/files#diff-bb09ed8cb7e0f6604c1d72c36e6bfb866010cc2e5d8dc319c3c1c8238af7e6f3R58-R69) to unhide the honeypot field.
3. Refresh the Subscribe block and confirm there's a new email input field alongside the usual one.
4. Rebusmit the form, this time filling out both email inputs, and confirm that the form resolves with a success message.
5. Confirm that no subscription …
> feat: honeypot field for Subscribe block form

- includes/class-newspack-newsletters.php
Although it is standard for the main query to have the `post_type` set as an array, a hook may change it to a string ( `'post'`, instead of `array( 'post' )`)
This PR ensures that a string `post_type` is transformed to array before adding the newsletters post type to it.
Public newsletters should continue to be displayed in archives.
> fix: ensure main query post type is an array

- includes/class-newspack-newsletters-subscription.php
- includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
Implements contact deletion methods for ActiveCampaign and Mailchimp and delete on reader deletion according to the config.
Further details and testing instructions at https://github.com/Automattic/newspack-plugin/pull/1884
> feat: delete contact on reader account deletion

- src/blocks/subscribe/style.scss
Makes the submit button for the Subscribe block form the same #d33 red color as default CTA buttons in the Newspack theme.
1. Check out this branch.
2. Confirm the button color (static and hover/focus) for the Subscribe block form.
> style: red button for Subscribe block form

- src/blocks/subscribe/index.php
- src/blocks/subscribe/style.scss
- src/blocks/subscribe/view.js
Adds reCAPTCHA to Subscribe form submissions as implemented in https://github.com/Automattic/newspack-plugin/pull/1910, if available.
Also fixes a bug from #932 where the honeypot field is prefilled with an email address if one is known, which causes the form to always trigger the honeypot trap.
See testing instructions in https://github.com/Automattic/newspack-plugin/pull/1910.
> feat: handle reCAPTCHA on Subscribe form

- src/blocks/subscribe/style.scss
- src/blocks/subscribe/view.js
Adds mobile-friendly styles, front-end form validation, and fixes a small reCAPTCHA-related bug with the Subscribe form.
View the Subscribe block and confirm that it looks good in both mobile and larger viewports. New mobile styles should look as follows:
Try to submit the Subscribe block form without entering an email address and confirm that you get an error message stating "Please enter a vaild email address".
Currently, we generate a reCAPTCHA token and append it to the form as a hidden field each time the form is submitted. This means if the form submission fails for whatever reason, a new field will be added for each submission attempt. This PR fixes things so that a maximum of one reCAPTCHA token field will be created, and its value simply updated for each submission attempt.
1. On …
> fix: tweak Subscribe form styles and behavior

- includes/class-newspack-newsletters.php
It's been two months since `Newspack_Newsletters::add_contact` method has bee marked for deprecation, in favour of `Newspack_Newsletters_Subscription::add_contact`. This PR removes the deprecated method, so there's no confusion. Our code does not use the deprecated method anywhere.
> chore: remove deprecated add_contact method of Newspack_Newsletters

- src/blocks/subscribe/index.php
This gives each subscribe form a unique ID that can be picked up by Google Analytics to identify the form while firing submission events. Required for https://github.com/Automattic/newspack-popups/pull/951.
Instructions in https://github.com/Automattic/newspack-popups/pull/951.
> feat: give each subscribe form a unique ID

- includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
- src/blocks/subscribe/style.scss
Two small issues:
- removing horizontal overflow on the Subscribe block (caused by the honeypot field)
- handling errors when fetching AC's data
1. Insert a Subscribe block as the single element on a page
2. Notice that on `master`, it overflows horizontally, causing side-scroll
3. Verify that it does not on this branch
4. The AC errors are hard to reproduce, must've been a network error when I've encountered them. A smoke check will suffice.
> Subscribe block's horizontal scroll; AC errors

- src/blocks/subscribe/style.scss
Fixes a minor style bug in the Subscribe block for large viewports.
1. On `master`, observe that the "Subscribe" button is slightly misaligned at large viewports in both editor and front-end:
2. Check out this branch, confirm that it looks properly aligned at all viewports in editor and front-end.
> style: fix vertical misalignment of submit button

- includes/class-newspack-newsletters-subscription.php
- includes/service-providers/campaign_monitor/class-newspack-newsletters-campaign-monitor.php
- includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
- includes/service-providers/interface-newspack-newsletters-esp-service.php
- includes/service-providers/letterhead/class-newspack-newsletters-letterhead.php
Reader Activation introduces adding contact w/out lists. This PR ensures this is handled gracefully by all ESPs.
1. Enable Reader Activation
2. Set the ESP to Constanct Contact 
3. On `master`, observe the post-donation webhook callback errors out, if it won't pass a list ID to `add_contact`
4. Observe it handled gracefully on this branch
> fix: adding contact w/out lists handling

- composer.json
- composer.lock
- phpunit.xml.dist
- tests/bootstrap.php
This PR updates our phpunit tests dependencies to allow us to run them against the latest version of WordPress
> test: update tests dependencies

- includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact-sdk.php
- includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
This PR fixes the OAuth2 API integration and improves error handling. The refresh token is now optional because the request for an access token wasn't always returning a refresh token value.
Closes #802.
You might have to update your app to the new OAuth2 API, follow instructions from this page: https://developer.constantcontact.com/api_guide/auth_update_apps.html
On the app settings, change the redirect URI to: `https://yoursite.com/wp-admin/index.php?cc_oauth2=1`
1. Check out this branch and connect to a valid and reviewed* Constant Contact account
2. Create a draft newsletter and attempt to send a test email
3. If you have a free account, you might see the error message: "Constant Contact: Your current plan does not allow the use of Test Send."
4. If you have access to the test email …
> fix(constant-contact): update api for oauth2

- src/editor/blocks/posts-inserter/block.json
- src/editor/blocks/posts-inserter/index.js
- src/editor/blocks/posts-inserter/query-controls.js
Add post type selection to the Post Inserter block.
Closes #843
1. Check out this branch and start a newsletter draft with the "Post Inserter" block
2. Edit the block and confirm you see the post type dropdown as pictured above
3. Select a custom post type and confirm the posts are updated
4. Toggle "Display specific posts"
5. Search for content inside the selected post type and confirm it works as expected
6. Insert the posts and confirm they are rendered correctly
> feat(post-inserter): post type selection

- .circleci/config.yml
- composer.json
- composer.lock
- tests/test-controlled-statuses.php
- tests/test-renderer.php
This upgrades the tests so they can run both on php 7.4 and 8.
To test it, load the repo in a php 8 environment and run composer install. the run ./vendor/bin/phpunit
Do the same thing on a php 7.4 environment, but run composer update instead of install. (Discard the changes to composer.lock afterwards)
> test: Upgrade to php 8

- src/blocks/subscribe/edit.js
- src/blocks/subscribe/editor.scss
- src/blocks/subscribe/index.php
- src/blocks/subscribe/style.scss
Make sure the Reader Registration block and the Newsletter Subscription Form block share the same design.
1. Add to a page a Reader Registration block and a Newsletter Subscription Form block (to compare)
2. Publish
3. Notice how different they look
4. Switch to this branch
5. Refresh page
> feat: update subscribe block design to match reader registration

- src/blocks/subscribe/block.json
- src/blocks/subscribe/edit.js
- src/blocks/subscribe/editor.scss
- src/blocks/subscribe/index.php
- src/blocks/subscribe/style.scss
Implements name fields options for the subscription block:
Stacked inputs on mobile:
This PR also adjusts the form elements styling for a more consistent responsive grid using flexboxes and `gap` for spacing.
Closes #983
1. Check out this branch and confirm you're connected to a Mailchimp or ActiveCampaign account
2. Draft a "Newsletter Subscription Form" block
3. Confirm you see the new block options
4. Save with the default options (without name field), subscribe and confirm the contact is stored
5. Toggle the name field, apply a custom placeholder, and save
6. Visit the page and confirm the custom placeholder is rendered
7. Subscribe using the block and confirm the name is stored in the contact
8. Toggle the last name field, apply a custom placeholder and save
9. Visit the page and …
> feat: name fields options for the subscription block

- includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact-sdk.php
- includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
Implements the required API in order to make Constant Contact available for the Subscription Block.
Closes #982
1. Check out this branch and confirm you are using a valid Constant Contact account
2. Visit Engagement -> Newsletters and confirm you are able to enable and configure the ESP's subscription lists
3. Enable a couple of lists to continue testing
4. Render the "Newsletter Subscription Form" block on a page and subscribe a new email to one list
5. Confirm the email is subscribed to the list and with the `current_page_url` custom field
6. Subscribe the same email address again, but this time select the other list
7. Confirm the contact is updated and subscribed to **both*** lists
* The subscription block is not subscription management, so it'll never unsubscribe someone from a list
> feat: constant contact support for the subscription block

- includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign-controller.php
- includes/service-providers/campaign_monitor/class-newspack-newsletters-campaign-monitor-controller.php
- includes/service-providers/class-newspack-newsletters-service-provider-controller.php
- includes/service-providers/class-newspack-newsletters-service-provider.php
- includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact-controller.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp-controller.php
The default status code for REST API responses when returning a `WP_Error` is `500`. This in combination with the [PWA](https://wordpress.org/plugins/pwa/) plugin triggers the service worker's cached template, which is HTML content instead of the standard JSON response.
The returned HTML is not parseable, resulting in the error seen in #964.
This error is intermittent because it only occurs if the PWA's service worker is installed and active, which is most of the time.
This PR updates the error response of API requests to change the status to `400`, ensuring that the SW cached template doesn't take over.
Closes #964
1. Make sure you have [PWA](https://wordpress.org/plugins/pwa/) plugin installed
2. Setup Newsletters with ActiveCampaign
3. Modify line `167` of …
> fix: standardize api error status code

- includes/class-newspack-newsletters-editor.php
- includes/class-newspack-newsletters-renderer.php
- tests/test-controlled-statuses.php
- tests/test-renderer.php
WP 6.1 introduced the concept of sortable list items. This, however, broke our MJML renderer's implementation of lists, causing them to not be rendered at all in the final email HTML. The fact that list items are now inner blocks of List blocks also means that we need to whitelist `core/list-item` as an allowed block in the Newsletter editor, or it's not possible to add list items to any list.
1. On a site with WP 6.1, on `master`, create a newsletter containing two List blocks: one bulleted and the other numbered. Try to add some list items and observe that you can't.
2. Check out this branch and refresh the editor. Confirm that you can now add list items to each List block.
3. Send a test email. Confirm that the lists are rendered as expected.
> fix: lists and list item blocks in WP 6.1

- includes/class-subscription-lists.php
- includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
- includes/service-providers/campaign_monitor/class-newspack-newsletters-campaign-monitor.php
- includes/service-providers/class-newspack-newsletters-service-provider.php
- includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
- newspack-newsletters.php
- tests/test-labels.php
This PR adds new attributes to the providers classes
* labels that will be used in the UI
* a flag indicating whether the provider supports Tag
It also adds a condition and only loads the Lists CPT if the provider is set and support tags.
1. Make sure tests pass
2. Configure Constant Contact as a provider
3. Confirm that the Newsletters > Lists submenu is not added
4. Try to access `wp-admin/edit.php?post_type=newspack_nl_list` and make sure you get the "Invalid post type" message
5. Configure Mailchimp or Active Campaing as a provider
6. Confirm you now see and are able to use the Newsletters > Lists post type
> Tags support/add provider attributes

- includes/class-newspack-newsletters-renderer.php
Fixes missing nested list items and Quote blocks from rendered emails. Asana reference: `/0/1200550061930446/1203326737036715`
1. Add a Quote block and a List block and then indent some of the list items like so:
2. On `master`, send a test email and observe that the Quote block and the nested list items are dropped.
3. On this branch, send another test and confirm that all items are rendered.
> fix: nested list items and quote blocks in email

- includes/class-subscription-list.php
- includes/class-subscription-lists.php
- includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
- includes/service-providers/class-newspack-newsletters-service-provider.php
- includes/service-providers/interface-newspack-newsletters-esp-service.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
- tests/test-subscription-list.php
This PR changes how we are dealing with tags in the ESPs and linking them to our local Subscription Lists
* Create abstract method to make sure all providers implement the support tags in the same way
* Create methods to create tags, get tags id and others
* Save the ESP's tag ID as metadata to the Subscription List.
First, let's test the new methods.
* Configure both Mailchimp and Active Campaign with valid credentials
* Open their dashboards
* Go to `wp shell` and test the methods below (test it with both providers):
```PHP
$tag_name = 'Test tag';
$list_id = null; // required only for Mailchimp
$contact_email = 'test@test.com'; // The email of an existing contact
$provider = Newspack_Newsletters_Mailchimp::instance();
// $provider = Newspack_Newsletters_Active_Campaign::instance(); …
```
> Tags support: use tag ids

- includes/class-newspack-newsletters-subscription.php
- includes/class-subscription-list.php
- includes/class-subscription-lists.php
- includes/service-providers/class-newspack-newsletters-service-provider.php
- tests/bootstrap.php
- tests/test-subscription-list.php
- tests/test-subscription-lists.php
- tests/trait-lists-setup.php
This PR depends on #1028
This PR adds the local Subscription Lists to the UI where admins can choose the enabled Lists, can place them as options for readers to sign up to, and will correctly add readers to the correspondent list and tag.
What is not done yet?
* We want to disable the option to edit the list title and details when you activate them and add a link to the custom post type instead
* The manage Newsletters page in "My Account" is not yet done
1. Create one or two local Subscription Lists
2. Enable them in the Newsletter Settings page
3. Add registration blocks to your site and enable the local list as options to subscribe to
4. As a reader, register/subscribe to newsletters
5. Confirm that the reader was added to the expected lists/tags in the provider dashboard
6. Test all …
> Tags support integrate local lists

- src/editor/blocks/posts-inserter/block.json
Fixes the attribute types for all font-size related attributes in Posts Inserter blocks, and adds the missing `displayAuthor` attribute to the block.json manifest. In both cases the mismatched attribute type/value and the missing attribute prevented those attributes' values from being saved.
Also adds the missing `preventDeduplication` to the block.json manifest, but this isn't currently exposed as an editable option so this shouldn't affect functionality. See /0/1200550061930446/1203451612303419/ for more details.
Closes /0/1200550061930446/1203452267509212.
1. On `master`, create a newsletter and add a Posts Inserter block.
2. Change the values for "Display author", and the font sizes under "Text style", "Heading style", and "Subtitle style" panels.
3. Save the post and refresh. Observe …
> fix: attribute types in posts inserter block.json

- includes/class-newspack-newsletters-settings.php
- includes/class-newspack-newsletters-subscription.php
- includes/class-subscription-list.php
Disables the edit of title and description from the list where we select the active Subscription Lists.
Since they are created locally, there is no need to edit the title and description again. Instead of allowing edits, link to the edit page.
1.Set up Mailchimp or AC as provider
2. Go to Newsletters > Lists and create a couple of lists
3. Go to Newsletters > Settings
4. Go to the "Subscription Lists" section
5. Make sure the Local lists are marked as such and you can't edit their title and description
6. Make sure the edit links points to the righ place
7. Make sure you are still able to enable/disable them
8. And make sure they are still working in the rest of the application (registration form, etc)
> Disable local lists edits from selection

- css/subscription-list-editor.css
- includes/class-subscription-lists.php
- includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
In Active Campaign, we can't send a campaign for users based on a tag, we need to create a Segment for it.
But unfortunately AC APIs (v1 and v3) do not offer a way to programatically create segments. Therefore, we need to tell users they will have to manually create a Segment for each Local Subscription List they create.
This PR adds a small notice in the metabox
1. Set Active Campaign as your provider
2. Go to Newsletters > Lists and create a new list
3. Confirm that you don't see any notice in the metabox until you save the list
5. After you save the list, confirm the notice is there
6. Check for typos and if the link works
8. Suggestions on the copy?
9. Go to Newsletters > Lists, confirm that the tags are properly displayed in the list
> feat: notice that we cant create segments

- includes/class-newspack-newsletters-settings.php
- includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
- includes/service-providers/campaign_monitor/class-newspack-newsletters-campaign-monitor.php
- includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact-sdk.php
- includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
This PR is a part of #1023 and fixes an issue with the provider's refresh token.
To obtain a refresh token - so the access token can be seamlessly updated - the API is missing an `offline_access` scope.  The OAuth flow is improved so that it can also be performed on the plugin's settings page:
1. Set your ESP to Constant Contact with valid API credentials
2. Make sure to delete these WP options: `newspack_newsletters_constant_contact_api_access_token`, `newspack_newsletters_constant_contact_api_refresh_token`
3. Visit the plugin's settings page
4. Confirm you see the notice on top of the form
5. Click to Authorize and go through with the flow (it may authorize automatically if the app was already previously authorized)
6. Confirm the page is refreshed and the subscription lists are …
> feat(constant-contact): improved oauth flow

- includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact-controller.php
- includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact-sdk.php
- includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
- src/service-providers/constant_contact/ProviderSidebar.js
- src/service-providers/constant_contact/style.scss
Allow users to send Newsletters to Segments using Constant Contact provider
1. Set Constant Contact as the provider with proper credentials
2. Create a new Newsletter
3. Verify the UI on the Sidebar Newsletter settings where you select the option to "SEND TO"
4. If you select one or more Lists, the Segments Select should be emptied
5. If you select one Segment, the Lists should all be unchecked
6. Play with these changes and verify that the Campaign in the Constant Contact dashboard is being updated with the correct values
7. Change the value on the CC dashboard and refresh the editor. Verify that the new values are correctly set up
> Allow constant contact to send to segments

- includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
Temporarily disables the tags based lists feature while we discuss if the approach is correct.
Closes # .
1. Set Mailchimp or Active Campaign as providers
2. Make sure there is no "Lists" submenu under the Newsletters menu in the admin panel
> fix: disable tag based lists

- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp-cached-data.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
- newspack-newsletters.php
Closes 1203536997639429-as-1203697115315826 .
This PR adds a cache layer to the mailchimp provider to improve the performance of the editor.
It caches Segments, Groups and Merge fileds when the `retrieve` method is called to retrieve a campaign. Since this method is called every time you make a change to a Newsletter, the editor gets very slow especially if you have too many segments or groups.
Why not simply caching the return of the api call for a certain amount of time? What's all this?
It's a tricky situation. We can't cache this information for too long, because users can make changes directly in the MC dashboard and we want to reflect them asap.
On the other hand, if we cached this for just a couple of minutes, in practice the user will experience a slow editor every time, because …
> feat: add caching to mailchimp

- includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
Closes #1068 
1. Make sure you have ActiveCampaign configured
2. Add `$existing_fields = [];` to line `994` of `includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php` so it attempts to create the fields
3. Subscribe with a new email using the subscription block
4. If it's a completely new AC account, subscribe again with another email so it attempts to create the fields again
5. Confirm you see the error and are unable to subscribe because it tried to create fields that already exist (duplicate `perstag`)
> fix(activecampaign): handle error on field creation

- src/editor/api/index.js
This PR ensures the width of images so it doesn't default to 100%.
The default behavior for Gutenberg (and browser rendering in general) for images without a determined width is to use the image's native width.
This is not the case for MJML. The `mj-image` element defaults the `width` attribute to the parent's width in pixels. This creates unwanted behavior and breaks the WYSIWYG aspect of the editor.
| Rendered email | Editor |
| --- | --- |
| <img width="779" alt="image" src="https://user-images.githubusercontent.com/820752/215809071-14751294-924b-4331-a57f-e90e792a9bcc.png"> | <img width="835" alt="image" src="https://user-images.githubusercontent.com/820752/215809155-19d213bf-8adc-496b-b8c3-144838f84f92.png"> |
1. While on the master branch, draft a newsletter and add an image with …
> fix: ensure images width are preserved

- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp-cached-data.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp-controller.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
- src/service-providers/mailchimp/ProviderSidebar.js
This PR introduces support for Mailchimp folders. The editor should be able to select a folder for campaigns:
1. Make sure you have Mailchimp configured as your ESP
2. Make sure you have configured folders on your MC dashboard
3. Draft a new newsletter, select a folder and save the draft
4. Visit your Mailchimp dashboard and confirm the draft is in the selected folder
> feat(mailchimp): support folder selection

- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp-groups.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
- newspack-newsletters.php
This PR adds all the methods to allow the Mailchimp service provider to manipulate groups. In the next PR, we will use it to make Mailchimp create Groups instead of Tags for local subscription lists.
We are going to manually test each method added by this PR
Start with a site with the Mailchimp credentials set, and 'mailchimp' selected as the provider in Newsletters > Settings
Go to your Mailchimp dashboard: Go to Audience Dashboard. Click on "Manage Audience > Manage Contacts" on the dropdown at the top right corner of the page. Scroll down and click on "Groups". We are going to check the groups being created here in this page.
1. Open a wp shell `wp shell`
2. Get a new instance of the provider class: `$mc = Newspack_Newsletters_Mailchimp::instance();`
3. Now we need to get the ID of …
> feat: add groups support to mailchimp

- includes/class-subscription-list.php
- includes/class-subscription-lists.php
- includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
- includes/service-providers/class-newspack-newsletters-service-provider.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp-groups.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
Re-enables the tag based Lists (local lists) for Active Campaign and Mailchimp.
For mailchimp, make it work with Groups instead of Tags.
1. Set your ESP as Mailchimp
2. Create a couple of Local lists in Newsletter > Lists
3. Register as a new user to your site
4. Subscribe to a newsletter
5. In Mailchimp dashboard, confirm that the "Newspack Newsletter" Group category was created (a new column in the all contacts list)
6. In Mailchimp dashboard, confirm the user was created with the expected Group
7. Go to My Account > Newsletters
8. Confirm that the page correctly shows the newsletters you have subscribed to
9. Check and uncheck different newsletters and save
10. Confirm that every time the correct Groups are applied to the contact on Mailchimp and the checkboxes are properly updated
11. …
> feat: enable local lists and mailchimp groups

- src/blocks/subscribe/index.php
Add support to Popups events in the Data Events api
See https://github.com/Automattic/newspack-plugin/pull/2291
> feat: add support to campaigns data event listeners

- includes/class-subscription-lists.php
Opens the Newsletter menu and mark "Lists" as the current item when editing a List
1. Go to Newsletters > Lists
2. Verify that the Newsletter top menu level is open and that "Lists" is the current active menu item
3. Add a new List or edit an existing one
4. Verify that the Newsletter top menu level is open and that "Lists" is the current active menu item
> fix: make Lists CPT menu item a sub-item of Newsletters CPT menu item

- includes/class-newspack-newsletters-renderer.php
Jetpack's Photon transforms images to webp, which is not supported by some email clients. This PR implements a filter to skip Photon processing while rendering the newsletter body.
1. Make sure your instance has Jetpack and Photon enabled
2. While on master, draft a newsletter with an image and confirm the generated source has `i0.wp.com` images
3. Check out this branch and confirm the images are now from your domain
4. Visit the home page and confirm the images are still coming from `i0.wp.com` (not affecting other places)
> fix: disable JP Photon for newsletters

- includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
- includes/service-providers/class-newspack-newsletters-service-provider.php
- includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact-sdk.php
- includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
- includes/service-providers/interface-newspack-newsletters-esp-service.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
Adds support to Tags for the Constant Contact provider. This will enable the new Lists feature for this provider.
1. Set Constant Contact as the provider with proper credentials
2. Go to Newsletter > Lists
3. Create a new list
4. Confirm that a correspondent tag is created in the provider
5. Go to Newsletter > Settings and enable the list in the Subsctiption Lists section
6. Add a registration or Newsletter subscription block to your site with that list as an option
7. As a visitor, register to a newsletter selecting that list
8. confirm the contact is created with the correct tag in the provider
9. confirm also that a Segment was created with users tagged with this tag
10. (Note: Constant Contact is not supported in the "My account" page for managing subscriptions, this is unrelated with …
> Add tags support to Constant Contact

- includes/class-subscription-lists.php
When a Local list is deleted, it still shows up as an option in the Subscription Block. This PR fixes it
Confirm the bug
1. Create a couple of local lists
2. Go to Newsletters > Settings an enable them
3. On a new tab, create a page and insert the Newsletter Subscription Block
4. Check that in the block options you see the Local lists as options
5. Go to Newsletters > Lists and delete/trash one of the lists
6. Go back to the page, add the Subscription block again and see that the deleted list is still there
Checkout this PR and repeat the process. Confirm that the list is no longer there in step 6
> fix: remove list from settings when deleted

- includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
Fixes a typo that is causing an error when $field_res is a WP_Error.
```
[02-Mar-2023 00:17:28 UTC] PHP Warning:  Undefined variable $fields_res in /newspack-repos/newspack-newsletters/includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php on line 1004
[02-Mar-2023 00:17:28 UTC] PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in /newspack-repos/newspack-newsletters/includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php:1015
```
1. check the code
> fix: typo causing fatal errors

- includes/class-newspack-newsletters-settings.php
Closes #1100 .
1. Create a custom local list adding a description
2. Go to Newsletter > Settings
3. enable the list and click Save changes
4. Add a subscription block to a page
5. confirm the list description shows up
> fix: local list description being deleted

- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
- src/components/with-api-handler/index.js
Very often, error messages are not displayed when trying to set Newsletter sender or sending Test emails.
This is a little hard to test because I've seen this happening intermittently.
My best guess was that it was a race condition that sometimes would not display the error notice because of a uncaught error.
The error was being thrown because all consumers of the `apiFetchWithErrorHandling` call it without a `.catch()` callback. When it rejects the error, the error is not caught and we see it on the console.
I have removed the `reject` call from it. Since I understand that the expectation is that this method will handle the errors, I thought this was acceptable. Otherwise, we would have to add a `.catch()` callback to all the places where this method is invoked.
I'm not sure it fixes the …
> Fix and improve error messages

- includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
Fixes an incorrect param order for `str_contains` which is causing custom ActiveCampaign metadata fields to be created with the wrong type in the connected ESP.
1. On a site connected to ActiveCampaign and with RAS enabled, dheck out this branch, go to **Newspack > Engagement > Reader Activation** and set the **Metadata field prefix** field to a custom prefix so that new fields will be created.
2. On the front-end, make a recurring donation.
3. In the ActiveCampaign dashboard, go to **Contacts > Fields** and confirm that new fields were created with your custom prefix, and that the following field types were all created with a field type of "Date" (note that the end date might not be created until you cancel the subscription):
- 'Registration Date'
- 'Last Payment Date'
- 'Next Payment …
> fix: date field types for custom ESP metadata fields

- src/editor/style.scss
This PR fixes the styles of the newsletter title so the select header font is applied.
| Before | After |
| --- | --- |
| <img width="568" alt="image" src="https://user-images.githubusercontent.com/820752/225947582-dea4d811-57f3-4288-a6af-83331c8232f0.png"> | <img width="607" alt="image" src="https://user-images.githubusercontent.com/820752/225947478-ee2d582c-e68e-489d-b5d9-4ab273480717.png"> |
1. Check out this branch and draft a new newletter
2. Mark the newsletter as public so the title shows up in the editor
3. In the "Newsletter Styles", change the "Headings Font" option
4. Confirm the selection is applied to the newsletter title
> fix: editor title with selected header font

- src/blocks/subscribe/block.json
Changes the default button label.
Note that this PR will also change the label of existing blocks that didn't customize their buttons.
See 1200550061930446-as-1204189922401733
1. Add a newsletter subscription block
2. Make sure the default button label is "Sign up"
> feat: Change the default button label to Sign up

- src/editor/blocks/posts-inserter/index.js
- src/editor/blocks/posts-inserter/style.scss
This PR fixes the styling of the Posts Inserter block preview for WP 6.2.
The use of flexbox is only applied when loading, so the spinner can be properly centered.
1. While on master and with WP 6.2, draft a new newsletter with Posts Inserter 
2. Confirm the cut-off and incorrectly aligned content
3. Check out this branch, refresh the editor
4. Confirm it's styled as expected and the spinner is also properly centered
5. Repeat the steps on the latest stable version (6.1.1) and confirm it also renders as expected
> fix(posts-inserter): preview styles for WP 6.2

- src/blocks/subscribe/block.json
- src/blocks/subscribe/edit.js
- src/blocks/subscribe/index.php
- src/blocks/subscribe/style.scss
- src/blocks/subscribe/view.js
Adds an optional field to block attributes to customize the success message.
Closes `1204166503564710/1204261432690203`.
1. Add a Subscription Form block to a post or page.
2. In the block sidebar, confirm there's a new field containing the previously hard-coded message as a default (note that the default is changed "thank you for signing up" instead of "subscribing", for consistency with the default button label as changed in #1125):
3. Edit the default message to something else and save.
4. On the front-end submit an email address to the form. Confirm that your custom success message is displayed in WP green upon success.
> feat: add customizable success message

- src/blocks/subscribe/view.js
This PR changes the Newsletter Subscription Form block js initialization to use `domReady` instead of `window.onload`.
No visible changes should take place. The block should continue to work with XHR instead of form submission.
> fix(subscription-block): use domReady for initializing block js

- includes/class-newspack-newsletters.php
Ensure the hook to display newsletters in archives only applies to the archives it belongs (categories and tags).
The overwrite of empty `post_type` can mess with how custom taxonomies and custom post types interact.
Closes #637
Make sure #637 is no longer reproducible and public newsletters are still shown in categories/tags archives.
> fix: only add newsletters to categories and tags archives queries

- includes/class-newspack-newsletters-editor.php
- src/editor/style.scss
Restricts the custom font sizes to the newsletters' editor only, preventing this definition to mess with theme definitions in other places.
Some Gutenberg behavior is also not allowing the newsletters' editor to have a consistent font size experience. Small and Large font sizes are applied as expected due to an `!important` flag in their rules, which is not applied to normal, medium, and x large. Although not ideal, 27de7726c7be9c139f5ffaa1e6006199fd3a432f enforces the font sizes for the editor across all options.
Closes #755
1. Check out this branch, edit a post with different font size definitions and confirm the choices are consistent between the editor and page
2. Draft a new newsletter and confirm the font sizes are as defined in pixels (12, 16, 24 and 36)
> fix: restrict custom editor font sizes

- includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
Avoids a fatal error when Constant Contact settings is incomplete
1. On master, start with a site configured for Constant Contact
2. Go to Newsletters > Settings. Delete the "Constant Contact API Key" and save
3. Confirm you see a Fatal error
4. Checkout this branch and confirm the settings page is usable again
> fix: avoid fatal error on Constant Contact

- includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
Small tweak to AC's `get_all_contact_fields()` method so it doesn't cause a fatal error if the fetch returns a `WP_Error`. Makes sure to return the error instead of attempting to `array_merge()` it.
No visible change should take place
1. With your site connected to AC, open your site shell
2. Instantiate the provider class in the shell:  `$provider = new Newspack_Newsletters_Active_Campaign();`
3. Fetch an existing contact and confirm there's no error: `$contact = $provider->get_contact_data( 'existing@email.com' );`
> fix(activecampaign): prevent fatal error when fetching contact fields

- includes/class-subscription-lists.php
After https://github.com/Automattic/newspack-newsletters/pull/1156 the metabox in the creation of a Subscription List is showing groups as well as Audiences. Only Audiences should be displayed there.
1. In `master` set up a site with Mailchimp and make sure Mailchimp account have some groups
2. Go to Newspack > Settings and make sure you see Audiences and groups there
3. Click to "Add new" Subscription List
4. Confirm that in the Select box in the metabox, under "Audience:" you see all Audiences and groups
5. Checkout this PR
6. Confirm that now you only see Audiences there
7. Confirm that this also still works with other provider
> fix: display only Audiences in list metabox

- includes/class-newspack-newsletters-blocks.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
- src/blocks/subscribe/block.json
- src/blocks/subscribe/edit.js
- src/blocks/subscribe/index.php
Implements Mailchimp's double opt-in support in the Newsletters Subscription Form block.
Also implements an improvement to the `add_contact` logic to prevent the same execution from adding the contact twice. This can happen with RAS's optimistic way of updating ESP data. It doesn't communicate well with Mailchimp's double opt-in because the API handles a "pending" contact differently. For that reason, we need to prevent this double run.
1. Check out this branch and make sure you have a Mailchimp setup
2. Add a Newsletters Subscription Form block to a page and confirm you see the new panel as above
3. Without checking the box, save the page
4. Visit the page and subscribe a new email to multiple lists
5. Confirm in Mailchimp's dashboard that the contact is subscribed to all lists
6. Edit …
> feat(mailchimp): support double opt-in subscription

- includes/class-newspack-newsletters-editor.php
- includes/class-newspack-newsletters-renderer.php
- includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
- includes/service-providers/campaign_monitor/class-newspack-newsletters-campaign-monitor.php
- includes/service-providers/class-newspack-newsletters-service-provider.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
- src/editor/blocks/conditional-content/index.js
- src/editor/blocks/conditional-content/style.scss
- src/editor/index.js
Implements custom attributes to support conditional content from ESP-provided tags.
1. Check out this branch and setup a Mailchimp connection
2. Start a new blank newsletter and add a paragraph
3. Confirm the new panel for settings conditional content attributes with Mailchimp-related instructions
4. To a segment, add a contact with "First Name" and another without (you must have access to both mailboxes or use `+` to send to the same gmail inbox)
5. Copy the setup from the first image above, with a paragraph using `*|IFNOT:FNAME|*` and another using `*|IF:FNAME|*`
6. Send the campaign and confirm both emails are sent with the appropriate greeting
7. Change your newsletter setup to use ActiveCampaign
8. Draft a new blank newsletter and add a block
9. Confirm the instructions now refer to …
> feat: conditional content tags

- src/service-providers/mailchimp/ProviderSidebar.js
After https://github.com/Automattic/newspack-newsletters/pull/1156 the metabox in the creation of a Subscription List is showing groups as well as Audiences. Only Audiences should be displayed there.
1. In `master` set up a site with Mailchimp and make sure Mailchimp account have some groups
2. Go to Newspack > Settings and make sure you see Audiences and groups there
3. Click to "Add new" Newsletter
4. Confirm that in the SEND TO section, under "Audiences:" you see all Audiences and groups
5. Checkout this PR and build the plugin
6. Confirm that now you only see Audiences there
> feat: fix SEND TO mailchimp audiences

- src/editor/blocks/conditional-content/style.scss
#1165 didn't account for #1162. This PR fixes the [linter error](https://app.circleci.com/pipelines/github/Automattic/newspack-newsletters/3028/workflows/4df2cee2-2049-4cbb-b86e-8e020a86dc3f/jobs/10177).
> chore(lint): replace css rule to use inset

- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
Givers user better feedback when the API key is invalid
1. Connect a site with Mailchimp nd confirm it works
2. On `master` Set an invalid API key for Mailchimp
3. Confirm that you don't see any error messages in Newspack > Engagement > Newsletters, nor in Newspack > Settings
4. checkout this branch
5. Confirm you see an error message in Newspack > Engagement > Newsletters
> feat: better feedback to the user about api error

- includes/class-newspack-newsletters-renderer.php
WordPress columns block supports choosing whether or not to stack the columns on mobile. The current implementation with MJML will always stack regardless of the selected block options.
This implements the support for non-stacking on mobile through a `mj-group` containing the columns.
| Editor | Rendered |
| --- | --- |
| <img width="1104" alt="image" src="https://github.com/Automattic/newspack-newsletters/assets/820752/3cf845fe-6e59-4158-a743-4cf3ee784e0f"> | <img width="342" alt="image" src="https://github.com/Automattic/newspack-newsletters/assets/820752/436eebad-5ea7-4048-bc3b-f2b4322d2fb8"> |
1. While on master draft a new newsletter and add 2-column blocks with images, like in the example above
2. Edit the columns block and make sure it's set to not stack on mobile
3. Save the draft …
> feat: support non-stacking on mobile

- includes/class-newspack-newsletters-settings.php
- includes/class-newspack-newsletters.php
Implements optional comments support for public newsletters.
1. Check out this branch and visit the Newsletter tab of "Newspack -> Engagement"
2. Confirm you see the new checkbox for `Support comments in public newsletters posts`
3. Toggle it on
4. Send/publish a new newsletter set to public
5. Confirm the "Discussion" panel is available and comments can be toggled on and off
6. Toggle it on and save
7. Visit the post and confirm comments are available
8. Visit the Newsletters settings outside Newspack's wizard (Newsletters -> Settings)
9. Confirm you see the same field
10. Toggle it off and save
11. Refresh the post page and confirm comments are no longer available
> feat: optional comments support

- includes/class-newspack-newsletters-editor.php
- src/editor/style.scss
The use of `!important` in the font size rules is enforcing the fixed size of `20px` to be replaced with `font-size: var( --wp--preset--font-size--normal );`, which renders 16px.
This PR removes the flag from all the font-size rules. cbc25b074c4ddcc8d1166a7769a62f2b880efbd9 also fixes the reason the rules were added in #1144. `after_setup_theme` is executed too early and the global post is not available for the `self::is_editing_email()` check. The font sizes were never registered.
1. Check out this branch and draft a new newsletter
2. With 5 paragraphs, change their font sizes to S, M, L, XL, and a custom fixed of 20px 
3. Confirm they render 12px, 16px, 24px, 36px, and 20px respectively
4. Send the newsletter and confirm the sizes persist
> fix: remove important flag from font size rules

- src/blocks/subscribe/edit.js
- src/blocks/subscribe/editor.scss
- src/blocks/subscribe/index.php
- src/blocks/subscribe/style.scss
- src/blocks/subscribe/view.js
The success message of the Subscription Form Block should render and be edited like RAS' Reader Registration Block:
1. While on the master branch, add a subscription form block to a new page
2. Check out this branch and without editing the block, subscribe using the block and confirm the new UI works
3. Edit the page, customize the message in the "Success" state, and confirm the custom message works as expected
> feat(subscribe-form): improve success message

- src/blocks/subscribe/style.scss
In very extreme cases -- like on smaller screens, or in narrower/super padded containers, the Newsletter Subscription block's input field can push out of the container.
This PR adds a width to the text container, which seems to fix it 🤞 
See: 1200550061930446-as-1203833168966390
1. Add a few Newsletter Subscription blocks to your content, with a mix of settings: with and without names fields, inside of groups, inside of columns. You can also copy-paste this starter content (though it'd be good to add at least one weird setting of your own):
<details>
<summary><strong>Newsletter Block text code</strong></summary>
```
<div class="wp-block-columns">
<div class="wp-block-column"></div>
<div class="wp-block-column"></div>
<div class="wp-block-column"></div>
</div>
<div …
```
> Newsletter Block: add a width to the email inputs to prevent overflow

- includes/class-newspack-newsletters.php
This PR includes author archives in the list of archives the public newsletters can appear on. The archives originally functioned this way, but it was accidentally changed as part of #1138. 
See: 1200550061930446-as-1204818298347108
1. Create at least one newsletter on your test site; assign it a category or tag, and set it to publish publicly; send.
2. View your author archive page; note that none of your newsletters appear there.
3. View the archive for the matching category/tag archive; note it does appear there. 
4. Apply this PR.
5. Confirm that the public newsletters now appear in your author archive. 
6. Confirm that the public newsletters still appear on their assigned category/tag archive pages, too.
> fix: allow public newsletters in author archives

- src/blocks/subscribe/edit.js
- src/blocks/subscribe/editor.scss
- src/blocks/subscribe/style.scss
Fixes a minor but annoying bug in which the `RichText` component for the submit button in the editor for Subscription Form blocks doesn't allow spaces if it's nested inside a `button` element. This fix changes the `button` element to a `div` with the same styles, in the editor only. See also https://github.com/Automattic/newspack-blocks/pull/1479
Closes `1204751246381643/1204483195828260`.
1. On `master`, add a Subscription Form block to a post or page.
2. Observe that you can edit the submit button labels but can't add spaces in either case.
3. Check out this branch, repeat step 2 and confirm that you can now add spaces, and that both editor and front-end styles and behavior are otherwise unchanged.
> fix(subscribe-block): allow spaces in submit button

- src/blocks/subscribe/index.php
Even though there's not a proper UI yet for determining the order to display newsletter subscription lists in the "Newsletter Subscription Form" block, the stored array order should be preserved.
1. While on the `release` branch, select different lists on a "Newsletter Subscription Form" block
2. Make sure to select a list on the bottom first, and another at the top
3. Confirm that the bottom list is rendered first in the editor
4. Visit the page and confirm it's not reflected on the page
5. Check out this branch, refresh, and confirm it's rendering in the expected order.
> fix: preserve list order on subscribe block

- src/blocks/subscribe/view.js
Ensures that the `input` element used by reCAPTCHA is not autofilled by the browser.
Note that I wasn't able to replicate the autofilling issue, but adding the `autocomplete="off"` attribute _should_ prevent the field from getting autofilled by most browsers. See also https://github.com/Automattic/newspack-plugin/pull/2517
Closes `1204751246381643/1204838932706810`.
1. Turn on autofill for your browser and ensure that there is a saved email address that will automatically autofill any email inputs.
2. Test on `master` first, with reCAPTCHA v3 enabled in the Connections wizard. Submit a newsletter signup block form. Does it fail?
3. Check out this branch and test again. The form should submit without errors.
> fix: disable autocomplete for recaptcha input

- src/blocks/subscribe/editor.scss
Wraps all the styles for the Newsletter Subscription Form block inside `.editor-styles-wrapper {}` so it can get picked up by the iframed editor when changing preview options.
1. While on the master branch, add a "Newsletter Subscription Form" block to a page
2. Change the page Preview option to "Tablet"
3. Confirm the styles are not rendering
4. Switch to this branch and build
5. Refresh the editor, repeat step 2, and confirm it renders correctly
> fix(subscription-block): css on tablet/mobile editor preview

- includes/class-newspack-newsletters-renderer.php
- includes/email-template.mjml.php
- includes/tracking/class-admin.php
- includes/tracking/class-click.php
- includes/tracking/class-data-events.php
- includes/tracking/class-pixel.php
- includes/tracking/class-tracking-pixel.php
- includes/tracking/class-utils.php
- newspack-newsletters.php
- tests/test-tracking.php
Implements pixel and click-tracking for sent newsletters.
The pixel is appended to the body of every sent email and increments a post meta as well as sends out a [data event](https://github.com/Automattic/newspack-plugin/blob/08e53ff639ffe3c58573b4f368f1db7285ff4055/includes/data-events/README.md) called `newsletter_opened` with the newsletter ID and email address.
The click tracker filters the existing `newspack_newsletters_process_link` to replace the URL with a proxied version. The redirection handler increments a post meta and sends a data event named `newsletter_clicked` with the newsletter ID, email address, and destination URL.
Both data events should be listed in the Connections -> Webhooks while editing/adding a webhook. (with `define( 'NEWSPACK_EXPERIMENTAL_WEBHOOKS', true );`) …
> feat: pixel and click-tracking

- src/blocks/subscribe/index.php
- src/blocks/subscribe/style.scss
- src/blocks/subscribe/view.js
Fixes a bug where if more than one Newsletter Subscription Form block exists on a single page, and signing up for one form results in a new reader account registration, submissions of other form instances will fail due to the initial nonce value being invalidated by the first form submission.
Also slipped in a couple of CSS changes for the error messaging, and added a proper error message response if nonce verification fails (so you get a more useful error message than the SyntaxError).
Closes `1200550061930446/1205129530451151`.
1. On `master`, using a RAS-enabled site, create a post or page that contains more than one Newsletter Subscription form, each one pointing to a different list or group in your ESP.
2. In a new session, sign up for a newsletter using a new email address. Then, …
> fix: allow multiple subscribe forms to be submitted on one page

- src/blocks/subscribe/index.php
Prevents the subscription form logic from continuing if unable to create contact.
#1231 introduced a new captcha token as part of the returned payload but the `$result` might be a `WP_Error`, which should be handled.
1. While on the `release` branch force the `Newspack_Newsletters_Subscription::add_contact()` to return an error by adding `return new WP_Error( 'custom_error', 'My custom error' );` on line 346 of `includes/class-newspack-newsletters-subscription.php`
2. Subscribe using a Newsletter Subscription Form block
3. Confirm the unhandled error
4. Check out this branch, repeat step 2, and confirm the correct error message is rendered
> fix(subscription-form): return if unable to add contact

- includes/class-newspack-newsletters-subscription.php
- includes/class-subscription-list.php
- includes/class-subscription-lists.php
- includes/service-providers/class-newspack-newsletters-service-provider.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
- tests/test-subscription-list.php
- tests/test-subscription-lists.php
- tests/trait-lists-setup.php
This PR refactors how we store the lists configuration.
Instead of saving the lists configuration as an option in the database, we now create a custom post for each list. We are using the same post type used to store "local" lists, but it has been extended so it now also serves to store "remote" lists.
"local" lists are those lists that are created via wp-admin. When we create a local list, the plugin creates a tag (or group) in the ESP
"remote" lists are the lists that are dynamically fetched from the ESP. Those lists are always managed in the ESP. Users can set an alternate title and description for them, but this information is used only in the site and is not sent to the ESP.
Everytime a user visits the admin page:
* we fetch all the lists from the ESP
* we get a post that represents …
> feat: refactor how we store lists configuration

- src/blocks/subscribe/index.php
Fixes the order of events when signing up for newsletters via the Subscription Form block.
1. On `master`, sign up for a newsletter via the Subscription Form block.
2. Continue navigating the site and observe that you're not segmented as a newsletter subscriber.
3. Check out this branch, repeat in a new session. Confirm you're now segmented properly and have the `np_reader_1_is_newsletter_subscriber` set in `localStorage`.
> fix: register before adding contact

- includes/class-newspack-newsletters-editor.php
- includes/class-newspack-newsletters-renderer.php
Implements two new filters to allow additional blocks to render in an email:
- `newspack_newsletters_allowed_block_types`: Filters the list of allowed block types in the newsletter editor.
- `newspack_newsletters_render_mjml_component`: Filters the block MJML markup for email rendering.
1. Check out this branch and paste the following code at the end of the `newspack-newsletters.php` file to test the filters usage:
```php
/**
* Allow the Table block in the editor.
*/
add_filter(
'newspack_newsletters_allowed_block_types',
function( $allowed_block_types ) {
$allowed_block_types[] = 'core/table';
return $allowed_block_types;
}
);
/**
* Render the Table block as an MJML table.
*/
add_filter(
'newspack_newsletters_render_mjml_component',
function( $markup, $block, $is_in_column, $is_in_group, …
```
> feat: add filters to support additional blocks

- src/ads/newsletter-editor/index.js
- src/components/send-button/index.js
- src/components/send-button/style.scss
- src/newsletter-editor/testing/index.js
1205078412187623-as-1205078412187635
Implements HTML preview before sending the newsletter:
The editor should also be able to change the ad settings or send a test email in this modal screen.
A new "Preview Email" button also renders the HTML in a modal, but without the sending functionality:
1. Make sure you have active newsletters ads configured
2. Set your newsletter provider as "Manual" and draft a new newsletter
3. Click "Preview email" and confirm the modal renders with injected ads
4. Close the modal and click to Send
5. Toggle the "Disable automatic insertion of ads" on and confirm it updates the HTML
6. Back to Newsletters settings, change your provider to a supported ESP
7. Repeat steps 3-5
8. Send a test newsletter and confirm you receive the expected content
9. Send the …
> feat: preview html

- includes/class-newspack-newsletters-ads.php
- includes/class-newspack-newsletters-renderer.php
- includes/tracking/class-admin.php
Implements impression and click tracking to newsletter ads.
1. Check out this branch and send a newsletter ensuring that ads will be inserted
2. Open the email, make sure to allow the images to render, and click the ad
3. Confirm the count updates in the Newsletters -> Ads dashboard table
> feat: ad tracking

- includes/class-newspack-newsletters-ads.php
- includes/class-newspack-newsletters-editor.php
- includes/class-newspack-newsletters-renderer.php
- includes/class-newspack-newsletters.php
- includes/tracking/class-admin.php
- src/ads/editor/index.js
Implements the following new tax and meta fields for Newsletter Ads:
- Start date field
- Price field
- Advertisers taxonomy
- Categories taxonomy (same as posts/newsletters)
The taxonomies determine the following:
1. Newsletters associated with an advertiser should only render ads that are also associated with that same advertiser
2. Ads associated with a category should only be rendered in newsletters that are also associated with that category
That means newsletters without any advertiser association can render ads from any advertiser. That also means that ads without any categories can be rendered on any newsletter.
1. Check out this branch and create an ad with a future start date
2. Draft a new newsletter, save, click to preview, and confirm the ad doesn't render
3. Edit the ad and …
> feat: ads taxonomies and fields

- includes/class-newspack-newsletters.php
- includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
- includes/service-providers/class-newspack-newsletters-service-provider.php
- includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
- src/editor/api/index.js
- src/newsletter-editor/editor/index.js
- src/newsletter-editor/sidebar/index.js
- src/service-providers/active_campaign/ProviderSidebar.js
- src/service-providers/constant_contact/ProviderSidebar.js
- src/service-providers/mailchimp/ProviderSidebar.js
Implements support for custom campaign names for Mailchimp, ActiveCampaign, and Constant Contact.
1. Make sure you have Mailchimp, ActiveCampaign or Constant Contact as your ESP
2. Draft a new newsletter and confirm you see the input above with the default "Newspack Newsletter (Post ID)"
3. Save the draft and confirm the draft is saved in the ESP with the expected campaign name
4. Delete the input and confirm the placeholder renders the default value, save the draft and confirm the default value persists
5. Add a custom text, save and confirm the draft is updated on the ESP
> feat: custom campaign name

- includes/class-newspack-newsletters-renderer.php
Prevents the renderer processing of links to be executed more than once for the same - already processed - link URL.
Also removes the unused `$ads_to_insert` private static variable.
1. Make sure you have a valid newsletter ad with inner link
2. Place the ad through a Newsletter Ad block on a new newsletter draft
3. Save the draft multiple times
4. Click on "Preview email" and confirm the ad link URL is correct (without multiple repeated arguments) and redirects without issues
> fix: avoid reprocessing links

- src/editor/blocks/posts-inserter/query-controls.js
Fixes an impossible UI state in the Posts Inserter block.
1. Make sure you have at least 1 sponsored post on your test site.
2. Create a new newsletter and add a Posts Inserter block set to display specific posts.
3. Choose the sponsored post to appear in the block. On `master`, observe that the "Display sponsored posts" option remains available in block settings, but has no effect due to the "specific posts" behavior forcing the sponsored post to be displayed.
4. Check out this branch and refresh the newsletter. Now confirm that if "Display specific posts" is turned on for the Posts Inserter block, the "Display sponsored posts" option disappears as it's no longer relevant.
> fix(posts-inserter): avoid conflicting UI state

- includes/class-newspack-newsletters-renderer.php
> fix: width behavior in buttons blocks with defined widths

- includes/class-newspack-newsletters-subscription.php
Fixes a fatal error that occurs if the main Newspack plugin isn't available, due to a non-existent `\Newspack\Reader_Activation` class. 
1. On `release`, deactivate the Newspack plugin.
2. Delete any user from the Users admin page. Observe a fatal error:
```
PHP Fatal error:  Uncaught Error: Class "Newspack\Reader_Activation" not found in /newspack-repos/newspack-newsletters/includes/class-newspack-newsletters-subscription.php:523
Stack trace:
#0 /var/www/html/wp-includes/class-wp-hook.php(310): Newspack_Newsletters_Subscription::delete_user()
#1 /var/www/html/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#2 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action()
#3 /var/www/html/wp-admin/includes/user.php(380): do_action()
#4 /var/www/html/wp-admin/users.php(211): …
```
> fix: fatal error from nonexistent class in main plugin

- includes/class-newspack-newsletters-renderer.php
Adds the newsletter post_id to the `newspack_newsletters_render_mjml_component` filter, so it can be accessed when the filter is used.  This is helpful when you need to conditionally update a block's mjml based on the post details.  
One example where this will help CalMatters:  we have four newsletters and each one has a different image and links in the header, which is styled in a custom block.  With this update, we can use the post_id to check the newsletter category and customize the mjml for each newsletter.  
Example code to test the filter by modifying a core block:
```php
/**
* Render a custom block.
*
* See https://documentation.mjml.io/ for MJML documentation.
*/
add_filter(
'newspack_newsletters_render_mjml_component',
function( $mjml, $block, $is_in_column, $is_in_group, …
```
> Add newsletter_id param to newspack_newsletters_render_mjml_component

- includes/class-newspack-newsletters-subscription.php
- includes/plugins/class-woocommerce-memberships.php
Adds some checks and early returns to avoid extraneous firings of the `add_contact` method which will result in additional requests to the connected ESP. There is no need to sync the contact to the ESP upon reader registration if the reader registration is happening as a side effect of either subscribing to a newsletter via the Newsletter Subscription Form block, or adding the user account to a Woo Memberships plan that doesn't restrict any newsletter lists.
1. On `release`, make sure your site is connected to an ESP and you've enabled at least one Group or local list in Newspack > Engagement > Newsletters.
2. Add a Newsletter Subscription Form block to a post or page. Enable a single list for that block.
3. Add `define( 'NEWSPACK_LOG_LEVEL', 2 );` to your wp-config.php so we know when …
> fix: avoid duplicate firing of add_contact

- src/blocks/subscribe/block.json
- src/blocks/subscribe/edit.js
- src/blocks/subscribe/editor.scss
- src/blocks/subscribe/index.php
This PR adds an option to change the button colour in the subscribe block; as part of this change, there's also a small theme PR to make sure the palette colours get picked up correctly: https://github.com/Automattic/newspack-theme/pull/2177
A couple specific things to call out:
* My previous attempt (#1279) tried to copy how the Checkout button handles this, but then realized there wasn't an easy way to add text recommending using colours that stand out. So this is a bit of a franken-attempt, nesting a `PanelColorSettings` inside of a `PanelBody` 😅 and probably a couple other minor crimes. (The other option was two separate `ColorPickers`, but they ate up a lot of space!).
* I added a normally-unnecessary check for the default colours so they're not output as inline styles. This is …
> feat: add color picker for the subscribe block button

- includes/class-newspack-newsletters.php
- includes/service-providers/active_campaign/class-newspack-newsletters-active-campaign.php
- includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
- src/components/init-modal/screens/layout-picker/index.js
- src/components/send-button/index.js
- src/editor/api/index.js
- src/newsletter-editor/editor/index.js
- src/newsletter-editor/index.js
- src/newsletter-editor/layout/index.js
- src/newsletter-editor/utils.js
- src/service-providers/active_campaign/ProviderSidebar.js
- src/service-providers/campaign_monitor/ProviderSidebar.js
Fixes the editor stuck in dirty state even after saving due to two issues:
- The unsynced handling of `newsletterData` meta in the front-end
- Transforming the apiFetch original payload when saving the post
You may still get an unexpected "unsaved changes" alert with the Post Inserter block when the posts are not inserted. Its editing state regenerates the block attributes on component rerenders and fixing that issue requires a bigger refactor that is not covered in this PR.
The `newsletterData` is now handled in the backend and the apiFetch original payload is no longer modified, as it doesn't impact the middleware functionality.
Other improvements were made for the sake of simplicity and readability:
- Refactored the `NewsletterEdit` and `LayoutPicker` components to use hooks instead of …
> fix: newsletterData handling and editor improvements

- src/blocks/subscribe/index.php
We've seen reports from readers that the honeypot field sometimes gets autofilled by Chrome's built-in password manager, despite the `autocomplete="off"` attribute. (Probably because Chrome [intentionally ignores this attribute](https://adamsilver.io/blog/stopping-chrome-from-ignoring-autocomplete-off/)). There's not much we can do to prevent this frustrating behavior, but since the honeypot is kind of redundant/unnecessary if protecting forms with reCAPTCHA, this PR proposes we only render the honeypot if reCAPTCHA is not on, as a sort of fallback security measure. Since most Newspack sites enable reCAPTCHA to protect their form inputs, this should sidestep the autocomplete issue for most readers.
See also https://github.com/Automattic/newspack-plugin/pull/2667
1. Check out this branch. …
> fix: remove honeypot field if using reCAPTCHA

- includes/class-newspack-newsletters-renderer.php
Populates an `alt` attribute on `mj-image` elements in the rendered email markup. Implements fallbacks to make sure something is always populated even if the expected field is empty. Given the following media library fields, the attribute is populated with the value of the first non-empty field:
- Alternative text
- Caption
- Description
- Title (all media library attachments get a title auto-generated from the filename, so this will always contain some value)
1. Add some values to a media library attachment in the fields described above.
2. Create a new newsletter. Add the attachment as an image block.
3. Send yourself a test email (or if using the "Other" ESP option, just click "Send" to render via MJML and get the HTML).
4. Confirm that the image block is always rendered with a …
> feat: add alt attr to mj-image elements

- includes/class-newspack-newsletters-ads.php
- includes/tracking/class-click.php
- includes/tracking/class-data-events.php
- includes/tracking/class-pixel.php
- tests/test-tracking.php
The existing approach for processing the pixel and click tracking processes the requests in the `template_redirect` hook, which can potentially be quite heavy being a hook called farther down the hook tree.
Removing the custom rewrite rule allows the hook to be executed early in `init`, which is executed much earlier, reducing the load of such requests.
The rewrite rule and the hook to `template_redirect` will continue to exist for backward compatibility, but every new newsletter sent will use a query parameter, which will be executed in the new hook.
1. While on the `release` branch, send a newsletter with links
2. Check out this branch
3. Open the newsletter in your inbox and make sure to allow images to render
4. Click on any link in the newsletter
5. Go to the newsletters dashboard …
> fix: execute tracking in an earlier hook

- README.md
- newspack-newsletters.php
- readme.txt
- src/branding/index.js
- tests/test-renderer.php
Updates some lingering legacy URLs throughout the code. All instances of newspack.pub or newspack.blog should be newspack.com
No functional changes.
> chore: newspack.pub > newspack.com

- src/editor/style.scss
This PR acts as a temporary fix for an issue we're seeing with the Newsletter editor + FSE themes that isn't happening with Classic themes: classic themes load a CSS file in the editor (/wp-includes/css/dist/edit-post/classic.min.css) that includes this style:
```
.editor-styles-wrapper .wp-block { 
margin-left:auto; 
margin-right:auto;
}
```
This CSS isn't loaded with FSE themes. In Newsletters, the max-width of 600px is still applied, but some blocks end up aligned left. This PR adds a temporary fix, adding the auto margin on the left and right to the editor. Long-term, we'll work on some more "proper" FSE support. 
See: 1200550061930446-as-1205636043694685
1. On a site running Newspack, start a new newsletter; if you use one of the premade templates with the top solid bar of colour, …
> fix: correct newsletter editor alignment with FSE

- src/blocks/subscribe/block.json
- src/blocks/subscribe/edit.js
- src/blocks/subscribe/index.php
1200550061930446-as-1205543124448992
Support toggling and storing the checkbox state for defining the initial form state:
1. Draft a new page and add a Newsletter Subscription Form block
2. Enable multiple lists and toggle their checkbox state in the editor
3. Save, refresh, and confirm the selected state is preserved
4. Visit the page and confirm the selected state is also reflected on the page
> feat(subscription-form): custom checkbox state for lists

- src/components/init-modal/screens/layout-picker/index.js
- src/components/init-modal/style.scss
I'm not sure which WP version introduced the shift in the layout but the init modal looks broken. This PR fixes the issue.
__Before__
__After__
1. Create a new newsletter, the modal should be broken
3. Refresh the screen with the modal.
> fix: init modal header misalignment

- includes/tracking/class-pixel.php
- tests/test-tracking.php
Make the cycling log files approach for pixel tracking (#1317) the default strategy.
> fix(tracking): make the log cycling strategy default for pixel tracking

- includes/class-newspack-newsletters-ads.php
- tests/test-newsletter-ads.php
If the newsletter ad has a past start date, it will considered "active" regardless of the end date. This PR makes sure to check both start and end dates.
1. While in the `release` branch, create a new newsletter ad
2. Set its "start_date" to a past date through CLI: `wp post meta update {post_id} start_date "2023-01-01T00:00:00.000Z"`
3. Set its "expiry_date" to another past date through CLI: `wp post meta update {post_id} expiry_date "2023-02-01T00:00:00.000Z"`
4. Draft a new newsletter, preview, and confirm the ad renders even though it's supposed to be expired
5. Check out this branch, save the draft newsletter again, and preview
6. Confirm the ad no longer renders
7. Modify the ad "expiry_date" to somewhere in the future: `wp post meta update {post_id} expiry_date …
> fix: active ad start/end date check

- includes/service-providers/class-newspack-newsletters-service-provider.php
- includes/service-providers/interface-newspack-newsletters-esp-service.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp-groups.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp-usage-reports.php
- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
- newspack-newsletters.php
- tests/test-usage-reports.php
Adds a usage report class, for retrieving ESP data. A report is an array of arrays representing days of activity. Currently it's hard-coded to retrieve the last day only, but this can be amended later. 
Currently this is only implemented for Mailchimp, handling more ESPs to come. 
1. Observe that the tests are passing.
2. With Mailchimp set as the ESP, run `wp eval "echo print_r( (\Newspack_Newsletters::get_service_provider())->get_usage_report(1) , true );"` in the console – observe an appropriate array printed
3. Switch ESP to another, run the snippet again – observe that its value is a `newspack_newsletters_not_implemented` WP Error
> feat: mailchimp usage data report

- includes/class-newspack-newsletters-editor.php
Prevents the "Conditional Content" block feature from being rendered in other email editors. It should only be rendered for newsletters, where it can benefit from the ESP capabilities of conditional content.
1. While on the master branch, edit the "Receipt" email from "Newspack -> Reader Revenue -> Emails"
2. Edit a block and confirm you see the "Conditional Content" panel
3. Checkout this branch, refresh the page, and confirm the panel is no longer available
4.  Draft a new newsletter and confirm the "Conditional Content" panel renders
> fix: restrict conditional content to newsletters

- includes/email-template-mjml.css
This PR adds a small bottom/top margin to lists (12px). Prior to this, lists felt very compact.
I also changed the list-style-position to inside because in some email clients, the bullet points were outside the screen.
__Before__
__After__
1. Send a (test) newsletter with a bunch of lists
2. Switch to this branch and refresh
3. Resend newsletter
> fix: add margin to lists and list style position

- includes/tracking/class-pixel.php
No longer delete `notoptions` and `alloptions` from object cache as it's not ideal to have it executed every minute and can cause CPU spikes.
> fix(tracking): don't flush options cache on log processing

- includes/class-newspack-newsletters-subscription.php
- includes/service-providers/class-newspack-newsletters-service-provider.php
- src/blocks/subscribe/index.php
When subscribing, each selected list generates one (or more) ESP API requests. When subscribing to multiple lists the form may take more than 7 seconds to resolve, which is not reasonable.
This PR implements an `async` parameter to the `Newspack_Newsletters_Subscription::add_contact` method. This parameter should be used by the Newsletter Subscription Form and Reader Registration blocks when subscribing readers.
2191b5758a693994111df5d2ae9b671b7b1bff07 introduces a subscription intent system, which allows the backend to recover from server hiccups or other reasons for a subscription attempt to fail while performed asynchronously.
The subscription intent is stored and processed 3 times, once every minute, before giving up. If the subscribed email is an existing user, a user meta stores the …
> feat(subscription): support async `add_contact()`

- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
When syncing metadata fields to Mailchimp merge fields, we hit the [merge-fields endpoint](https://mailchimp.com/developer/marketing/api/list-merges/list-merge-fields/). By default, this endpoint only returns a max of 10 results. So if there are more than 10 merge fields in the audience (likely there will be), we won't see all of the available fields and will attempt to create duplicates of fields that have already been created.
1. On `master` in this plugin and Newsletters, set up RAS, connect Mailchimp as the ESP and set an audience in RAS advanced settings.
4. As a new reader, purchase a donation or non-donation product without signing up for any newsletters and observe that in Mailchimp, only a small amount of reader data is synced to the contact in Mailchimp, and few or none of the …
> fix(ras): contact syncing to mailchimp

- src/components/init-modal/screens/layout-picker/index.js
Fixes a regression introduced in #1287.
Layouts with custom styles (custom font, background color, or custom CSS) do not have their settings applied to newsletters when selected. This PR ensures the layout meta is applied to the newsletter.
1. While in the master branch, draft a new newsletter with custom styles like the example above
2. Save this newsletter as a new layout
3. Draft a new newsletter and select the new layout
4. Confirm the styles are not applied
5. Check out this branch, refresh, and draft a new newsletter selecting the style
6. Confirm all the styles are applied
> fix: add layout styles to newsletter

- includes/class-newspack-newsletters-editor.php
Ensures the editor localized variables that may be required by blocks are available when editing block patterns. Fixes the fatal crash when editing a pattern containing a Post Inserter block with sponsored posts.
1. While on the master branch, draft a new newsletter with the Post Inserter block
2. Make sure the Post Inserter block is rendering a sponsored post and save the block as a new pattern
3. Visit Posts -> Patterns and edit the recently created pattern
4. Confirm the block crashes
5. Check out this branch, refresh, and confirm the pattern renders without issues
> fix(editor): ensure localized variables while editing patterns

- includes/plugins/class-woocommerce-memberships.php
Fixes a small issue. 
1. On `master`,
1. Create a user with a membership
2. Set ESP to "Other"
3. Try to delete the user, observe it fails
4. Switch to this branch, repeat, observe the user can be deleted
> fix: memberships & "other" ESP

- includes/class-newspack-newsletters-renderer.php
1200550061930446-as-1205996773681761
Group blocks placed in the root of the body are processed outside the usual `render_mjml_component()` method so they didn't have the conditional tags properly applied.
This PR ensures the conditional tags are rendered for such blocks.
1. Make sure you have your ESP setup to Mailchimp
2. While in the master branch, draft a new newsletter
3. Add a group block with some content and set the conditional tags to any rule, like `*|IF:FNAME|*` and `*|END:IF|*`
4. Add a paragraph block below that one and apply the same rule
5. Save the draft and click to preview
6. Confirm only the paragraph is contained in the conditional tags
7. Check out this branch, save the draft and preview again
8. Confirm both blocks are contained in the conditional tags
> fix(renderer): ensure group blocks use conditional tags

- includes/plugins/class-woocommerce-memberships.php
Currently, every time a user is granted a membership, they get add to all lists behind that membership.
If a membership is paused and then restored, the user will be re-added to all lists, even if they opt out of some of the lists at some point.
We recently found out that every membership that is tied to a Subscription, will be put on pause and active again when the subscription is being renewed. This could amplify this problem.
What this PR does is:
* When a membership is deactivated, we store which of the lists behind the membership the user is actually subscribed to
* Whenever a membership is reactivated, we will only resubscribe the user to the lists they were before (which could be none)
1.Create a membership plan
2. Configure Newsletters with 2 or more lists
3. In the membership …
> fix: store and recover lists on membership reactivation

- includes/tracking/class-click.php
1200550061930446-as-1206176822900759
Supersedes #1381.
The ESP may add UTM parameters to the URL. When combined with the click-tracking functionality that will be added to the proxied URL and ignored because it's not in the destination URL. This PR allows UTM parameters to be passed along to the destination URL, so this:
```
https://example.com/?np_newsletters_click=1&id=123&url=https%3A%2F%2Fexample.com%3Futm_medium%3Demail&em=*|EMAIL|*&utm_campaign=test_campaign
```
Gets redirected to this:
```
https://example.com/?utm_medium=email&utm_campaign=test_campaign
```
There may be a case to pass along any added query parameter not part of the click-tracking configuration (`np_newsletters_click`, `id`, `url`, `em`), but I believe that requires further discussion.
1. Draft a new newsletter, add …
> feat(tracking): support UTM coming from the ESP

- includes/class-newspack-newsletters-subscription.php
Changes the newsletters' `reader_registered` hook to only `add_contact()` if there are lists to subscribe to. The `add_contact()` method should no longer be used for data sync purposes, only subscriptions.
The sync strategy is already performed through different strategies in the main plugin, where it belongs:
- https://github.com/Automattic/newspack-plugin/blob/f8d35ec6b092a2078a742a0ee04926801ef74fdc/includes/data-events/connectors/class-mailchimp.php#L36-L38
- https://github.com/Automattic/newspack-plugin/blob/f8d35ec6b092a2078a742a0ee04926801ef74fdc/includes/reader-revenue/woocommerce/class-woocommerce-connection.php#L363-L385
1. Check out this branch and confirm you have RAS enabled with Mailchimp
2. Make sure you have a data sync Mailchimp audience selected in RAS' advanced settings …
> fix: prevent the use of `add_contact` for data sync purposes

- includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php
When checking the sender email domain, pull all verified domains from MC api. Currently we are pulling only 10, which is the default return from the api.
1. Edit a Newsletter
2. Set the sender
3. Make sure it work
If you don't have a mailchimp account with more than 10 verified domains, you can check just doing an api request and playing with the `count` argument to confirm it works
> fix: get all verified domains from Mailchimp

- src/components/send-button/index.js
- src/components/send-button/style.scss
Tweaks some newsletter editor components to isolate custom CSS only to our custom modal elements. Currently some of our custom editor styles are bleeding into core modal components as well.
Fixes `1206197591054328/1206312385969911`
1. On `master`, edit a newsletter, click the three-dots icon, then Preferences, then "Blocks" in the modal that appears.
3. Observe that the top of the "Blocks" preferences are not shown. The highlighted area is hidden and can't be scrolled to. (You can repeat these steps in a regular post editor to see what it should look like).
4. Check out this branch and repeat in the newsletter editor. Confirm that all Blocks preferences are now viewable and interactive in the Preferences modal.
5. Smoke test the custom Newsletter modals to make sure they still work as …
> fix: apply custom editor modal styles only to newspack modals

- includes/class-newspack-newsletters-ads.php
- includes/class-newspack-newsletters-layouts.php
- includes/class-newspack-newsletters-quick-edit.php
- includes/class-newspack-newsletters-settings.php
- includes/class-newspack-newsletters-subscription.php
- includes/class-newspack-newsletters.php
- includes/class-subscription-list.php
- includes/class-subscription-lists.php
- includes/service-providers/class-newspack-newsletters-service-provider.php
- includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
Registers the newsletter CPT with a custom `capability_type`, in order to allow granular control over access to this CPT.
Also adds a small tweak for handling "Other" provider in some methods. 
1. As an administrator or editor user, ensure that the following can all be edited:
2. Newsletters
3. Newsletter Ads
4. Newsletter Ads Advertisers
5. Subscription Lists (via Newspack's Engagement wizard UI)
6. Layouts (via Newsletters post editor)  
2. Install the [capability-manager-enhanced plugin](https://wordpress.org/plugins/capability-manager-enhanced/) and create a new role in "Roles" submenu item
3. Go to "Capabilities" submenu item and select the new role. Select "Newspack Newsletters" group and assign all the caps
5. Due to a quirk in CME plugin, also assign these same caps in the …
> Use custom capability_type for the CPT

- includes/class-newspack-newsletters-ads.php
- includes/class-newspack-newsletters-layouts.php
- includes/class-newspack-newsletters-quick-edit.php
- includes/class-newspack-newsletters-subscription.php
- includes/class-newspack-newsletters.php
- includes/class-subscription-list.php
- includes/class-subscription-lists.php
- includes/service-providers/class-newspack-newsletters-service-provider.php
- includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
This reverts commit 59403a92ae0ec2b14549dc9c72d8495fca1e926a.
Closes # .
1.
2.
3.
> Revert "feat: use custom capability_type for CPTs (#1398)"

- includes/plugins/class-woocommerce-memberships.php
This PR fixes an issue I ran into on a client site. A membership plan can reference different subscription lists, and will continue referencing a subscription list if the associated CPT post is deleted. So when a user purchases a subscription and we're giving them access to subscriptions via their membership, an uncaught exception is thrown. This PR modifies a bit of code to make it more [in line with this piece](https://github.com/Automattic/newspack-newsletters/blob/075cd033d553c029ef64e5e652f031f17456e5d1/includes/plugins/class-woocommerce-memberships.php#L168-L173). 
I'm not sure the simplest way to test this. Create a Subscription List, assign it to a Membership Plan, delete the Subscription List, observe it's still in the Membership Plan.
> fix: Catch invalid subscription list errors
